import {createElement,Fragment,Component} from 'react';
import {designBoard,type SavedDesign} from '../lib/design-board';
import {studioMaterials,studioQuery,type StudioConfig} from '../lib/desk-v8';
import {downloadText} from '../lib/domain';
import {openDesignSheet} from '../lib/design-sheet';
import {Icon,Eyebrow} from './ui';
type Props={config:StudioConfig;ready:boolean;getEngine:()=>any;onSelect:(c:StudioConfig)=>void;notify:(s:string)=>void};
type State={items:SavedDesign[];busy:string;message:string;quality:string;arUrl:string;arPreview:string};
export class DesignWorkbench extends Component<Props,State>{
 state:State={items:designBoard.list(),busy:'',message:'',quality:'balanced',arUrl:'',arPreview:''};private alive=true;
 componentDidUpdate(previous:Props){if(!previous.ready&&this.props.ready)this.props.getEngine()?.quality(this.state.quality);if(studioQuery(previous.config)!==studioQuery(this.props.config)&&this.state.arUrl){URL.revokeObjectURL(this.state.arUrl);this.setState({arUrl:'',arPreview:''});}}
 componentWillUnmount(){this.alive=false;if(this.state.arUrl)URL.revokeObjectURL(this.state.arUrl);}
 screenshot=()=>{try{return this.props.getEngine()?.snapshot(960,640)||null;}catch{return null;}};
 save=()=>{const result=designBoard.add(this.props.config,this.screenshot());this.setState({items:designBoard.list(),message:result.status==='full'?'Üç seçenek dolu. Bir seçeneği kaldırıp yeniden ekleyin.':result.status==='duplicate'?'Bu tasarım karşılaştırmada zaten var. Görünümü yenilendi.':'Seçili tasarım karşılaştırmaya eklendi.'});};
 importFile=async(e:any)=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(!file)return;if(file.size>16384){this.setState({message:'Tasarım dosyası 16 KB sınırını aşıyor.'});return;}if(designBoard.list().length&&!window.confirm('Dosyadaki seçenekler mevcut karşılaştırmanın yerini alsın mı?'))return;try{const n=designBoard.import(await file.text());if(this.alive)this.setState({items:designBoard.list(),message:n+' tasarım yüklendi. Görüntüler, stüdyoda yeniden açtığınızda hazırlanabilir.'});}catch(error){if(this.alive)this.setState({message:error instanceof Error?error.message:'Dosya okunamadı.'});}};
 modelExport=async(format:'glb'|'usdz')=>{if(this.state.busy)return;this.setState({busy:format,message:'Seçili model dosyası hazırlanıyor.'});try{const signature=studioQuery(this.props.config),preview=this.screenshot();const blob:Blob=await this.props.getEngine().exportModel(format);if(signature!==studioQuery(this.props.config))throw Error('Configuration changed');if(!this.alive)return;const url=URL.createObjectURL(blob);if(format==='usdz'){if(this.state.arUrl)URL.revokeObjectURL(this.state.arUrl);this.setState({arUrl:url,arPreview:preview||''});}else{const a=document.createElement('a');a.href=url;a.download='Elif-Devir-01-Konsept.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}this.setState({message:format==='usdz'?'USDZ dosyası hazır. Uyumlu Apple cihazında AR önizlemesi açılabilir. Diğer cihazlarda dosya indirilebilir.':'GLB dosyası hazırlandı. Ölçek birimi metredir. Konsept geometri, CAD veya üretim dosyası değildir.'});}catch(error){if(this.alive)this.setState({message:'Bu cihazda model dışa aktarılamadı. Tasarım JSON dosyasıyla veya yazdırılabilir özetle devam edebilirsiniz.'});}finally{if(this.alive)this.setState({busy:''});}};
 render(){const p=this.props,s=this.state,selected=studioQuery(p.config);return <section className="v20-workbench" aria-labelledby="v20-board-title"><div className="v20-section-heading"><div><Eyebrow>TASARIM DEFTERİNİZ</Eyebrow><h2 id="v20-board-title">Bir karar vermeden,<br/><em>yan yana düşünün.</em></h2></div><button type="button" className="button" disabled={!p.ready||!!s.busy} onClick={this.save}>Bu tasarımı karşılaştır <Icon name="plus" size={17}/></button></div><p className="v20-intro">En fazla üç düzeni ayırın. Ölçüyü, yüzeyi ve çalışma yüksekliğini karşılaştırın. Her seçenek tek dokunuşla stüdyoya döner.</p>
 <div className="v20-comparison-grid">{s.items.map((item,i)=><article key={item.id} className={selected===studioQuery(item.config)?'selected':''}><div className="v20-compare-image">{item.preview?<img alt={'Tasarım '+(i+1)+' görünümü'} src={item.preview}/>:<span>Görünüm stüdyoda hazırlanır.</span>}<span className="v20-design-index">0{i+1}</span></div><h3>{studioMaterials[item.config.material].name}</h3><dl><div><dt>Tabla</dt><dd>{item.config.width} × {item.config.depth} cm</dd></div><div><dt>Yükseklik</dt><dd>{item.config.height} cm</dd></div><div><dt>Yan tabla</dt><dd>{item.config.angle}°</dd></div><div><dt>Işık</dt><dd>{item.config.lighting==='evening'?'Akşam':'Gün ışığı'}</dd></div></dl><div className="v20-compare-actions"><button type="button" onClick={()=>{p.onSelect(item.config);this.setState({message:'Tasarım '+(i+1)+' stüdyoya aktarıldı.'});}} aria-label={'Tasarım '+(i+1)+' stüdyoda aç'}>Stüdyoda aç <Icon size={14}/></button><button type="button" aria-label={'Tasarım '+(i+1)+' kaldır'} onClick={()=>{designBoard.remove(item.id);this.setState({items:designBoard.list()});}}><Icon name="close" size={15}/></button></div></article>)}{s.items.length===0&&<div className="v20-compare-empty"><span>01 / 02 / 03</span><p>Önce masayı size göre düzenleyin.<br/>Sonra karşılaştırmaya ekleyin.</p></div>}</div>
 <div className="v20-board-file"><button type="button" disabled={!s.items.length} onClick={()=>downloadText('Elif-Tasarim-Seceneklerim.json',designBoard.serialize())}>Seçenekleri JSON olarak sakla <Icon name="download" size={16}/></button><label>Kaydettiğim seçenekleri aç<input type="file" accept="application/json,.json" onChange={this.importFile}/></label></div><small className="v20-privacy-note">Bu defter yalnız açık sekmede tutulur. JSON dosyası not, adres, oda ölçüsü veya müşteri fotoğrafı içermez. Yenilemeden önce seçenekleri kaydedin.</small>
 <div className="v20-delivery-tools"><div><Eyebrow>STÜDYODAN GÖRÜŞMEYE</Eyebrow><h3>Tasarımınız burada kalmasın.</h3><p>Görseli ve ölçüyü bir arada yazdırın. Dijital modeli GLB veya USDZ biçiminde inceleyin.</p></div><div className="v20-export-buttons"><button type="button" disabled={!p.ready||!!s.busy} onClick={()=>{if(!openDesignSheet(p.config,this.screenshot()))this.setState({message:'Açılır pencere engellendi. Tarayıcınızdan bu siteye izin verin.'});}}>Görselli tasarım dosyası <Icon name="download" size={16}/></button><button type="button" disabled={!p.ready||!!s.busy} onClick={()=>this.modelExport('glb')}>{s.busy==='glb'?'GLB hazırlanıyor':'3D modeli indir · GLB'}</button><button type="button" disabled={!p.ready||!!s.busy} onClick={()=>this.modelExport('usdz')}>{s.busy==='usdz'?'USDZ hazırlanıyor':'AR dosyasını hazırla · USDZ'}</button>{s.arUrl&&<><a className="v20-ar-link" href={s.arUrl} rel="ar" download="Elif-Devir-01-Konsept.usdz"><img src={s.arPreview} alt=""/>USDZ modelini aç</a><small>AR açılması cihaz ve görüntüleyici desteğine bağlıdır. Yerinde ölçek ve zemin davranışı gerçek cihazda teyit edilmelidir.</small></>}</div></div>
 <div className="v20-quality"><label htmlFor="v20-quality">Görüntü profili</label><select id="v20-quality" value={s.quality} onChange={e=>{const quality=e.currentTarget.value;p.getEngine()?.quality(quality);this.setState({quality});}} disabled={!p.ready}><option value="balanced">Dengeli</option><option value="economy">Düşük grafik yükü</option><option value="detail">Ayrıntılı</option></select><small>Sahne çözünürlüğü ve gölge kalitesi değişir. Masa ölçüleri değişmez.</small></div>{s.message&&<p role="status" className="v20-workbench-status">{s.message}</p>}</section>}
}
