import {createElement,Fragment,Component} from 'react';
import {Icon,Link,Eyebrow,image,type PageProps} from './ui';
import {defaultStudio,normalizeStudio,studioFromQuery,studioQuery,studioSummary,studioMaterials,studioRequestMaterial,type StudioConfig} from '../lib/desk-v8';
import {projectStore,whatsappUrl} from '../lib/project';
import {downloadText,publicHref} from '../lib/domain';
import {evaluateRoomFit,type RoomFitResult} from '../lib/room-fit';

type Props={query?:string;compact?:boolean;navigate:PageProps['navigate'];notify:PageProps['notify']};
type State={config:StudioConfig;status:'poster'|'loading'|'ready'|'unavailable'|'lost';tab:'motion'|'size'|'room';dimensions:boolean;view:string;share:boolean;rotating:boolean;fullscreen:boolean;footprint:{width:number;depth:number}|null;hotspots:boolean;hotspot:string;roomWidth:string;roomDepth:string;fit:RoomFitResult|null;fitError:string};
let runtimePromise:Promise<any>|null=null;
const hotspotCopy:Record<string,{title:string;body:string}>={
 lift:{title:'Yükseklik kumandası',body:'Ana çalışma yüzeyinin yükselmesini temsil eder. Gerçek motor, taşıma kapasitesi ve elektrik güvenliği üretim öncesi ayrıca doğrulanır.'},
 drawers:{title:'Üst çekmece grubu',body:'Sık kullanılan küçük ekipmanlar için üç bölümlü depolama fikri. İç düzen ve ray sistemi gerçek projede kullanımınıza göre netleştirilir.'},
 return:{title:'Döner yan çalışma yüzeyi',body:'Tek masa ile farklı yerleşimlere geçebilmek için tasarlanan ikincil yüzey. Dönüş çapı ve mekanik durdurucular prototip aşamasında doğrulanmalıdır.'},
 storage:{title:'Sabit depolama gövdesi',body:'Dosya, aksesuar ve günlük ekipman için sabit alt depolama fikri. Kapak, çekmece ve iç bölmeler ihtiyaca göre yeniden çalışılabilir.'}
};
function loadRuntime():Promise<any>{const w=window as any;if(w.ElifDesk3D)return Promise.resolve(w.ElifDesk3D);if(w.__ELIF_LOAD_3D__)return w.__ELIF_LOAD_3D__();if(runtimePromise)return runtimePromise;runtimePromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.type='module';script.src=(w.__ELIF_BASE__||'/elif-tasarim')+'/three/desk-scene.mjs?v=v13-final-atelier';script.onload=()=>w.ElifDesk3D?resolve(w.ElifDesk3D):reject(Error('3D initialization failed'));script.onerror=()=>{runtimePromise=null;script.remove();reject(Error('3D runtime unavailable'))};document.head.appendChild(script)});return runtimePromise;}
export class DeskExperience extends Component<Props,State>{
 private host:HTMLDivElement|null=null;private root:HTMLElement|null=null;private engine:any=null;private alive=true;
 constructor(p:Props){super(p);this.state={config:p.query&&new URLSearchParams(p.query).has('en')?projectStore.openStudio(p.query,studioFromQuery(p.query)):projectStore.getStudio(),status:'poster',tab:'motion',dimensions:false,view:'perspective',share:false,rotating:false,fullscreen:false,footprint:null,hotspots:false,hotspot:'',roomWidth:'',roomDepth:'',fit:null,fitError:''}}
 componentDidMount(){document.addEventListener('fullscreenchange',this.fullscreenChanged);if(!this.props.compact)this.start();}
 componentWillUnmount(){document.removeEventListener('fullscreenchange',this.fullscreenChanged);this.alive=false;this.engine?.dispose();this.engine=null;}
 start=async()=>{if(this.state.status==='loading')return;if(this.engine){if(!['lost','unavailable'].includes(this.state.status))return;this.engine.dispose();this.engine=null;}this.setState({status:'loading'});try{const runtime=await loadRuntime();if(!this.alive||!this.host)return;this.engine=runtime.createDeskScene(this.host,this.state.config,{status:(status:any)=>{if(this.alive)this.setState({status})},motion:(rotating:boolean)=>{if(this.alive)this.setState({rotating})},camera:(view:string)=>{if(this.alive)this.setState({view})},hotspot:(hotspot:string)=>{if(this.alive)this.setState({hotspot})}});this.engine.light(this.state.config.lighting);this.engine.dimensions(this.state.dimensions);this.engine.hotspots?.(this.state.hotspots);this.setState({status:'ready'});}catch{if(this.alive)this.setState({status:'unavailable'})}};
 change=(patch:Partial<StudioConfig>)=>{const config=normalizeStudio({...this.state.config,...patch}),roomChanged=config.room!==this.state.config.room;projectStore.setStudio(config);this.setState({config,footprint:null,fit:null,fitError:'',...(roomChanged?{view:'perspective',rotating:false}:{})},()=>this.engine?.update(config));};
 setView=(view:string)=>{this.setState({view,rotating:false});this.engine?.rotate(false);this.engine?.setView(view)};
 handoff=()=>{const notice=projectStore.get().studioNotice;if(notice&&!window.confirm(notice+' Gösterilen 3D ölçülerini proje taslağınıza aktarmak istediğinize emin misiniz?'))return;projectStore.handoffStudio(this.state.config);this.props.navigate('/modelini-getir');};
 fullscreenChanged=()=>{const fullscreen=document.fullscreenElement===this.root;this.setState({fullscreen},()=>{if(!fullscreen)this.root?.querySelector<HTMLButtonElement>('.v11-fullscreen-toggle')?.focus({preventScroll:true})})};
 fullscreen=async()=>{const el=this.root;if(!el)return;try{if(document.fullscreenElement===el)await document.exitFullscreen();else if(el.requestFullscreen)await el.requestFullscreen();else this.props.notify('Tam ekran bu tarayıcıda desteklenmiyor.')}catch{this.props.notify('Tam ekran açılamadı. Stüdyo normal görünümde kullanılabilir.')}};
 measureFootprint=()=>{if(!this.engine)return;this.setView('top');const footprint=this.engine.footprint();this.setState({footprint,fit:null,fitError:''})};
 toggleHotspots=()=>this.setState(s=>({hotspots:!s.hotspots,hotspot:s.hotspots?'':s.hotspot}),()=>this.engine?.hotspots?.(this.state.hotspots));
 evaluateFit=()=>{if(!this.engine)return;const footprint=this.engine.footprint(),roomWidth=Number(this.state.roomWidth.replace(',','.')),roomDepth=Number(this.state.roomDepth.replace(',','.'));const fit=evaluateRoomFit(roomWidth,roomDepth,footprint);if(!fit){this.setState({fit:null,fitError:'Oda eni ve derinliği için pozitif bir santimetre değeri girin.'});return}this.setState({footprint,fit,fitError:''});this.setView('top')};
 snapshot=()=>{if(!this.engine)return;try{const url=this.engine.snapshot(1920,1280),a=document.createElement('a');a.href=url;a.download='Elif-Devir-01-Konsept-Model.png';a.click();this.props.notify('Görüntü hazırlandı. Konsept modeldir, teknik imalat çizimi değildir.')}catch{this.props.notify('Görüntü bu cihazda kaydedilemedi. Ölçü özetinizi indirebilirsiniz.')}};
 shareURL=()=>{const w=typeof window!=='undefined'?window as any:{};return (w.__ELIF_SITE_URL__||'https://onourimpram.github.io/elif-tasarim').replace(/\/$/,'')+'/tasarim-masasi/?'+studioQuery(this.state.config)};
 toggleRotate=()=>{this.engine?.rotate(!this.state.rotating)};
 tabKey=(event:any,id:string)=>{const tabs=['motion','size','room'];let n=tabs.indexOf(id);if(event.key==='ArrowRight')n=(n+1)%3;else if(event.key==='ArrowLeft')n=(n+2)%3;else if(event.key==='Home')n=0;else if(event.key==='End')n=2;else return;event.preventDefault();const tab=tabs[n] as State['tab'];this.setState({tab},()=>this.root?.querySelector<HTMLButtonElement>('[role="tab"][aria-selected="true"]')?.focus())};
 field=(key:'width'|'depth'|'height'|'angle',label:string,min:number,max:number,unit='cm')=>{const v=this.state.config[key];return <div className="v8-field" key={key}><div><label htmlFor={'v8-'+(this.props.compact?'home-':'full-')+key}>{label}</label><span><input type="number" inputMode="numeric" value={v} min={min} max={max} step="1" aria-label={label+', sayı girişi'} onChange={e=>{const raw=e.currentTarget.value;if(/^\d+$/.test(raw)&&+raw>=min&&+raw<=max)this.change({[key]:+raw});else e.currentTarget.value=String(v)}}/>{unit}</span></div><input id={'v8-'+(this.props.compact?'home-':'full-')+key} type="range" aria-label={label} min={min} max={max} value={v} step="1" onInput={e=>this.change({[key]:+e.currentTarget.value})}/><div className="v8-bounds"><span>{min} {unit}</span><span>{max} {unit}</span></div></div>};
 render(){const {config:c,status,tab,dimensions,view}=this.state,light=c.lighting,p=this.props,ready=status==='ready',prefix=p.compact?'home':'full';return <div ref={e=>this.root=e} className={'v8-experience '+(p.compact?'v8-compact':'v8-full')} data-studio={p.compact?'home':'full'} data-three-status={status} data-room={c.room} data-fullscreen={this.state.fullscreen?'true':'false'}>
 <div className="v8-story"><Eyebrow>{p.compact?'05 / YAŞAYAN TASARIM MASASI':'ELİF TASARIM / DEVİR 01'}</Eyebrow>{p.compact?<h2>Çalışma alanınız,<br/><em>sizinle değişsin.</em></h2>:<h1>Kendi çalışma<br/><em>alanınızı tasarlayın.</em></h1>}<p className="v8-lede">Yükselen bir çalışma yüzeyi, çekmeceler ve döner yan tabla. Masayı ölçünüze göre inceleyin. İki yandaki kitaplıklar, mekânı birlikte hayal etmek için.</p>
 {projectStore.get().studioNotice&&<p className="v11-studio-notice" role="status">{projectStore.get().studioNotice}</p>}
 <div className="v8-design-note"><span className="v8-series-number">01</span><div><strong>DEVİR</strong><span>YÜKSEKLİK AYARLI ÇALIŞMA MASASI</span></div><span className="v8-concept-label">Konsept model</span></div>
 <div className="v8-control-tabs" role="tablist" aria-label="Tasarım kontrol grubu">{[['motion','Masa'],['size','Ölçü'],['room','Mekân']].map(([id,name])=><button type="button" role="tab" key={id} id={'studio-'+prefix+'-tab-'+id} aria-controls={'studio-'+prefix+'-panel'} tabIndex={tab===id?0:-1} aria-selected={tab===id} onKeyDown={e=>this.tabKey(e,id)} onClick={()=>this.setState({tab:id as any})}>{name}</button>)}</div>
 <div className="v8-controls" id={'studio-'+prefix+'-panel'} aria-labelledby={'studio-'+prefix+'-tab-'+tab} role="tabpanel" aria-label={tab==='motion'?'Hareket kontrolleri':tab==='size'?'Ölçü kontrolleri':'Mekân kontrolleri'}>
 {tab==='motion'?<>{this.field('height','Çalışma yüksekliği',80,125)}{this.field('angle','Yan tabla açısı',0,360,'°')}<div className="v8-presets" aria-label="Masa yerleşimleri">{[['Toplu',0],['L düzen',90],['Açık',180]].map(([label,a])=><button type="button" key={label as string} aria-pressed={c.angle===a} onClick={()=>this.change({angle:a as number})}>{label}</button>)}</div><div className="v8-toggle-row"><button type="button" aria-pressed={c.drawers} onClick={()=>this.change({drawers:!c.drawers})}><Icon name="plus" size={16}/>{c.drawers?'Çekmeceleri kapat':'Çekmeceleri aç'}</button><button type="button" aria-pressed={c.door} onClick={()=>this.change({door:!c.door})}><Icon name="grid" size={16}/>{c.door?'Dolabı kapat':'Dolabı aç'}</button></div></>:tab==='size'?<>{this.field('width','Masa eni',120,220)}{this.field('depth','Masa derinliği',65,95)}<p className="v8-control-note">Bu aralıklar görsel keşif içindir. Gerçek ölçü ve mekanizma, üretim öncesi birlikte netleştirilir.</p></>:<div className="v9-room-controls"><span className="v9-control-label">MEKÂN KİTAPLIKLARI</span><div className="v9-shelf-options" role="group" aria-label="Raf düzeni">{[['both','Çift taraflı'],['left','Sol raf'],['right','Sağ raf'],['none','Rafsız']].map(([id,label])=><button key={id} type="button" aria-pressed={c.shelves===id} onClick={()=>this.change({shelves:id as StudioConfig['shelves'],room:'atelier'})}>{label}</button>)}</div><label className="v9-light-control">Raf aydınlatması <span>{c.shelfLight}%</span><input aria-label="Raf ışığı" type="range" min="0" max="100" value={c.shelfLight} onInput={e=>this.change({shelfLight:+e.currentTarget.value})}/></label><p className="v8-control-note">Kitaplıklar ve koltuk mekânı göstermek içindir. Masa ölçüsüne veya bir fiyat teklifine dahil değildir.</p></div>}
 </div>
 <div className="v8-materials"><span>MASA YÜZEYİ</span><div role="group" aria-label="Ahşap yüzey seçenekleri">{Object.entries(studioMaterials).map(([id,m])=><button type="button" key={id} aria-pressed={c.material===id} aria-label={m.name} onClick={()=>this.change({material:id as StudioConfig['material']})}><i className={'v8-swatch v8-'+id} style={{backgroundColor:m.color}}/><span>{m.name}</span></button>)}</div></div>
 <div className="v8-primary-action">{p.compact?<Link className="button" to={'/tasarim-masasi?'+studioQuery(c)} navigate={p.navigate}>Stüdyoda devam et <Icon/></Link>:<button type="button" className="button" onClick={this.handoff}>Bu tasarımı Yunus Usta ile konuş <Icon/></button>}<span>Ölçü, malzeme ve hareket alanını birlikte değerlendirelim.</span>{!p.compact&&<a className="v10-direct-question" href={whatsappUrl("Merhaba Yunus Usta, Devir 01 konsepti hakkında görüşmek istiyorum.\n"+studioSummary(c))} target="_blank" rel="noopener noreferrer">Form doldurmadan WhatsApp’ta sor <Icon name="diagonal" size={16}/></a>}</div>
 </div>
 <div className="v8-showroom"><div className="v8-viewer-top"><div><span className="v8-live-dot"/><span>{ready?'CANLI 360° STÜDYO':'İNTERAKTİF TASARIM STÜDYOSU'}</span></div><span>DEVİR 01 · KONSEPT MODEL</span></div>
 <div className="v8-canvas-wrap"><div className="v9-environment" role="group" aria-label="Sahne görünümü"><button type="button" aria-pressed={c.room==='atelier'} onClick={()=>this.change({room:'atelier'})}>Mekân içinde</button><button type="button" aria-pressed={c.room==='product'} onClick={()=>this.change({room:'product'})}>Yalnız masa</button></div><div className="v8-canvas-host" ref={e=>this.host=e}/>{!ready&&<div className="v8-poster"><img src={image(c.room==='atelier'?'atelier-poster-v9.webp':'devir-poster.webp')} alt="Çekmeceli ana tabla, dolap ve döner yan yüzeyli Devir 01 konsept çalışma masası"/><div className="v8-poster-action">{status==='poster'?<button type="button" aria-label="3D deneyimi başlat" onClick={this.start}><span className="v8-cube" aria-hidden="true">◇</span>3D deneyimi başlat <Icon size={18}/></button>:status==='loading'?<p role="status">Malzemeler ve ışık hazırlanıyor.</p>:<><p role="status">{status==='lost'?'3D görüntü bağlantısı kesildi.':'Bu cihazda 3D görünüm açılamadı.'}</p><small>Ölçü ve malzeme seçiminiz korunur. Tasarım özetiyle devam edebilirsiniz.</small><button type="button" onClick={this.start}>3D görünümü yeniden dene <Icon/></button></>}</div></div>}
 <div className="v8-view-tabs" role="group" aria-label="Kamera açıları">{[['perspective','Genel'],['front','Çekmece tarafı'],['back','Arka'],['left','Soldan'],['right','Sağdan'],['top','Üstten']].map(([id,name])=><button type="button" key={id} disabled={!ready} aria-pressed={view===id} onClick={()=>this.setView(id)}>{name}</button>)}</div>
 <div className="v8-view-tools"><button type="button" disabled={!ready} className="v11-fullscreen-toggle" aria-label={this.state.fullscreen?'Tam ekrandan çık':'Stüdyoyu kontrollerle tam ekran aç'} aria-pressed={this.state.fullscreen} onClick={this.fullscreen}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/></svg></button><button type="button" disabled={!ready} aria-label="Yakınlaştır" onClick={()=>this.engine?.zoom(.88)}><Icon name="plus"/></button><button type="button" disabled={!ready} aria-label="Uzaklaştır" onClick={()=>this.engine?.zoom(1.12)}><Icon name="minus"/></button><button type="button" disabled={!ready} aria-label="Görünümü sıfırla" onClick={()=>this.setView('perspective')}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M3 10a9 9 0 1 1 1 8M3 4v6h6"/></svg></button><button type="button" disabled={!ready} aria-label="Ölçü çizgilerini göster" aria-pressed={dimensions} onClick={()=>this.setState({dimensions:!dimensions},()=>this.engine?.dimensions(this.state.dimensions))}><Icon name="ruler"/></button><button type="button" disabled={!ready} aria-label={this.state.hotspots?'Detay noktalarını gizle':'Detay noktalarını göster'} aria-pressed={this.state.hotspots} onClick={this.toggleHotspots}><Icon name="info"/></button></div>
 {this.state.hotspot&&hotspotCopy[this.state.hotspot]&&<aside className="v13-hotspot-card" role="status"><button type="button" aria-label="Detay bilgisini kapat" onClick={()=>this.setState({hotspot:''})}>×</button><span>DETAY NOKTASI</span><strong>{hotspotCopy[this.state.hotspot].title}</strong><p>{hotspotCopy[this.state.hotspot].body}</p></aside>}<span className="v8-canvas-hint">{ready?'Sürükleyerek 360° inceleyin. İki parmakla yakınlaştırın.':'Gerçek zamanlı üç boyutlu model'}</span><span className="v8-scene-label">Konsept model</span>
 </div>
 <div className="v11-quick-controls" aria-label="Görüntünün yanında hızlı ayarlar"><label htmlFor={'quick-height-'+prefix}>Yükseklik <strong>{c.height} cm</strong></label><input id={'quick-height-'+prefix} aria-label="Hızlı çalışma yüksekliği" type="range" min="80" max="125" step="1" value={c.height} onInput={e=>this.change({height:+e.currentTarget.value})}/><div role="group" aria-label="Hızlı yüzey seçimi">{Object.entries(studioMaterials).map(([id,m])=><button type="button" key={id} aria-label={'Hızlı '+m.name} aria-pressed={c.material===id} onClick={()=>this.change({material:id as StudioConfig['material']})}><i style={{backgroundColor:m.color}}/>{m.name}</button>)}</div></div>
 <div className="v8-viewer-bottom"><div><span>SEÇTİĞİNİZ ÖLÇÜ</span><strong>{c.width} <i>×</i> {c.depth} <i>×</i> {c.height}<small> cm</small></strong></div><div className="v8-light-options" role="group" aria-label="Stüdyo ışığı"><button type="button" aria-pressed={light==='day'} onClick={()=>this.change({lighting:'day'})}>Gün ışığı</button><button type="button" aria-pressed={light==='evening'} onClick={()=>this.change({lighting:'evening'})}>Akşam</button></div><button type="button" disabled={!ready} className="v8-export" onClick={this.snapshot}><Icon name="download" size={19}/><span>Görünümü kaydet</span></button></div>
 <div className="v8-experience-foot"><span><Icon name="ruler" size={16}/>Ölçüye göre değişen geometri</span><span><Icon name="grid" size={16}/>Çift taraflı raf deneyimi</span><span>Three.js / WebGL</span></div>
 {!p.compact&&<><div className="v8-export-row"><button className="text-link" type="button" onClick={()=>downloadText('Elif-Devir-01-Tasarim.txt',studioSummary(c))}>Ölçü özetini indir <Icon name="download" size={17}/></button><button className="text-link" type="button" aria-expanded={this.state.share} onClick={()=>this.setState({share:!this.state.share})}>Tasarım bağlantısı <Icon name="diagonal" size={17}/></button><button type="button" className="text-link" disabled={!ready} aria-pressed={this.state.rotating} onClick={this.toggleRotate}>{this.state.rotating?'Dönüşü durdur':'360° otomatik döndür'} <Icon name="clock" size={17}/></button></div>{this.state.share&&<label className="v8-share-field">Yalnız model seçeneklerinizi içeren bağlantı<input aria-label="Paylaşılabilir 3D tasarım bağlantısı" readOnly value={this.shareURL()} onFocus={e=>e.currentTarget.select()}/><small>Kişisel not veya iletişim bilgisi içermez.</small></label>}</>}
 <div className="v11-footprint"><button className="text-link" type="button" disabled={!ready} onClick={this.measureFootprint}>Üstten yerleşim alanını gör <Icon name="ruler" size={17}/></button>{this.state.footprint&&<p role="status" className="v11-footprint-result"><strong>{this.state.footprint.width} × {this.state.footprint.depth} cm</strong> Ekrandaki masa ve hareketli parçaların toplam görsel sınırı.</p>}<small>Oda, sandalye ve kitaplıklar dahil değildir. Hareket güvenliği veya imalat ölçüsü değil, seçili konumun yaklaşık yerleşim görünümüdür.</small>{!p.compact&&<div className="v13-fit-planner"><div><span className="eyebrow">ODANIZA GÖRE DÜŞÜNÜN</span><h3>Bu düzen alana nasıl oturuyor?</h3><p>Odanızın kullanılabilir enini ve derinliğini girin. Hesap yalnız seçili masa geometrisinin ortalanmış görsel sınırını karşılaştırır.</p></div><div className="v13-fit-fields"><label>Oda eni <span><input aria-label="Oda eni" inputMode="decimal" value={this.state.roomWidth} onInput={e=>this.setState({roomWidth:e.currentTarget.value,fit:null,fitError:''})}/> cm</span></label><label>Oda derinliği <span><input aria-label="Oda derinliği" inputMode="decimal" value={this.state.roomDepth} onInput={e=>this.setState({roomDepth:e.currentTarget.value,fit:null,fitError:''})}/> cm</span></label><button type="button" className="button button-outline" disabled={!ready} onClick={this.evaluateFit}>Yerleşimi karşılaştır</button></div>{this.state.fit&&<div className={'v13-fit-result '+(this.state.fit.fits?'fits':'does-not-fit')} role="status"><strong>{this.state.fit.fits?'Bu görsel sınır oda içine sığıyor.':'Bu seçili konumda masa sınırı odayı aşıyor.'}</strong><span>{this.state.fit.fits?'Yanlarda yaklaşık '+this.state.fit.widthClearance+' cm, önde ve arkada yaklaşık '+this.state.fit.depthClearance+' cm pay.':'Oda eni için '+Math.max(0,this.state.fit.footprintWidth-this.state.fit.roomWidth)+' cm, derinlik için '+Math.max(0,this.state.fit.footprintDepth-this.state.fit.roomDepth)+' cm ek alan gerekir.'}</span></div>}{this.state.fitError&&<p className="model-error" role="alert">{this.state.fitError}</p>}<small>Bu sonuç sandalye dolaşımı, kapı açılımı, süpürgelik, montaj toleransı veya güvenli mekanik hareket payını hesaplamaz. Yerleşim görüşmesine hazırlık içindir.</small></div>}</div>
 <p className="v12-orbit-note">Çekmeceler sandalye tarafına açılır. Arka açıya geçerken görüşü kapatan oda öğeleri geçici gizlenir, raf seçiminiz değişmez. Klavye oklarıyla dönebilir, + ve − ile yakınlaştırabilir, 0 ile ilk görünüme dönebilirsiniz. Telefonda sayfayı sahnenin dışından kaydırın.</p><p className="v8-engineering-note">Konsept modeldir. Raflar ve aksesuarlar masa ölçüsüne veya teklifine otomatik dahil değildir. Nihai mekanizma, yük kapasitesi, hareket açıklığı ve üretim ölçüleri atölye onayı gerektirir. Bu sahne teknik imalat çizimi veya güvenlik testi değildir.</p>{!p.compact&&<section className="v13-devir-guide" aria-labelledby="devir-guide-title"><span className="eyebrow">DEVİR 01 / KARAR REHBERİ</span><h2 id="devir-guide-title">Güzel görünmesinden önce,<br/><em>nasıl kullanacağınızı düşünün.</em></h2><div className="v13-guide-grid"><article><span>01</span><h3>Oturun, yükseltin, devam edin.</h3><p>Konseptin ana fikri, aynı yüzeyde oturarak ve ayakta çalışma arasında geçiş. Gerçek motor seçimi ve ergonomik yükseklik aralığı üretim öncesi doğrulanır.</p></article><article><span>02</span><h3>Yan yüzey, farklı düzenler.</h3><p>Döner tabla, tek bir masayı düz, L veya daha açık çalışma düzenlerine yaklaştırır. Mekanik sınırlar ve odadaki dönüş alanı prototiple teyit edilmelidir.</p></article><article><span>03</span><h3>Depolama işin içinde.</h3><p>Üst çekmeceler ve sabit dolap günlük ekipmanı masanın üzerinde bırakmadan yakınınızda tutmak için düşünülmüştür. İç düzen tamamen yeniden planlanabilir.</p></article></div><div className="v13-guide-check"><h3>Teklif görüşmesinde birlikte netleştirelim.</h3><ul><li>Gerçek oda ölçüsü ve dolaşım alanı</li><li>Motor, kontrol ünitesi ve taşıma gereksinimi</li><li>Kablo yönetimi ve priz konumu</li><li>Çekmece, dolap ve yan tabla kullanım senaryosu</li><li>Gerçek ahşap, kaplama, boya ve yüzey numunesi</li></ul></div></section>}
 </div></div>}
}
