import {createElement,Component} from 'react';
import {Icon} from './ui';
import {encodeSelections,decodeSelections,combineSelections,MAX_SELECTION_FILE_BYTES} from '../lib/selection-backup';
import {downloadText} from '../lib/domain';
type Props={ids:string[];replace:(ids:string[])=>void};
export class InspirationTransfer extends Component<Props,{pending:string[]|null;status:string;busy:boolean}>{
 state:{pending:string[]|null;status:string;busy:boolean}={pending:null,status:'',busy:false};private alive=true;
 componentWillUnmount(){this.alive=false}
 read=async(file:File|undefined)=>{if(!file)return;this.setState({busy:true,pending:null,status:''});try{if(file.size>MAX_SELECTION_FILE_BYTES)throw Error('Dosya en fazla 64 KB olabilir.');const ids=decodeSelections(await file.text());if(this.alive)this.setState({pending:ids,status:ids.length+' model bulundu. Mevcut listeniz henüz değiştirilmedi.'})}catch(e){if(this.alive)this.setState({status:e instanceof Error?e.message:'Dosya açılamadı. Mevcut seçimleriniz korunuyor.'})}finally{if(this.alive)this.setState({busy:false})}};
 apply=(merge:boolean)=>{if(!this.state.pending)return;try{const ids=merge?combineSelections(this.props.ids,this.state.pending):this.state.pending;if(!merge&&!window.confirm('Mevcut ilham seçkiniz bu dosyadaki '+ids.length+' modelle değiştirilsin mi?'))return;this.props.replace(ids);this.setState({pending:null,status:'İlham dosyanız güncellendi. Otomatik olarak atölyeye gönderilmedi.'})}catch(e){this.setState({status:e instanceof Error?e.message:'Seçkiler birleştirilemedi.'})}};
 render(){return <section className="v22-inspiration-transfer" aria-labelledby="v22-transfer-title"><h2 id="v22-transfer-title">İlhamınız yanınızda kalsın.</h2><p>Seçtiğiniz modelleri dosya olarak saklayın. Başka bir cihazda aynı seçkiyi açabilirsiniz. Yalnız herkese açık model kimlikleri kaydedilir, kişisel not veya fotoğraf eklenmez.</p><div className="action-row"><button type="button" className="button button-outline" disabled={!this.props.ids.length} onClick={()=>downloadText('Elif_Ilham_Dosyasi.json',encodeSelections(this.props.ids))}>İlham dosyamı indir <Icon name="download" size={17}/></button><label className="v22-file-label">İlham dosyamı aç<input type="file" accept="application/json,.json" aria-label="Elif ilham dosyasını aç" disabled={this.state.busy} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';this.read(f)}}/></label></div>{this.state.pending&&<div className="v22-import-choice"><p>{this.state.pending.length} model hazır. Nasıl devam edelim?</p><div className="action-row"><button type="button" className="button" onClick={()=>this.apply(true)}>Mevcut seçimlerimle birleştir</button><button type="button" className="button button-outline" onClick={()=>this.apply(false)}>Mevcut seçkiyi değiştir</button><button type="button" className="text-link" onClick={()=>this.setState({pending:null,status:'İçe aktarma iptal edildi. Seçimleriniz değişmedi.'})}>Vazgeç</button></div></div>}{this.state.status&&<p role="status" className="v22-transfer-status">{this.state.status}</p>}</section>}
}
