import {createElement,Fragment,Component} from 'react';
import {instagramModels,instagramProfile,type InstagramModel} from '../lib/instagram';
import {categoryName,workCategories,modelHref} from '../lib/portfolio';
import {targetElementId} from '../lib/selections';
import {VImage,SourceTag} from './PortfolioUI';
import {Icon,Eyebrow,TextLink,ButtonLink,Dialog,type PageProps} from './ui';

export class InstagramSelection extends Component<PageProps&{category?:string},{category:string;preview:string;photo:number}>{
 state={category:'all',preview:'',photo:0};
 save=(m:InstagramModel)=>{const a=this.props,id='ig:'+m.id,saved=a.favorites.includes(id);return <button type="button" className="v7-save-text" aria-label={(saved?'İlham dosyanızda. Kaydı kaldır. ':'İlham dosyama ekle. ')+m.title} aria-pressed={saved} onClick={()=>a.favorite(id)}><Icon name="heart" size={18}/>{saved?'İlham dosyanızda':'İlham dosyama ekle'}</button>};
 inquiry=(m:InstagramModel)=>modelHref(m.photos[0].url,m.category,'','ig:'+m.id);
 render(){const a=this.props,s=this.state,category=a.category||s.category,list=instagramModels.filter(m=>category==='all'||m.category===category),preview=instagramModels.find(m=>m.id===s.preview),photo=preview?.photos[s.photo];if(!list.length&&a.category)return null;return <>
  <section className="instagram-section" id="instagram-seckisi"><div className="wrap"><div className="v6-heading"><div><Eyebrow>YUNUS USTA’NIN HESABINDAN</Eyebrow><h2>Instagram’dan<br/><em>model seçkisi.</em></h2></div><div><p>Bir dolabın iç düzeni, kapı çevresinde açılan yer, bir sehpanın formu. Ustanın hesabında paylaşılan modeller arasından, kendi alanınız için konuşabileceğimiz ayrıntılar.</p><a className="text-link" href={instagramProfile} target="_blank" rel="noopener noreferrer">Ustanın Instagram hesabı <Icon name="diagonal" size={17}/></a></div></div>
  {!a.category&&<div className="filter-chips pin-filters" role="group" aria-label="Instagram kategorisi">{[{id:'all',name:'Tüm modeller'},...workCategories.filter(c=>instagramModels.some(m=>m.category===c.id))].map(c=><button key={c.id} aria-pressed={c.id===s.category} onClick={()=>this.setState({category:c.id})}>{c.name}</button>)}</div>}
  <p className="pin-count" role="status" aria-live="polite">{list.length} model. Fotoğrafa dokunup ayrıntıları inceleyin.</p><div className="instagram-grid">{list.map(m=><article className="instagram-card" key={m.id} id={targetElementId('ig:'+m.id)} tabIndex={-1} data-instagram={m.id}><button type="button" className="instagram-photo" aria-label={m.title+' görselini büyüt'} aria-haspopup="dialog" onClick={()=>this.setState({preview:m.id,photo:0})}><VImage asset={m.photos[0].asset} alt={m.title+'. Yunus Usta’nın Instagram model seçkisinden.'} sizes="(max-width: 600px) 90vw, (max-width: 1000px) 44vw, 29vw"/><span className="pin-zoom"><Icon name="plus" size={16}/> {m.photos.length>1?'Açık ve kapalı görünüm':'İncele'}</span></button><div className="instagram-copy"><span className="eyebrow">INSTAGRAM SEÇKİSİ / {categoryName(m.category)}</span><h3>{m.title}</h3><p>{m.description}</p>{this.save(m)}<div className="pin-card-actions"><TextLink to={this.inquiry(m)} navigate={a.navigate}>Bu modelle başlayalım</TextLink><a className="text-link" href={m.photos[0].url} target="_blank" rel="noopener noreferrer">Paylaşımı aç <Icon name="diagonal" size={17}/></a></div></div></article>)}</div>
  <p className="pin-note">Bu bölüm, Yunus Usta’nın Instagram hesabındaki model paylaşımlarından seçilmiştir. Her kartın özgün paylaşım bağlantısı korunur. Malzeme, ölçü ve üretim kapsamı kendi projeniz için ayrıca netleştirilir.</p>
  </div></section>
  {preview&&photo&&<Dialog title={preview.title} onClose={()=>this.setState({preview:'',photo:0})}><div className="concept-preview instagram-preview"><div className="concept-preview-media"><VImage asset={photo.asset} alt={preview.title+'. '+photo.caption} full eager sizes="(max-width: 800px) 90vw, 55vw"/>{preview.photos.length>1&&<div className="instagram-photo-tabs" role="group" aria-label="Model görünümleri">{preview.photos.map((p,i)=><button key={p.asset} aria-pressed={s.photo===i} onClick={()=>this.setState({photo:i})}>{p.caption}</button>)}</div>}<p className="photo-credit" aria-live="polite">{photo.caption}</p></div><div className="concept-preview-copy"><SourceTag kind="reference" label="Instagram seçkisi"/><h3>{preview.title}</h3><p>{preview.description}</p><p className="instagram-question">{preview.question}</p><ButtonLink to={this.inquiry(preview)} navigate={p=>{this.setState({preview:''});a.navigate(p)}}>Bu modelle başlayalım</ButtonLink>{this.save(preview)}<p className="concept-preview-note">Ustanın hesabından seçilmiş bir model. Beğendiğiniz ayrıntıyı, alanınızın ölçüsü ve kullanım ihtiyacıyla birlikte değerlendirelim.</p><a className="text-link" href={photo.url} target="_blank" rel="noopener noreferrer">Bu fotoğrafın Instagram paylaşımı <Icon name="diagonal"/></a></div></div></Dialog>}
 </>}
}
