import {createElement,Fragment} from 'react';
import {ResilientImage} from './ResilientImage';
import {image,Link,Icon,type PageProps} from './ui';
import {imageManifest} from '../lib/image-manifest';
import {categoryName,workPhotoEvidence,type Work} from '../lib/portfolio';
export function VImage({asset,alt,className='',eager=false,sizes='(max-width: 680px) 100vw, 50vw',full=false,priority,onLoad}:{asset:string;alt:string;className?:string;eager?:boolean;sizes?:string;full?:boolean;priority?:'high'|'low'|'auto';onLoad?:()=>void}) {
 const m=(imageManifest as any)[asset];
 if(!m)return <ResilientImage src={image(asset)} alt={alt} className={className} loading={eager?'eager':'lazy'}/>;
 const max=m.variants[m.variants.length-1],fallback=full?max:m.variants[Math.min(1,m.variants.length-1)];
 return <ResilientImage src={image(fallback.file)} fallbackSrc={image(max.file)} srcSet={m.variants.map((v:any)=>image(v.file)+' '+v.width+'w').join(', ')} sizes={sizes} width={m.width} height={m.height} alt={alt} className={className} loading={eager?'eager':'lazy'} decoding={priority==='low'?'async':eager?'sync':'async'} fetchPriority={priority||(eager?'high':'auto')} onLoad={onLoad}/>;
}
export function SourceTag({kind='work'}:{kind?:'work'|'process'|'concept'|'reference'}){return <span className={'source-tag source-'+kind}>{({work:'Atölye arşivi',process:'Uygulama aşaması',concept:'Konsept model',reference:'Pinterest ilhamı'})[kind]}</span>}
export function WorkCard({work:w,actions:a,featured=false,index=0}:{work:Work;actions:PageProps;featured?:boolean;index?:number}){return <article className={'work-card'+(featured?' featured-work':'')} data-work={w.id}>
 <Link to={'/proje/'+w.id} navigate={a.navigate} className="work-photo"><VImage asset={w.images[0]} alt={w.subtitle+', atölyeden paylaşılan fotoğraf'} sizes="(max-width: 680px) 90vw, (max-width: 1024px) 45vw, 30vw"/><SourceTag kind={workPhotoEvidence(w).kind}/><span className="work-open"><Icon name="diagonal" size={22}/></span></Link>
 <div className="work-caption"><span className="work-index">{String(index+1).padStart(2,'0')}</span><div><span className="work-category">{categoryName(w.category)}</span><h3><Link to={'/proje/'+w.id} navigate={a.navigate}>{featured?w.subtitle:w.title}</Link></h3><p>{featured?w.title:w.subtitle}</p><p className="work-gallery-count">{w.images.length} fotoğraf<span aria-hidden="true"> · </span>{w.features[0]}</p></div></div>
 <button type="button" className="v7-save-text" aria-label={(a.favorites.includes('work:'+w.id)?'İlham dosyanızda. Kaydı kaldır. ':'İlham dosyama ekle. ')+w.subtitle} aria-pressed={a.favorites.includes('work:'+w.id)} onClick={()=>a.favorite('work:'+w.id)}><Icon name="heart" size={18}/>{a.favorites.includes('work:'+w.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button></article>}
export function ModelCallout({navigate,compact=false}:{navigate:(p:string)=>void;compact?:boolean}){return <section className={'model-callout'+(compact?' compact':'')}><div className="model-callout-image"><VImage asset="concept-model" alt="Malzeme numuneleri, çizimler ve görsel fikirlerden oluşan temsili tasarım masası"/><SourceTag kind="concept"/></div><div className="model-callout-copy"><span className="eyebrow">BİR FOTOĞRAFLA BAŞLAYABİLİRİZ</span><h2>Kendi modelinizi getirin.<br/><em>Üzerinde birlikte çalışalım.</em></h2><p>Pinterest’te kaydettiğiniz bir model, fotoğraf ya da çizim paylaşın. Raf düzenini mi, rengini mi, biçimini mi sevdiniz? Neyi korumak, neyi değiştirmek istediğinizi Yunus Usta’ya anlatın.</p><Link to="/modelini-getir" navigate={navigate} className="button">Fikrimi hazırlayayım <Icon/></Link><small>Yaklaşık ölçüyle başlayabilirsiniz. Son ölçü, malzeme ve teklif kapsamı birlikte netleşir.</small></div></section>}
