import {createElement,Fragment} from 'react';
import {Photo,Link,Eyebrow,Icon,type PageProps} from './ui';
import {studioPresets,presetHref} from '../lib/studio-presets';
export function StudioGuide({navigate}:Pick<PageProps,'navigate'>){return <div className="studio-guide">
 <section id="studio-baslangic" className="wrap studio-starts"><div className="studio-section-heading"><div><Eyebrow>3D STÜDYO / BAŞLANGIÇ MODELLERİ</Eyebrow><h2>Bir düzen seçin.<br/><em>Kendinize göre değiştirin.</em></h2></div><p>Üç farklı ölçü ve yüzey. Seçtiğiniz model, yukarıdaki aynı stüdyoda açılır. Sonra eni, yüksekliği ve yan yüzeyin açısını değiştirebilirsiniz.</p></div>
 <div className="studio-preset-grid">{studioPresets.map((p,i)=><Link key={p.id} to={presetHref(p)} navigate={navigate} className="studio-preset" data-preset={p.id}><div className="studio-preset-top"><span>0{i+1}</span><span>Konsept model</span></div><Photo name={p.image} alt={p.title+'. '+p.finish+'. '+p.width+' × '+p.depth+' × '+p.height+' cm başlangıç düzeni.'} ratio="3/2" caption={false} eager/><div className="studio-preset-copy"><h3>{p.title}</h3><p>{p.subtitle}</p><dl><div><dt>Görünüm</dt><dd>{p.finish}</dd></div><div><dt>En × derinlik × yükseklik</dt><dd>{p.width} × {p.depth} × {p.height} cm</dd></div></dl><span className="text-link">Bu modeli stüdyoda aç <Icon size={18}/></span></div></Link>)}</div><p className="studio-caption">Görseller stüdyodaki gerçek Three.js modelinden alınmıştır. Ölçüler değiştirilebilir görsel başlangıçlardır, onaylanmış üretim ölçüsü değildir.</p></section>
 <section id="studio-yaklasim" className="wrap studio-behavior"><div className="studio-section-heading"><div><Eyebrow>MASANIN HAREKETLERİ</Eyebrow><h2>Gündelik kullanım,<br/><em>ayrıntıyı belirler.</em></h2></div><p>Sahnedeki bilgi düğmesinden detay noktalarını açın. Yükseklik kumandası, çekmeceler, yan yüzey ve alt gövdeyi yerinde inceleyin.</p></div><div className="studio-explain-grid">{[['Yükselir.','Ana yüzey ile üst çekmeceler birlikte hareket eder. Oturarak ve ayakta çalışma fikrini aynı model üzerinde değerlendirin.'],['Döner.','Yan yüzeyin açısını değiştirerek toplu, L biçiminde veya açık bir yerleşim deneyin. Gerçek dönüş mesafesi ve durdurucular prototipte doğrulanır.'],['Saklar.','Üst çekmece grubu, alt çekmece ve kapaklı gövde ayrı depolama alanlarıdır. İç düzeni kullanacağınız eşyalara göre konuşabiliriz.']].map(([title,body],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section id="studio-detay" className="wrap studio-details"><div className="studio-detail-media"><Photo name="devir-detay-v23.webp" alt="Stüdyodaki konsept masanın açık çekmeceleri ve alt depolama bölümü" ratio="3/2" eager/><span className="studio-caption">Konsept modelin depolama ayrıntısı.</span></div><div className="studio-detail-copy"><Eyebrow>MALZEME VE İŞÇİLİK KARARLARI</Eyebrow><h2>Ekrandan sonra,<br/><em>numune ve ölçü.</em></h2><details open><summary>Yüzeyin gerçek karşılığı</summary><p>Meşe, ceviz ve koyu ahşap seçenekleri ekrandaki görünümü anlatır. Masif, kaplama, gövde malzemesi ve son kat uygulaması gerçek numune üzerinden ayrıca belirlenir. Ekrandaki renk, numune taahhüdü değildir.</p></details><details><summary>Çekmece, ray ve mekanizma</summary><p>Çekmecenin iç ölçüsü, ray sistemi, motor, taşıma kapasitesi ve elektrik güvenliği üretim tasarımının konusudur. Stüdyo bu başlıkları konuşmak için görsel bir araçtır.</p></details><details><summary>Kablo ve priz planı</summary><p>Kullanacağınız ekran, bilgisayar ve diğer ekipmanları belirtin. Kablo geçişi ve priz konumu gerçek projede çalışma alanınıza göre planlanır. Mevcut modelde onaylanmış bir kablo mekanizması gösterilmez.</p></details><Link to="/modelini-getir" navigate={navigate} className="text-link">Kendi ayrıntınızı da paylaşın <Icon/></Link></div></section>
 <section className="wrap studio-room-note"><Photo name="devir-atolye-v23.webp" alt="İki kitaplık ve masa ile oluşturulmuş üç boyutlu çalışma odası konsepti" ratio="3/2" eager/><div><Eyebrow>AYNI STÜDYODA MEKÂNI DA DÜŞÜNÜN</Eyebrow><h2>İki yanda raflar.<br/><em>Ortada sizin düzeniniz.</em></h2><p>Mekân sekmesinden kitaplıkları ve raf aydınlatmasını değiştirin. Üstten görünüm ve oda ölçüsü aracıyla yerleşimi değerlendirin.</p><p>Kitaplık, koltuk ve aksesuarlar ortamı anlatır. Masa teklifine otomatik olarak dahil değildir. Odamda gör ve model indirme seçenekleri sahnenin paylaşım araçlarında bulunur.</p><a href="#studio-deneyimi" className="text-link" onClick={e=>{e.preventDefault();document.getElementById('studio-deneyimi')?.scrollIntoView({behavior:'auto'});}}>3D deneyimine dön <Icon/></a></div></section>
 </div>}
