const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
class TestComponent{constructor(props){this.props=props;this.state={}}setState(change){this.state={...this.state,...(typeof change==='function'?change(this.state):change)}}}
function load(file){const cache={};function req(f){f=path.resolve(f);if(cache[f])return cache[f].exports;const m={exports:{}};cache[f]=m;const js=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,jsxFactory:'createElement',jsxFragmentFactory:'Fragment'}}).outputText;new Function('module','exports','require',js)(m,m.exports,id=>{if(id==='react')return {createElement:(type,props,...children)=>({type,props:{...props,children}}),Fragment:({children})=>children,Component:TestComponent};if(id.startsWith('.')){const base=path.resolve(path.dirname(f),id);return req(fs.existsSync(base+'.ts')?base+'.ts':base+'.tsx')}return require(id)});return m.exports}return req(file)}
function walk(node,fn){if(!node)return;if(Array.isArray(node))return node.forEach(x=>walk(x,fn));if(typeof node==='object'){fn(node);walk(node.props?.children,fn)}}
test('asset fallback preserves actual deployed subpath without registry',()=>{global.window={__ELIF_BASE__:'/elif-tasarim'};try{const ui=load('src/components/ui.tsx');assert.equal(ui.image('devir-standing.webp'),'/elif-tasarim/assets/devir-standing.webp')}finally{delete global.window}});
test('critical studio editorial media does not depend on a later lazy scroll',()=>{const {StudioGuide}=load('src/components/StudioGuide.tsx');const photos=[];walk(StudioGuide({navigate(){}}),n=>{if(typeof n.type==='function'&&n.type.name==='Photo')photos.push(n)});assert.ok(photos.length>=3);assert.ok(photos.every(n=>n.props.eager===true))});
test('each studio starting choice includes an actual model view',()=>{const {StudioGuide}=load('src/components/StudioGuide.tsx');let grid;walk(StudioGuide({navigate(){}}),n=>{if(n.props?.className==='studio-preset-grid')grid=n});const photos=[];walk(grid,n=>{if(typeof n.type==='function'&&n.type.name==='Photo')photos.push(n)});assert.equal(photos.length,3,'colour swatches alone are not product previews')});
test('static HTML includes recovery context independent of config JavaScript',()=>{const html=fs.readFileSync('dist/tasarim-masasi/index.html','utf8');assert.match(html,/<html[^>]*data-base="\/elif-tasarim"/);assert.match(html,/<html[^>]*data-site="https:\/\/onourimpram.github.io\/elif-tasarim"/)});
test('image failure has one bounded retry and an explicit useful state',()=>{const {ResilientImage}=load('src/components/ResilientImage.tsx');const c=new ResilientImage({src:'/elif-tasarim/assets/test.webp',alt:'Masa ayrıntısı'});c.onError();assert.equal(c.state.retried,true);assert.equal(c.state.failed,false);c.onError();assert.equal(c.state.failed,true);const node=c.render();assert.equal(node.type,'span');assert.match(JSON.stringify(node),/Görsel yüklenemedi/);c.componentDidUpdate({src:'/old.webp'});assert.equal(c.state.failed,false)});

test('release identity matches the current package and visible site',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));assert.equal(pkg.version,'0.28.0');assert.equal(pkg.scripts.build,'node tools/build-v25.cjs');assert.equal(pkg.scripts['verify:dist'],'node tools/verify-v25.cjs');const app=fs.readFileSync('src/App.tsx','utf8');assert.match(app,/V28 \/ TASARIM ÖNİZLEMESİ/);assert.match(app,/ELİF TASARIM · V28 \/ 2026/);});
