const test=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm');
const p='src/lib/desk-v8.ts';
function lib(){assert.ok(fs.existsSync(p),'V8 parametre modülü gerekli');const code=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const mod={exports:{}};vm.runInNewContext(code,{module:mod,exports:mod.exports,URLSearchParams,URL,console});return mod.exports;}
test('default model has storage, adjustable tabletop and independent wing',()=>{let x=lib();assert.equal(x.defaultStudio.height,80);assert.equal(x.defaultStudio.angle,90);assert.equal(x.defaultStudio.material,'ceviz')});
test('dimensions clamp nonfinite and impossible inputs',()=>{let x=lib(),s=x.normalizeStudio({width:999,depth:-8,height:NaN,angle:Infinity});assert.equal(s.width,220);assert.equal(s.depth,65);assert.equal(s.height,80);assert.equal(s.angle,90)});
test('full rotation and drawers roundtrip in public design URL',()=>{let x=lib(),s=x.normalizeStudio({width:203,depth:81,height:113,angle:270,drawers:true,door:true,material:'koyu'});assert.equal(JSON.stringify(x.studioFromQuery(x.studioQuery(s))),JSON.stringify(s))});
test('public URL never includes personal notes or district',()=>{let x=lib(),q=x.studioQuery({...x.defaultStudio,note:'private',district:'private'});assert.ok(!q.includes('private'));assert.ok(!q.includes('note'))});
test('scientific notation and malformed URL dimensions are rejected',()=>{let x=lib(),s=x.studioFromQuery('en=1e3&yukseklik=%3Cscript%3E&donus=-3&malzeme=invalid');assert.equal(s.width,180);assert.equal(s.height,80);assert.equal(s.angle,90);assert.equal(s.material,'ceviz')});
test('description preserves geometry and does not promise warranty or capacity',()=>{let x=lib(),s=x.studioSummary(x.defaultStudio);assert.ok(s.includes('180'));assert.ok(s.includes('90'));assert.ok(s.includes('Konsept model'));assert.ok(!s.includes('5 yıl'));assert.ok(!s.includes('200 lbs'))});
