/** Approved AI visual concepts, not completed jobs, stock or engineering specifications. */
export type BedConcept = {
 id: string; title: string; subtitle: string; category: 'baza-yatak';
 image: string; openImage: string; group: 'wood'|'upholstered';
 material: string; description: string; details: readonly string[];
};
export const beds: readonly BedConcept[] = [
 {id:'ceviz-yalin',title:'Ceviz Yalın',subtitle:'Ceviz Yalın ahşap ağırlıklı baza konsepti',category:'baza-yatak',image:'bed-ceviz-yalin-closed',openImage:'bed-ceviz-yalin-open',group:'wood',material:'Ceviz görünümü ve krem başlık',description:'Ahşap dokusunu geniş yan yüzeyler ve sade bir ön panel boyunca devam ettiren sakin bir çizgi.',details:['Ahşap görünümlü ön ve yan yüzeyler','Dikey kanallı, döşemeli başlık','İki bölümlü depolama fikri']},
 {id:'mese-cizgi',title:'Meşe Çizgi',subtitle:'Meşe Çizgi ahşap ağırlıklı baza konsepti',category:'baza-yatak',image:'bed-mese-cizgi-closed',openImage:'bed-mese-cizgi-open',group:'wood',material:'Açık meşe görünümü ve bej başlık',description:'Açık ahşap tonu, başlığın iki yanında ince çizgilerle tamamlanır. Daha aydınlık bir yatak odası için.',details:['Açık ahşap görünümlü gövde','Başlık kenarlarında çizgili ahşap detay','Yumuşatılmış köşe hatları']},
 {id:'ceviz-cerceve',title:'Ceviz Çerçeve',subtitle:'Ceviz Çerçeve ahşap detaylı baza konsepti',category:'baza-yatak',image:'bed-ceviz-cerceve-closed',openImage:'bed-ceviz-cerceve-open',group:'wood',material:'Ceviz çerçeve ve bej döşeme',description:'Başlıktan ayaklara uzanan ahşap çerçeve, döşemeli yüzeyleri tek bir tasarım diliyle birleştirir.',details:['Başlığı çevreleyen ahşap hat','Döşemeli ön ve yan paneller','İnce alt kayıt ve ayak birleşimi']},
 {id:'ceviz-kusak',title:'Ceviz Kuşak',subtitle:'Ceviz Kuşak ahşap kuşaklı baza konsepti',category:'baza-yatak',image:'bed-ceviz-kusak-closed',openImage:'bed-ceviz-kusak-open',group:'wood',material:'Geniş ceviz kuşak ve kum döşeme',description:'Alt gövdedeki belirgin ahşap kuşak, kumaşın yumuşak dokusuyla dengelenir. Yuvarlatılmış köşelerle tamamlanır.',details:['Geniş alt ahşap kuşak','Yuvarlatılmış ahşap köşe detayları','Kanallı ve çerçeveli başlık']},
 {id:'keten-ceviz',title:'Keten ve Ceviz',subtitle:'Keten ve Ceviz döşemeli baza konsepti',category:'baza-yatak',image:'bed-keten-ceviz-closed',openImage:'bed-keten-ceviz-open',group:'upholstered',material:'Krem döşeme ve ince ceviz detay',description:'Döşemenin öne çıktığı, ahşabın ise başlık kenarında ve alt çerçevede ince bir eşlikçi olduğu yorum.',details:['Açık renk, dokulu döşeme','İnce ahşap kenar ve ayaklar','Dikey başlık kanalları']},
 {id:'yumusak-bukle',title:'Yumuşak Bukle',subtitle:'Yumuşak Bukle yuvarlatılmış baza konsepti',category:'baza-yatak',image:'bed-yumusak-bukle-closed',openImage:'bed-yumusak-bukle-open',group:'upholstered',material:'Açık bukle görünümü',description:'Yuvarlatılmış kenarlar ve başlıktan gövdeye uzanan dokulu yüzey. Daha yumuşak bir oda atmosferi için.',details:['Bukle görünümlü döşeme','Alçak ayaklı gövde yorumu','Yumuşak köşeli başlık']},
 {id:'antrasit-hat',title:'Antrasit Hat',subtitle:'Antrasit Hat döşemeli baza konsepti',category:'baza-yatak',image:'bed-antrasit-hat-closed',openImage:'bed-antrasit-hat-open',group:'upholstered',material:'Antrasit döşeme ve ahşap ayak',description:'Koyu döşeme, yalın bir başlık ve ahşap ayaklarla birleşir. Odada daha belirgin bir odak isteyenlere.',details:['Antrasit dokulu yüzeyler','Yalın, dikey bölümlü başlık','Görünür ahşap ayaklar']},
 {id:'kum-dokusu',title:'Kum Dokusu',subtitle:'Kum Dokusu döşemeli baza konsepti',category:'baza-yatak',image:'bed-kum-dokusu-closed',openImage:'bed-kum-dokusu-open',group:'upholstered',material:'Kum rengi döşeme ve açık ahşap ayak',description:'Sıcak nötr tonlar ve düzenli başlık kanallarıyla, farklı oda renklerine eşlik eden sade bir seçenek.',details:['Kum rengi dokulu döşeme','Hafif yan kanatlı başlık','Açık ahşap görünümlü ayaklar']}
];
export const bedById = (id:string): BedConcept|undefined => beds.find(b=>b.id===id);
