import {studioSummary,studioQuery,type StudioConfig} from './desk-v8';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
/** Print uses only the selected public model. Private project notes are never read here. */
export function openDesignSheet(config:StudioConfig,preview:string|null):boolean{
 const win=window.open('','_blank');if(!win)return false;
 const site=((window as any).__ELIF_SITE_URL__||'https://onourimpram.github.io/elif-tasarim').replace(/\/$/,'');
 const link=site+'/tasarim-masasi/?'+studioQuery(config);
 const safeImage=preview&&/^data:image\/png;base64,[a-zA-Z0-9+/=]+$/.test(preview)?preview:null;
 win.document.write('<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="referrer" content="no-referrer"><title>Elif Tasarım. Devir 01 tasarım dosyası</title><style>body{font:15px/1.7 Georgia,serif;color:#352b22;background:#fffaf1;max-width:900px;margin:40px auto;padding:0 25px}header{border-bottom:1px solid #a38a69;display:flex;justify-content:space-between;align-items:center}h1{font-size:42px;margin:26px 0 8px}small{font:11px/1.6 Arial,sans-serif;letter-spacing:.08em}img{width:100%;max-height:430px;object-fit:contain;background:#eee6d8}pre{font:14px/1.8 Arial,sans-serif;white-space:pre-wrap;overflow-wrap:anywhere;padding:20px;background:#f1e9dc}a{color:#745434;overflow-wrap:anywhere}button{padding:14px 22px;border:0;background:#6c5036;color:white;cursor:pointer}footer{border-top:1px solid #c3b39a;margin-top:24px;padding:15px 0;font:12px/1.6 Arial,sans-serif}@media print{body{margin:0;max-width:none;background:white}.no-print{display:none}img{max-height:300px}h1{font-size:30px}pre{font-size:11px;padding:10px}footer{font-size:10px}header{break-after:avoid}}</style><header><strong>ELİF TASARIM</strong><small>DEVİR 01 · KONSEPT DOSYASI</small></header><h1>Sizin çalışma düzeniniz.</h1><p>Seçtiğiniz masa konfigürasyonunun görüşme özeti. Bir üretim onayı veya fiyat teklifi değildir.</p>'+(safeImage?'<img alt="Seçili üç boyutlu modelin görünümü" src="'+safeImage+'">':'')+'<pre>'+escape(studioSummary(config))+'</pre><p><a href="'+escape(link)+'">Aynı tasarımı 3D stüdyoda açın</a></p><footer>Yunus Usta. +90 530 879 71 69.<br>Kitaplıklar, sandalye, lamba ve diğer aksesuarlar masa kapsamına dahil değildir. Son ölçü, malzeme ve mekanizma ayrıca netleştirilir. Bu sayfa herhangi bir kişiye otomatik gönderilmedi.</footer><button class="no-print" id="print">Yazdır veya PDF olarak kaydet</button><p class="no-print">Tarayıcınızın yazdırma menüsünden PDF olarak kaydedebilirsiniz.</p></html>');
 win.document.close();win.document.getElementById('print')?.addEventListener('click',()=>win.print());win.opener=null;return true;
}
