export type StudioConfig={width:number;depth:number;height:number;angle:number;material:'ceviz'|'mese'|'koyu';drawers:boolean;door:boolean;shelves:'both'|'left'|'right'|'none';room:'atelier'|'product';shelfLight:number;lighting:'day'|'evening'};
export const defaultStudio:StudioConfig={width:180,depth:80,height:80,angle:90,material:'ceviz',drawers:false,door:false,shelves:'both',room:'atelier',shelfLight:65,lighting:'day'};
export const studioMaterials={ceviz:{name:'Ceviz tonu',color:'#765039'},mese:{name:'Açık meşe tonu',color:'#b89a6e'},koyu:{name:'Koyu ahşap',color:'#37312d'}};
const clamp=(v:unknown,min:number,max:number,fallback:number)=>typeof v==='number'&&Number.isFinite(v)?Math.min(max,Math.max(min,Math.round(v))):fallback;
export function normalizeStudio(v:Partial<StudioConfig>):StudioConfig{return {width:clamp(v.width,120,220,180),depth:clamp(v.depth,65,95,80),height:clamp(v.height,80,125,80),angle:clamp(v.angle,0,360,90),material:['ceviz','mese','koyu'].includes(v.material||'')?v.material!:'ceviz',drawers:v.drawers===true,door:v.door===true,shelves:['both','left','right','none'].includes(v.shelves||'')?v.shelves!:'both',room:v.room==='product'?'product':'atelier',shelfLight:clamp(v.shelfLight,0,100,65),lighting:v.lighting==='evening'?'evening':'day'}}
export function studioFromQuery(query:string):StudioConfig{const p=new URLSearchParams(query),num=(k:string,min:number,max:number,def:number)=>{const raw=p.get(k)||'';if(!/^\d+(?:[.,]\d+)?$/.test(raw))return def;const n=Number(raw.replace(',','.'));return n>=min&&n<=max?n:def};return normalizeStudio({width:num('en',120,220,180),depth:num('derinlik',65,95,80),height:num('yukseklik',80,125,80),angle:num('donus',0,360,90),material:p.get('malzeme') as StudioConfig['material'],drawers:p.get('cekmece')==='1',door:p.get('kapak')==='1',shelves:p.get('raf') as StudioConfig['shelves'],room:p.get('mekan') as StudioConfig['room'],shelfLight:num('rafisigi',0,100,65),lighting:p.get('isik')==='evening'?'evening':'day'})}
export function studioQuery(s:StudioConfig):string{const v=normalizeStudio(s);return new URLSearchParams({en:String(v.width),derinlik:String(v.depth),yukseklik:String(v.height),donus:String(v.angle),malzeme:v.material,cekmece:v.drawers?'1':'0',kapak:v.door?'1':'0',raf:v.shelves,mekan:v.room,rafisigi:String(v.shelfLight),isik:v.lighting}).toString()}
export function studioSummary(s:StudioConfig):string{const v=normalizeStudio(s);return ['ELİF TASARIM / DEVİR 01','Konsept model. Üretim çizimi veya onaylanmış ürün şartnamesi değildir.',`Ana tabla ölçü fikri, ${v.width} × ${v.depth} cm`,`Gösterilen çalışma yüksekliği, ${v.height} cm`,`Yan tabla açısı, ${v.angle}°`,`Yüzey fikri, ${studioMaterials[v.material].name}`,`Sunum ışığı, ${v.lighting==='evening'?'akşam':'gün ışığı'}. Görsel tercih, elektrik tesisatı taahhüdü değildir.`,`Mekân kitaplığı tercihi, ${{both:'çift taraflı',left:'sol',right:'sağ',none:'rafsız'}[v.shelves]}. Kitaplıklar masa ölçüsüne dahil değildir.`, 'Tablanın altında çekmeceler, sabit depolama ünitesi ve bağımsız dönen yan tabla.','Mekanizma, yük kapasitesi, güvenli hareket alanı ve son ölçüler Yunus Usta ile ayrıca doğrulanır.','Bu özet gönderilmiş sipariş değildir.'].join('\n')}

export function studioRequestMaterial(material:StudioConfig['material']):string{return {ceviz:'Ceviz görünümü, yapısını görüşelim',mese:'Meşe görünümü, yapısını görüşelim',koyu:'Ahşap / ahşap kaplama görünümü'}[material]}
