import {works,workCategories} from './portfolio';
import {business} from './project';
import {getSiteProfile} from './site-profile';
import { products, journal, ideas } from './data';
export const routePaths = ['/kolay-iletisim','/hizmet-ve-teklif','/devir-01','/projeler','/kategoriler','/ilham-modelleri','/modelini-getir','/hakkimizda','/atolye',...works.map(w=>'/proje/'+w.id),...workCategories.map(c=>'/kategoriler/'+c.id),'/', '/urunler', '/tasarim-masasi', '/atolyemiz', '/ozel-uretim', '/malzemeler', '/mekan-fikirleri', '/rehber', '/teklif-al', '/sikca-sorulan-sorular', '/iletisim', '/sepet', '/odeme', '/calisma-dosyam', '/gizlilik', '/atolye-demolari', ...products.map(p => '/urun/' + p.id), ...ideas.map(p => '/mekan-fikirleri/' + p.id), ...journal.map(p => '/rehber/' + p.id)];
export function pageTitle(path: string) { const p = path.split('?')[0]; if(p==='/kolay-iletisim')return 'Kolay İletişim | Elif Tasarım'; if(p==='/hizmet-ve-teklif')return 'Hizmet ve Teklif Rehberi | Elif Tasarım'; if(p==='/devir-01')return 'Devir 01. Çalışma Biçiminize Yer Açın | Elif Tasarım'; if(p==='/arama')return 'Arama | Elif Tasarım'; if(p==='/calisma-dosyam')return 'İlham Dosyanız | Elif Tasarım'; if(p==='/gizlilik')return 'Veri ve Dış Servisler | Elif Tasarım'; const w=works.find(w=>'/proje/'+w.id===p);if(w)return w.subtitle+' | Elif Tasarım';const c=workCategories.find(c=>'/kategoriler/'+c.id===p);if(c)return c.name+' | Elif Tasarım';const newTitles:Record<string,string>={'/projeler':'Bitirdiğimiz İşler','/kategoriler':'Kategoriler','/ilham-modelleri':'İlham Modelleri','/modelini-getir':'Kendi Modelinizi Getirin','/hakkimizda':'Aileden Gelen Ustalık','/atolye':'Atölye'};if(newTitles[p])return newTitles[p]+' | Elif Tasarım'; if(p==='/tasarim-masasi')return 'Devir 01. Üç Boyutlu Tasarım Stüdyosu | Elif Tasarım'; const product = products.find(x => '/urun/' + x.id === p); const article = journal.find(x => '/rehber/' + x.id === p); const idea = ideas.find(x => '/mekan-fikirleri/' + x.id === p); return product ? product.name + ' | Elif Tasarım' : article ? article.title + ' | Elif Tasarım' : idea ? idea.name + ' | Elif Tasarım' : ({ '/': 'Elif Tasarım | El Yapımı Mobilya Atölyesi', '/urunler': 'Koleksiyon | Elif Tasarım', '/teklif-al': 'Proje Fikrinizi Hazırlayın | Elif Tasarım', '/atolyemiz': 'Atölyemiz | Elif Tasarım', '/malzemeler': 'Malzeme Kütüphanesi | Elif Tasarım', '/sepet': 'Örnek Sepet | Elif Tasarım', '/odeme': 'Sipariş Hazırlığı | Elif Tasarım', '/iletisim': 'İletişim | Elif Tasarım', '/rehber': 'Atölye Notları | Elif Tasarım', '/ozel-uretim': 'Özel Üretim | Elif Tasarım', '/mekan-fikirleri': 'Mekân Fikirleri | Elif Tasarım', '/calisma-dosyam': 'Kaydedilenler | Elif Tasarım', '/gizlilik': 'Önizleme Gizliliği | Elif Tasarım', '/sikca-sorulan-sorular': 'Sorular | Elif Tasarım', '/atolye-demolari': 'Atölye İş Akışı Demosu | Elif Tasarım' } as Record<string, string>)[p] || 'Sayfa bulunamadı | Elif Tasarım'; }
export function pageDescription(path:string){const p=path.split('?')[0],w=works.find(w=>'/proje/'+w.id===p),c=workCategories.find(c=>'/kategoriler/'+c.id===p);if(w)return w.subtitle+'. '+w.description;if(c)return 'Elif Tasarım. '+c.name+'. '+c.detail;const desc:Record<string,string>={'/':'Zamana değer katan mobilyalar. İstanbul’daki aile atölyesinden gerçek çalışmalar, ilham modelleri ve Yunus Usta ile doğrudan iletişim.','/modelini-getir':'Pinterest bağlantısı, kendi fotoğrafınız veya fikrinizle başlayın. Ölçü ve kullanımınızı özetleyin, Yunus Usta ile WhatsApp’ta görüşün.','/teklif-al':'Kayıpsız ortak proje taslağı. Yaklaşık ölçü, malzeme ve kullanım ayrıntılarını birlikte hazırlayın.','/arama':'Elif Tasarım çalışma arşivi, ilham modelleri ve kategorilerinde arayın.','/iletisim':'Yunus Usta ile doğrudan iletişim. +90 530 879 71 69. Yeni atölye adresini ziyaret öncesinde teyit edin.','/gizlilik':'Elif Tasarım. Yerel proje taslağı, fotoğraf hazırlama, isteğe bağlı saklama, WhatsApp ve Pinterest hakkında açıklama.','/calisma-dosyam':'Gerçek çalışma, konsept model ve Pinterest modelini ortak ilham dosyanızda toplayın.'};const specific:Record<string,string>={
 '/kolay-iletisim':'Form kullanmadan Elif Tasarım ile iletişim kurun. Görünür e-posta, telefon, SMS ve ilk mesaj için başlangıç metni.',
 '/hizmet-ve-teklif':'Özel üretim mobilyada bütçe, malzeme, donanım, keşif, nakliye ve montaj kapsamını birlikte netleştirmek için görüşme rehberi.',
 '/devir-01':'Devir 01. Yükselen yüzeyi, döner yan tablası ve çekmeceli depolamasıyla özel çalışma masası konsepti. Üç başlangıç düzenini keşfedin ve 3D stüdyoda karşılaştırın.',
 '/projeler':'Atölyeden paylaşılan mutfak, kahve köşesi, TV ünitesi ve depolama çalışmalarını kaynak türü ve kullanım alanına göre inceleyin.',
 '/kategoriler':'Mutfak, TV ünitesi, vestiyer, gardırop, kahve köşesi, sehpa, pergola ve özel tasarım için üretim alanlarımızı keşfedin.',
 '/ilham-modelleri':'Konsept seçkileri ve kaynağı korunan Pinterest modelleri. Beğendiğiniz ayrıntıyı ilham dosyanıza ekleyin veya kendi fikrinize başlangıç yapın.',
 '/hakkimizda':'Yunus Usta’nın aileden öğrendiği marangozluk ve ihtiyaca göre çalışma yaklaşımı. Elif Tasarım’ın atölye hikâyesi.',
 '/atolye':'Üretim ve uygulama aşamalarından gerçek atölye arşivi. Montaj fotoğrafları bitmiş işlerden ayrı gösterilir.',
 '/tasarim-masasi':'Devir 01 konsept masayı gerçek 3D sahnede inceleyin. Yükseklik, ölçü, döner yan tabla ve çift taraflı raf seçeneklerini birlikte deneyin.',
 '/malzemeler':'Gövde, kapak, yüzey ve donanım kararlarını ayrı değerlendirin. Fotoğraftaki ahşap görünümü ile gerçek malzeme seçimi arasındaki farkı öğrenin.',
 '/ozel-uretim':'İlk fikirden ölçü ve kapsam görüşmesine, taslak değerlendirmesinden üretim onayına özel mobilya sürecinin adımları.',
 '/rehber':'Ölçü, malzeme ve bakım hakkında atölye notları. İlk mobilya görüşmenize daha doğru sorularla hazırlanın.',
 '/rehber/bakim':'Mobilya bakımında yüzey türünü tanıyın. Temizlik ve bakım ürününü seçmeden önce üretici yönlendirmesi ve donanım bilgisini teyit edin.',
 '/rehber/malzeme-secimi':'Masif, kaplama, gövde ve yüzey aynı karar değildir. Kullanım alanınıza uygun malzeme görüşmesi için başlangıç rehberi.',
 '/rehber/olcu-alma':'Mekânınıza özel mobilya için yaklaşık ölçü hazırlığı. En, derinlik, yükseklik ve yerleşim açıklıklarını görüşmeye taşıyın.',
 '/sikca-sorulan-sorular':'Ölçüye özel mobilya, Pinterest fikirleri, konsept modeller ve atölye görüşmesi hakkında sık sorulan sorular.'};return desc[p]||specific[p]||('Elif Tasarım. '+pageTitle(p).split(' | ')[0]+'. Çalışmaları ve görüşme seçeneklerini keşfedin.')}
export const v7Routes=[...new Set([...routePaths.filter(p=>!['/urunler','/sepet','/odeme','/atolye-demolari','/atolyemiz','/mekan-fikirleri'].includes(p)&&!p.startsWith('/urun/')&&!p.startsWith('/mekan-fikirleri/')),'/arama'])];

export function pageShareImage(path:string):string{const p=path.split('?')[0];if(p==='/hizmet-ve-teklif')return 'r13-full.webp';const article=journal.find(j=>'/rehber/'+j.id===p);if(article)return article.image==='joinery.webp'?'joinery-v8.webp':article.image;if(['/iletisim','/kolay-iletisim','/hakkimizda','/atolye'].includes(p))return 'work-joinery-full.webp';if(p==='/malzemeler')return 'joinery-v8.webp';if(p==='/sikca-sorulan-sorular')return 'concept-model-full.webp';if(p==='/devir-01')return 'devir-standing.webp';if(p==='/tasarim-masasi')return 'atelier-poster-v9.webp';const work=works.find(w=>'/proje/'+w.id===p);if(work)return work.images[0]+'-full.webp';const cat=workCategories.find(c=>'/kategoriler/'+c.id===p);if(cat){const representative=works.find(w=>w.category===cat.id&&w.status==='work');return (representative?representative.images[0]:cat.image)+'-full.webp'}if(['/modelini-getir','/teklif-al','/ilham-modelleri'].includes(p))return 'concept-model-full.webp';return 'r13-full.webp'}
export function indexableRoute(path:string){return !['/arama','/modelini-getir','/teklif-al','/calisma-dosyam','/404'].includes(path.split('?')[0]);}
export function pageSchema(path:string,site:string){
 const route=path.split('?')[0],base=site.replace(/\/$/,''),profile=getSiteProfile(),url=base+(route==='/'?'/':route+'/');
 const publisher:any={'@type':profile.address?'LocalBusiness':'Organization','@id':base+'/#atolye',name:business.name,url:base+'/',telephone:business.telephone,logo:base+'/assets/elif-amblem.png',areaServed:{'@type':'City',name:business.city},contactPoint:{'@type':'ContactPoint',telephone:business.telephone,contactType:'Proje görüşmesi',availableLanguage:'tr'}};
 if(profile.email)publisher.email=profile.email;
 if(profile.address)publisher.address={'@type':'PostalAddress',...profile.address};
 if(profile.social.length)publisher.sameAs=profile.social;
 const crumbs:{name:string;url:string}[]=[{name:'Anasayfa',url:base+'/'}];
 if(route.startsWith('/proje/'))crumbs.push({name:'Bitirdiğimiz İşler',url:base+'/projeler/'});
 if(route.startsWith('/kategoriler/'))crumbs.push({name:'Kategoriler',url:base+'/kategoriler/'});
 if(route.startsWith('/rehber/'))crumbs.push({name:'Atölye Notları',url:base+'/rehber/'});
 if(route!=='/')crumbs.push({name:pageTitle(route).split(' | ')[0],url});
 const schema:any={'@context':'https://schema.org','@type':'WebPage','@id':url+'#sayfa',name:pageTitle(route),description:pageDescription(route),url,inLanguage:'tr-TR',publisher,isPartOf:{'@type':'WebSite','@id':base+'/#website',name:business.name,url:base+'/'},breadcrumb:{'@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:c.url}))}};
 const article=journal.find(j=>'/rehber/'+j.id===route);
 if(article)schema.mainEntity={'@type':'Article',headline:article.title,description:article.intro,image:base+'/assets/'+pageShareImage(route),inLanguage:'tr-TR',author:{'@type':'Organization',name:business.name},publisher,mainEntityOfPage:url};
 return schema;
}
