/** Decision support, not a fabrication specification or an attributed interview. */
export type ServiceContent={title:string;intro:string;sections:[string,string][];preparation:string[];project?:string;concept?:string;note:string};
export const serviceContent:Record<string,ServiceContent>={
 'kahve-kosesi':{title:'Kahve köşesi dolabı. Makinenizden başlayalım.',intro:'Sabah fincanı aldığınız, makinenin suyunu doldurduğunuz ve kahveyi hazırladığınız bir köşe. Dolabın yerleşimini bu küçük hareketlerden başlayarak düşünelim.',sections:[
 ['Makinenin ölçüsü tek başına yetmez.','Makinenin marka ve modelini paylaşın. Su haznesinin çıktığı yöne, üst kapağın açılmasına ve temizlik için erişime birlikte bakalım. Niş ölçüsünü cihazın üretici belgesindeki kullanım ve havalandırma boşluklarıyla değerlendirelim.'],
 ['Açık raf mı, kapalı depolama mı?','Günlük fincanları el altında tutmakla yedek ekipmanları saklamak farklı ihtiyaçlar. Görünmesini istediğiniz parçaları, kapalı dolapta duracakları ve çekmeceye ayıracağınız küçük gereçleri üç grupta düşünün.'],
 ['Servis yüzeyi de çalışma alanıdır.','Makinenin yanında fincan, öğütücü ve hazırlık için ne kadar yere ihtiyacınız var? Tezgâhın kullanımını bu eşyalarla tarif edin. Kablo çıkışı, priz, su bağlantısı ve aydınlatmayı ayrıca konuşalım. Elektrik ve tesisat işlerinin teklifteki yerini baştan netleştirelim.'],
 ['Fotoğraftaki ayrıntıyı kendi alanınıza uyarlayın.','Arşivdeki gerçek örnekte kemerli orta bölüm, cam yan vitrinler ve alt çekmeceler bir arada. Bu düzenin hangi ayrıntısını beğendiğinizi söyleyin. Sizin dolabınızın ölçüsü, yüzeyi, donanımı ve fiyatı cihazınıza ve seçtiğiniz kapsama göre ayrıca belirlenir.']
 ],preparation:['Makinenin marka/modeli veya ürün belgesi.','Hazne ve kapak açılırken çekilmiş bir fotoğraf.','Duvarın tamamı, yaklaşık en ve priz konumları.','Açıkta kalmasını ve saklanmasını istediğiniz ekipmanlar.'],project:'kemerli-kahve-kosesi',note:'Üretim ölçüsü değildir. Cihaz açıklıkları üretici bilgisiyle, mobilya ve uygulama kapsamı Yunus Usta ile ayrıca teyit edilir.'},
 'mutfak':{title:'Mutfak dolabı. Görünüm kadar günlük düzen.',intro:'Tencereye uzanmak, tabakları yerleştirmek, tezgâhta hazırlık yapmak. Yeni mutfağı düşünürken önce bugün sizi zorlayan noktaları konuşalım. Görünümü, cihazları ve depolamayı bu ihtiyaçlarla birlikte ele alalım.',sections:[
 ['Önce korunacakları belirleyin.','Beyaz eşya, tezgâh, evye ve tesisattan hangileri kalacak, hangileri değişecek? Cihaz marka ve modellerini, mevcut bağlantı noktalarını paylaşın. Dolapla birlikte tezgâh, söküm, elektrik ve tesisat için gereken işleri de teklif görüşmesine dahil edelim.'],
 ['Çekmece ve kapağı kullanımına göre seçin.','En sık kullandığınız tencere, tabak ve kuru gıdalara nereden ulaşmak istersiniz? Çekmece ve rafların görevini bu eşyalara göre belirleyelim. Kapaklar ve çekmeceler açıldığında geçişi, oda kapısını ve karşıdaki mobilyayı da birlikte değerlendirelim.'],
 ['Aynı ölçü, aynı teklif demek değildir.','Gövde, kapak, yüzey, ray ve menteşe seçimleri teklifin parçalarıdır. Karşılaştırırken hangi ürünlerin ve hangi montaj işlerinin dahil olduğunu sorun. Beğendiğiniz rengin yanında yüzeyin dokusunu ve bakım bilgisini de gerçek ürün bilgisiyle değerlendirelim.'],
 ['İlk görüşmeye yaklaşık ölçüyle başlayın.','Duvarın yaklaşık eni, tavan yüksekliği, pencere ve kapı konumları ilk görüşmeye yardımcı olur. Birkaç genel fotoğrafla birlikte paylaşabilirsiniz. Üretime esas son ölçü ve gerekli yerinde inceleme, tasarım netleşirken ayrıca ele alınır.']
 ],preparation:['Mekânın iki köşesinden genel fotoğraf.','Kalacak cihazların marka/model listesi.','Yaklaşık duvar ölçüleri ve pencere/kapı konumları.','Bugünkü mutfakta zorlandığınız üç kullanım durumu.'],project:'sade-kose-mutfak',note:'Üretim öncesinde son ölçü, kapak ve donanım, tezgâh, tesisat, taşıma ve montaj kapsamları yazılı olarak netleşir.'},
 'tv-unitesi':{title:'TV ünitesi. Ekran, kablo ve depolama bir arada.',intro:'Ekranın çevresinde sakin bir görünüm, cihazlara erişim ve eşyalara yer. TV ünitesini ekranınızla, kullandığınız cihazlarla ve saklamak istediğiniz parçalarla birlikte düşünelim.',sections:[
 ['Ekranı ve diğer cihazları birlikte listeleyin.','TV modelini ve ayaklı ya da duvara asılı kullanım tercihinizi paylaşın. Ses sistemi, oyun konsolu ve modem gibi diğer cihazları da ekleyin. Her cihazın yeri, bağlantıları ve üreticisinin montaj ve havalandırma koşulları birlikte değerlendirilir.'],
 ['Kablolar gizlensin, erişim kaybolmasın.','Priz, anten ve veri noktalarının fotoğrafını paylaşın. Kabloların nereden geçeceğini, cihaz değiştirirken ya da temizlikte arka bölüme nasıl ulaşacağınızı konuşalım. Böylece görünümle birlikte günlük erişimi de tasarımın parçası yapabiliriz.'],
 ['Sergileme ile depolamayı ayırın.','Kitap, dekor ve kapalı tutulacak cihazlar için farklı alanlar gerekebilir. Açık raf, cam bölüm ve kapaklı alt dolap seçeneklerini neyi kullanacağınız üzerinden karşılaştırın. Aydınlatma ve elektrik bağlantıları ayrı iş kapsamlarıdır.'],
 ['Duvar ve geçiş alanı belirleyicidir.','Duvarın enini, kapı açılımını, süpürgeliği ve yakın mobilyaları gösteren bir fotoğraf hazırlayın. Ünitenin oda içindeki yerini bu bilgilerle konuşalım. Duvara sabitleme ve taşıma uygunluğu ise yerinde ayrıca kontrol edilir.']
 ],preparation:['TV marka/modeli, ayak veya askı tercihi.','Ses sistemi ve diğer cihazların listesi.','Duvarın tamamı ve bağlantı noktalarının fotoğrafı.','Saklanacak eşyalar ve açıkta sergilenecek parçalar.'],project:'isikli-tv-unitesi',note:'Üretim ölçüsü, duvar bağlantısı ve cihaz gereklilikleri ayrıca kontrol edilir. Görseldeki TV, dekor ve elektrik işleri kendiliğinden teklif kapsamına girmez.'},
 'gardrop':{title:'Gardırop. Her eşyanın yeri ayrı.',intro:'Sabah aradığınız gömleğe ulaşmak, uzun giysileri asmak, mevsimlik eşyaları kaldırmak. Gardırobun içini, elinizdeki kıyafetlere ve kullandığınız düzene göre birlikte planlayalım.',sections:[
 ['Askı, raf ve çekmeceyi ayrı düşünün.','Uzun giysiler, katlanmış kıyafetler, çantalar ve küçük parçalar için önceliklerinizi sıralayın. Günlük kullandıklarınız ile mevsimlik sakladıklarınızın aynı yerde durması gerekmeyebilir. İç düzeni eşya listenizle değerlendirelim.'],
 ['Kapak açıkken odanız nasıl kullanılıyor?','Dolabın karşısındaki yatak, oda kapısı ve geçiş yönü kapak seçimini etkiler. Sürgülü ve menteşeli seçenekleri, kapağı açtığınızda ulaşmak istediğiniz bölmelerle birlikte konuşalım. Son açıklıklar, iç bölmeler ve donanım uygunluğu ölçüyle netleşir.'],
 ['Görünür olanla saklanacak olanı ayırın.','Çantaları sergilemek, günlük kıyafetleri görmek ya da tüm eşyaları kapak arkasında tutmak isteyebilirsiniz. Arşivdeki cam kapaklı köşe uygulamasının raf ve askı düzenine bakın. Hangi bölümlerin görünür, hangilerinin kapalı olmasını istediğinizi bu örnekle anlatabilirsiniz.']
 ],preparation:['Askıda, rafta ve çekmecede tutacağınız eşya grupları.','Dolap duvarını, oda kapısını ve karşı mobilyayı gösteren fotoğraf.','Varsa yaklaşık en, derinlik ve yükseklik.','Açık raf, cam veya kapalı kapak tercihiniz.'],project:'cam-kapak-giyinme',note:'Bu bir görüşme hazırlığıdır. Son ölçü, iç bölmeler, sabitleme ve donanım kapasitesi üretim öncesinde ayrıca değerlendirilir.'},
 'vestiyer':{title:'Antre. Evinize nasıl giriyorsunuz?',intro:'Montu bırakmak, ayakkabıyı değiştirmek, anahtarı bulmak. Girişteki düzeni günlük hareketlerinizden başlayarak birlikte düşünelim.',sections:[
 ['Günlük eşyaları ayrı bir gruba alın.','Sık kullanılan ayakkabı ve montlarla yedek ya da mevsimlik eşyaları ayırın. Açık askılık mı, kapalı depolama mı sizin için daha kullanışlı olacak? Çanta ve küçük eşyaların yerini de ilk konuşmaya katın.'],
 ['Ayakkabıyı değiştirirken, çantayı bırakırken.','Ayakkabı değiştirirken oturacak bir yer, çantanızı bırakacak bir yüzey veya anahtar için bir çekmece düşünüyor musunuz? Bunlardan hangisinin öncelikli olduğunu söyleyin. Bank, ayna, raf ve dolabın birlikte nasıl yerleşeceğini alanınıza göre değerlendirelim.'],
 ['Kapı açılımını ve erişilecek noktaları gösterin.','Giriş kapısının hareketi, süpürgelik, priz ve erişimi korunacak pano gibi noktaları fotoğrafa dahil edin. Depolama eklerken geçişi ve günlük erişimi nasıl koruyacağınızı görüşelim.']
 ],preparation:['Giriş alanının ve kapının açık hâlinin fotoğrafı.','Günlük mont, ayakkabı ve çanta ihtiyacı.','Oturma, ayna ve küçük eşya yüzeyi tercihi.','Varsa yaklaşık duvar ölçüsü ve erişilecek noktalar.'],project:'rafli-depolama',note:'Arşiv örneği açık raflı depolamadır. Antrenize uyarlanacak düzen, son ölçü, sabitleme ve varsa oturma bölümünün uygunluğu ayrıca değerlendirilir.'},
 'sehpa':{title:'Sehpa ve zigon. Bir arada mı, ayrı ayrı mı?',intro:'Koltuğun yanında bir fincan için yer, ortada kitaplar için yüzey, misafir geldiğinde ayrılan küçük sehpalar. Hangi kullanıma ihtiyacınız olduğunu seçerek başlayalım.',sections:[
 ['Kullanacağınız anı anlatın.','Kitap bırakmak, içecek servis etmek veya misafir geldiğinde farklı noktalara yüzey açmak ayrı ihtiyaçlar. Tek orta sehpa, yan sehpa ve zigon seçeneklerini hangi anda kullanacağınızı düşünerek karşılaştırın.'],
 ['Kapalı ve açılmış düzeni birlikte düşünün.','İç içe duran parçaların ayrıldığında nerede kullanılacağını ve kullanılmadığında nerede duracağını tarif edin. Oturma düzeni ile dolaşım alanı, yalnız bir sehpanın en ve boyundan daha fazla bilgi verir.'],
 ['Kenar ve yüzey tercihinizi belirleyin.','Oval ya da köşeli formu, açık ya da koyu tonu mevcut oturma alanınızla birlikte düşünün. Yüzeyin dokusu, günlük bakım ihtiyacı ve depolama isteğiniz de seçimin parçası olsun. Malzeme ve yüzey işlemi, gerçek ürün bilgisiyle ayrıca netleşir.']
 ],preparation:['Koltuk düzenini ve mevcut sehpayı gösteren fotoğraf.','Tek yüzey veya ayrı kullanılan parçalar tercihi.','Kullanılmadığında saklama veya iç içe toplama ihtiyacı.','Beğendiğiniz form ve değiştirmek istediğiniz ayrıntı.'],concept:'oval-orta-sehpa',note:'Bu kategorinin örneği bir konsept görseldir, tamamlanmış atölye işi değildir. Üretim ölçüsü, gerçek malzeme ve kullanılabilirlik ayrıca değerlendirilir.'},
 'pergola':{title:'Açık alan. Önce yeri ve koşulları tanıyalım.',intro:'Bahçede oturmak, gölgede yemek yemek veya bir köşeyi kullanıma açmak. Önce bu alanda nasıl vakit geçirmek istediğinizi anlatın. Zemin, çevre ve uygulama koşullarını ardından birlikte ele alalım.',sections:[
 ['Alanı ve erişimi gösterin.','Çalışmanın düşünüldüğü yer, çevresindeki yapılar, zemin ve taşıma erişimini gösteren fotoğraflarla başlayın. İlk ölçüler saha değerlendirmesinin ve teknik projenin yerine geçmez.'],
 ['Kullanım ve maruziyeti tarif edin.','Oturma, gölgelenme veya başka bir kullanım mı düşünüyorsunuz? Alanın yağış ve rüzgârla ilişkisi, çatı yaklaşımı ve drenaj gereksinimi yetkin teknik değerlendirmeyle ele alınmalıdır.'],
 ['Kapsamı baştan ayırın.','Ahşap yapı, zemin hazırlığı, çatı, elektrik ve bakım için gereken işleri ayrı ayrı konuşalım. Teklifte hangi işin kim tarafından yapılacağı açık olsun. Gerekli izinler, taşıyıcı hesapları ve uygulama sorumlulukları üretimden önce netleşir.']
 ],preparation:['Alanı ve çevresini gösteren genel fotoğraflar.','Zemin hakkında bildikleriniz ve erişim koşulları.','Kullanım amacınız ve yaklaşık yerleşim düşünceniz.'],project:'ahsap-bahce-kamelyasi',note:'Açıklık, taşıma kapasitesi veya bağlantı hesabı burada verilmez. Güvenli uygulama için saha koşulları, teknik proje ve gerekli izinler ayrıca değerlendirilir.'},
 'ozel-tasarim':{title:'Özel tasarım. Fikrin hangi ayrıntısını koruyalım?',intro:'Bir fotoğraftaki kapağı, başka bir modelin raf düzenini ya da kendi çizdiğiniz bir fikri beğenmiş olabilirsiniz. Neyi sevdiğinizi ve nerede kullanacağınızı Yunus Usta’ya anlatın. Birlikte üzerinden geçelim.',sections:[
 ['Beğendiğiniz özelliği seçin.','Form, doku, depolama düzeni veya hareketli bir parça. Referansta sizin için asıl önemli olan ayrıntıyı tarif edin. Tek bir özelliği seçerek başlayabilir, diğer bölümleri kendi ihtiyacınıza göre yeniden düşünebilirsiniz.'],
 ['Değişmesini istediğinizi ekleyin.','Daha dar bir ölçü, kapalı bir raf, farklı bir ton veya başka bir kullanım önceliğiniz olabilir. Örneğin görseldeki biçimi koruyup içini daha fazla depolama için düşünmek isteyebilirsiniz. Korumak ve değiştirmek istediklerinizi ayrı ayrı yazın.'],
 ['Uygunluğu birlikte değerlendirelim.','Referansı mekânınız, yaklaşık ölçünüz ve kullanım önceliğinizle birlikte değerlendirelim. Malzeme, donanım ve varsa mekanizmanın nasıl uygulanabileceğini konuşalım. Üretilecek çözüm, son ölçü ve teklif kapsamı bu görüşmelerle şekillenir.']
 ],preparation:['Bir fotoğraf, çizim, bağlantı veya kısa fikir notu.','Korumak ve değiştirmek istediğiniz özellikler.','Kullanılacağı alan ve varsa yaklaşık ölçü.'],project:'yatak-cevresi-depolama',note:'İlk görüşme, tasarım onayı ve kesin teklif farklı adımlardır. Son ölçü ve kapsam üretimden önce ayrıca kararlaştırılır.'}
};
