/** Decision support, not a fabrication specification or an attributed interview. */
export type ServiceContent={title:string;intro:string;sections:[string,string][];preparation:string[];project?:string;concept?:string;note:string};
export const serviceContent:Record<string,ServiceContent>={
 'kahve-kosesi':{title:'Kahve köşesi dolabı. Makinenizden başlayalım.',intro:'Bir kahve alanını yalnız dolabın eniyle planlamayalım. Makineyi kullanırken, temizlerken ve fincan hazırlarken yaptığınız hareketleri de konuşalım.',sections:[
 ['Makinenin ölçüsü tek başına yetmez.','Marka ve modeli, su haznesinin nasıl çıkarıldığını ve varsa üst kapağın açılma yönünü paylaşın. Cihazın üretici belgesindeki kullanım ve havalandırma boşluklarını ayrıca kontrol edelim. Her makineye uyan tek bir niş derinliği vermek doğru olmaz.'],
 ['Açık raf mı, kapalı depolama mı?','Günlük fincanları el altında tutmakla yedek ekipmanları saklamak farklı ihtiyaçlar. Görünmesini istediğiniz parçaları, kapalı dolapta duracakları ve çekmeceye ayıracağınız küçük gereçleri üç grupta düşünün.'],
 ['Servis yüzeyi de çalışma alanıdır.','Makinenin yanında fincan koyacağınız, öğütücüyü kullanacağınız veya ekipmanı temizleyeceğiniz yüzeyi tarif edin. Kablo çıkışı, priz konumu, su bağlantısı ve aydınlatma ayrı kararlardır. Elektrik ve tesisat işinin teklife dahil olduğunu varsaymayın.'],
 ['Fotoğraftaki ayrıntıyı kendi alanınıza uyarlayın.','Kemerli orta bölüm, cam yan vitrin ve alt çekmeceler, arşivdeki gerçek örnekte birlikte görülebilir. Aynı görünümün sizin alanınızda nasıl çalışacağı cihaz ve ölçü bilgisiyle değerlendirilir. Fotoğraftan malzeme markası, fiyat veya teslim süresi çıkarılmaz.']
 ],preparation:['Makinenin marka/modeli veya ürün belgesi.','Hazne ve kapak açılırken çekilmiş bir fotoğraf.','Duvarın tamamı, yaklaşık en ve priz konumları.','Açıkta kalmasını ve saklanmasını istediğiniz ekipmanlar.'],project:'kemerli-kahve-kosesi',note:'Üretim ölçüsü değildir. Cihaz açıklıkları üretici bilgisiyle, mobilya ve uygulama kapsamı Yunus Usta ile ayrıca teyit edilir.'},
 'mutfak':{title:'Mutfak dolabı. Görünüm kadar günlük düzen.',intro:'Mevcut alanı, korunacak cihazları ve sık kullandığınız eşyaları birlikte ele alalım. Bir planın fotoğrafta güzel görünmesi, sizin mutfağınıza aynen uyacağı anlamına gelmez.',sections:[
 ['Önce korunacakları belirleyin.','Beyaz eşya, tezgâh, evye ve tesisattan hangileri kalacak? Cihaz marka/modelini ve mevcut bağlantı noktalarını paylaşın. Dolap siparişi, tezgâh veya elektrik işlerinin otomatik olarak dahil olduğu anlamına gelmez.'],
 ['Çekmece ve kapağı kullanımına göre seçin.','Tencere, tabak, kuru gıda ve temizlik malzemelerinin nerede duracağını düşünün. Bir çekmecenin açılması için gereken alanı yalnız kapalı dolap ölçüsünden anlayamayız. Geçişler, kapılar ve karşıdaki mobilya da yerleşimin parçasıdır.'],
 ['Aynı ölçü, aynı teklif demek değildir.','Gövde, kapak, yüzey, ray ve menteşeleri ayrı kalemler olarak konuşun. İki teklifi karşılaştırırken yalnız toplam tutara değil, donanım ve montaj kapsamına da bakın. Gerçek ürün seçimi ve numune onayı olmadan aynı renk aynı malzeme sayılmaz.'],
 ['Yaklaşık ölçüyle başlayın, son ölçüyü onaylayın.','Duvar boyunca yaklaşık en, tavan yüksekliği, pencere ve kapı konumları ilk görüşmeye yardımcı olur. Fotoğraf ve ölçü hazırlığı, yerinde inceleme ya da imalata esas son ölçünün yerine geçmez.']
 ],preparation:['Mekânın iki köşesinden genel fotoğraf.','Kalacak cihazların marka/model listesi.','Yaklaşık duvar ölçüleri ve pencere/kapı konumları.','Bugünkü mutfakta zorlandığınız üç kullanım durumu.'],project:'sade-kose-mutfak',note:'Üretim öncesinde son ölçü, kapak ve donanım, tezgâh, tesisat, taşıma ve montaj kapsamları yazılı olarak netleşir.'},
 'tv-unitesi':{title:'TV ünitesi. Ekran, kablo ve depolama bir arada.',intro:'Panelin görünümünü seçmeden önce ekranınızı, diğer cihazları ve duvarın kullanımını konuşalım. Yalnız televizyonun inç ölçüsü bütün yerleşimi tarif etmez.',sections:[
 ['Ekranı ve diğer cihazları birlikte listeleyin.','TV modeli, ayak veya askı tercihi, ses sistemi, oyun konsolu ve modem gibi cihazları belirtin. Üreticinin montaj ve havalandırma talimatları cihaz özelinde değerlendirilmelidir. Evrensel askı yüksekliği veya kapalı raf ölçüsü vermiyoruz.'],
 ['Kablolar gizlensin, erişim kaybolmasın.','Priz, anten ve veri noktalarının fotoğrafını paylaşın. Günlük kullanımda görünmeyen bir kablonun bakım veya cihaz değişiminde erişilebilir olması da önemlidir. Panel ve dolabın arkasına nasıl ulaşılacağını tasarım görüşmesinde sorun.'],
 ['Sergileme ile depolamayı ayırın.','Kitap, dekor ve kapalı tutulacak cihazlar için farklı alanlar gerekebilir. Açık raf, cam bölüm ve kapaklı alt dolap seçeneklerini neyi kullanacağınız üzerinden karşılaştırın. Aydınlatma ve elektrik bağlantıları ayrı iş kapsamlarıdır.'],
 ['Duvar ve geçiş alanı belirleyicidir.','Duvarın eni, kapı açılımı, süpürgelik ve yakın mobilyalar yerleşimi etkiler. Duvara sabitleme uygunluğu ve taşıma ihtiyacı yerinde kontrol edilmelidir. Bir arşiv fotoğrafı duvarınızın taşıma kapasitesini kanıtlamaz.']
 ],preparation:['TV marka/modeli, ayak veya askı tercihi.','Ses sistemi ve diğer cihazların listesi.','Duvarın tamamı ve bağlantı noktalarının fotoğrafı.','Saklanacak eşyalar ve açıkta sergilenecek parçalar.'],project:'isikli-tv-unitesi',note:'Üretim ölçüsü, duvar bağlantısı ve cihaz gereklilikleri ayrıca kontrol edilir. Görseldeki TV, dekor ve elektrik işleri kendiliğinden teklif kapsamına girmez.'},
 'gardrop':{title:'Gardırop. Önce içinde yaşayacak düzen.',intro:'Askıdaki kıyafetler, katlanan parçalar ve küçük eşyalar aynı depolama ihtiyacı değildir. Dış görünümü seçmeden önce içeride neye yer ayıracağınızı konuşalım.',sections:[
 ['Askı, raf ve çekmeceyi ayrı düşünün.','Uzun giysiler, katlanmış kıyafetler, çantalar ve küçük parçalar için önceliklerinizi sıralayın. Günlük kullandıklarınız ile mevsimlik sakladıklarınızın aynı yerde durması gerekmeyebilir. İç düzeni eşya listenizle değerlendirelim.'],
 ['Kapak açıkken odanız nasıl kullanılıyor?','Dolabın karşısındaki yatak veya diğer mobilyalar, oda kapısı ve geçiş yönü birlikte ele alınır. Sürgülü veya menteşeli kapağı yalnız görünümüne göre değil, açıldığında ulaşmak istediğiniz bölmelere göre konuşun. Kesin açıklık ve donanım uygunluğu ayrıca teyit edilir.'],
 ['Görünür olanla saklanacak olanı ayırın.','Açık raf, cam kapak ve kapalı bölmeler farklı tercihlerdir. Cam kapaklı köşe uygulamasında raf ve askı alanları görülüyor. İçerideki eşyalarınızın ne kadar görünmesini istediğinizi bu örnek üzerinden anlatabilirsiniz.']
 ],preparation:['Askıda, rafta ve çekmecede tutacağınız eşya grupları.','Dolap duvarını, oda kapısını ve karşı mobilyayı gösteren fotoğraf.','Varsa yaklaşık en, derinlik ve yükseklik.','Açık raf, cam veya kapalı kapak tercihiniz.'],project:'cam-kapak-giyinme',note:'Bu bir görüşme hazırlığıdır. Son ölçü, iç bölmeler, sabitleme ve donanım kapasitesi üretim öncesinde ayrıca değerlendirilir.'},
 'vestiyer':{title:'Antre. Evinize nasıl giriyorsunuz?',intro:'Montu bırakmak, ayakkabıyı değiştirmek, anahtarı bulmak. Girişteki düzeni günlük hareketlerinizden başlayarak birlikte düşünelim.',sections:[
 ['Günlük eşyaları ayrı bir gruba alın.','Sık kullanılan ayakkabı ve montlarla yedek ya da mevsimlik eşyaları ayırın. Açık askılık mı, kapalı depolama mı sizin için daha kullanışlı olacak? Çanta ve küçük eşyaların yerini de ilk konuşmaya katın.'],
 ['Oturma ve servis yüzeyi ihtiyacını tarif edin.','Ayakkabı değiştirirken oturmak, kısa süreli çanta bırakmak veya ayna kullanmak isteyebilirsiniz. Bank, çekmece ve rafın birlikte çözülüp çözülemeyeceği alanla değerlendirilir. Bir fotoğraf oturma elemanının taşıma kapasitesini göstermez.'],
 ['Kapı açılımını ve erişilecek noktaları gösterin.','Giriş kapısının hareketi, süpürgelik, priz ve erişimi korunacak pano gibi noktaları fotoğrafa dahil edin. Depolama eklerken geçişi ve günlük erişimi nasıl koruyacağınızı görüşelim.']
 ],preparation:['Giriş alanının ve kapının açık hâlinin fotoğrafı.','Günlük mont, ayakkabı ve çanta ihtiyacı.','Oturma, ayna ve küçük eşya yüzeyi tercihi.','Varsa yaklaşık duvar ölçüsü ve erişilecek noktalar.'],project:'rafli-depolama',note:'Arşiv örneği açık raflı depolamadır. Fotoğrafın özgün kullanım yerini varsaymıyoruz. Sizin antrenize uygunluk, ölçü ve uygulama koşullarıyla ayrıca belirlenir.'},
 'sehpa':{title:'Sehpa ve zigon. Bir arada mı, ayrı ayrı mı?',intro:'Bir orta yüzey mi, koltuğun yanına taşınabilen küçük parçalar mı gerekiyor? Seçimi yalnız form üzerinden değil, kullanım senaryonuzla birlikte yapalım.',sections:[
 ['Kullanacağınız anı anlatın.','Kitap bırakmak, içecek servis etmek veya misafir geldiğinde farklı noktalara yüzey açmak ayrı ihtiyaçlar. Tek orta sehpa, yan sehpa ve zigon seçeneklerini hangi anda kullanacağınızı düşünerek karşılaştırın.'],
 ['Kapalı ve açılmış düzeni birlikte düşünün.','İç içe duran parçaların ayrıldığında nerede kullanılacağını ve kullanılmadığında nerede duracağını tarif edin. Oturma düzeni ile dolaşım alanı, yalnız bir sehpanın en ve boyundan daha fazla bilgi verir.'],
 ['Kenar ve yüzey tercihinizi belirleyin.','Oval ya da köşeli form, açık veya koyu ton ve depolama isteği konuşulabilir. Kenar biçimi tek başına güvenlik garantisi değildir. Gerçek malzeme, yüzey işlemi ve bakım koşulları numune ve ürün bilgisiyle netleşir.']
 ],preparation:['Koltuk düzenini ve mevcut sehpayı gösteren fotoğraf.','Tek yüzey veya ayrı kullanılan parçalar tercihi.','Kullanılmadığında saklama veya iç içe toplama ihtiyacı.','Beğendiğiniz form ve değiştirmek istediğiniz ayrıntı.'],concept:'oval-orta-sehpa',note:'Bu kategorinin örneği bir konsept görseldir, tamamlanmış atölye işi değildir. Üretim ölçüsü, gerçek malzeme ve kullanılabilirlik ayrıca değerlendirilir.'},
 'pergola':{title:'Açık alan. Önce yeri ve koşulları tanıyalım.',intro:'Bir bahçe fotoğrafı iyi bir başlangıçtır. Zemin, çevre ve kullanım koşullarını bilmeden taşıyıcı veya bağlantı çözümü belirlemeyelim.',sections:[
 ['Alanı ve erişimi gösterin.','Çalışmanın düşünüldüğü yer, çevresindeki yapılar, zemin ve taşıma erişimini gösteren fotoğraflarla başlayın. İlk ölçüler saha değerlendirmesinin ve teknik projenin yerine geçmez.'],
 ['Kullanım ve maruziyeti tarif edin.','Oturma, gölgelenme veya başka bir kullanım mı düşünüyorsunuz? Alanın yağış ve rüzgârla ilişkisi, çatı yaklaşımı ve drenaj gereksinimi yetkin teknik değerlendirmeyle ele alınmalıdır.'],
 ['Kapsamı baştan ayırın.','Ahşap yapı, zemin hazırlığı, çatı, elektrik ve bakım farklı iş kalemleri olabilir. Gerekli izinler, taşıyıcı hesapları ve uygulama sorumlulukları netleşmeden bir görsel üretim onayı değildir.']
 ],preparation:['Alanı ve çevresini gösteren genel fotoğraflar.','Zemin hakkında bildikleriniz ve erişim koşulları.','Kullanım amacınız ve yaklaşık yerleşim düşünceniz.'],project:'ahsap-bahce-kamelyasi',note:'Açıklık, taşıma kapasitesi veya bağlantı hesabı burada verilmez. Güvenli uygulama için saha koşulları, teknik proje ve gerekli izinler ayrıca değerlendirilir.'},
 'ozel-tasarim':{title:'Özel tasarım. Fikrin hangi ayrıntısını koruyalım?',intro:'Hazır bir çiziminiz olması gerekmiyor. Bir fotoğraf, bağlantı ya da birkaç cümleyle neyi sevdiğinizi anlatabilirsiniz.',sections:[
 ['Beğendiğiniz özelliği seçin.','Form, doku, depolama düzeni veya hareketli bir parça. Referansta sizin için asıl önemli olan ayrıntıyı tarif edin. Görseldeki her şeyin aynı biçimde üretilmesini istemek zorunda değilsiniz.'],
 ['Değişmesini istediğinizi ekleyin.','Daha küçük bir ölçü, farklı bir ton veya başka bir kullanım önceliğiniz olabilir. Sizin notunuz ile referansın açıklamasını ayrı tutarak başlayalım.'],
 ['Uygunluğu birlikte değerlendirelim.','Mekân, malzeme, donanım ve mekanizma, atölye görüşmesinde netleşir. Bir referans veya 3D konsept, teknik çizim ya da kesin üretim taahhüdü değildir.']
 ],preparation:['Bir fotoğraf, çizim, bağlantı veya kısa fikir notu.','Korumak ve değiştirmek istediğiniz özellikler.','Kullanılacağı alan ve varsa yaklaşık ölçü.'],project:'yatak-cevresi-depolama',note:'İlk görüşme, tasarım onayı ve kesin teklif farklı adımlardır. Son ölçü ve kapsam üretimden önce ayrıca kararlaştırılır.'}
};
