/** Decision support, not a fabrication specification or an attributed interview. */
export type ServiceContent={title:string;intro:string;sections:[string,string][];preparation:string[];project:string;note:string};
export const serviceContent:Record<string,ServiceContent>={
 'kahve-kosesi':{title:'Kahve köşesi dolabı. Makinenizden başlayalım.',intro:'Bir kahve alanını yalnız dolabın eniyle planlamayalım. Makineyi kullanırken, temizlerken ve fincan hazırlarken yaptığınız hareketleri de konuşalım.',sections:[
 ['Makinenin ölçüsü tek başına yetmez.','Marka ve modeli, su haznesinin nasıl çıkarıldığını ve varsa üst kapağın açılma yönünü paylaşın. Cihazın üretici belgesindeki kullanım ve havalandırma boşluklarını ayrıca kontrol edelim. Her makineye uyan tek bir niş derinliği vermek doğru olmaz.'],
 ['Açık raf mı, kapalı depolama mı?','Günlük fincanları el altında tutmakla yedek ekipmanları saklamak farklı ihtiyaçlar. Görünmesini istediğiniz parçaları, kapalı dolapta duracakları ve çekmeceye ayıracağınız küçük gereçleri üç grupta düşünün.'],
 ['Servis yüzeyi de çalışma alanıdır.','Makinenin yanında fincan koyacağınız, öğütücüyü kullanacağınız veya ekipmanı temizleyeceğiniz yüzeyi tarif edin. Kablo çıkışı, priz konumu, su bağlantısı ve aydınlatma ayrı kararlardır. Elektrik ve tesisat işinin teklife dahil olduğunu varsaymayın.'],
 ['Fotoğraftaki ayrıntıyı kendi alanınıza uyarlayın.','Kemerli orta bölüm, cam yan vitrin ve alt çekmeceler, arşivdeki gerçek örnekte birlikte görülebilir. Aynı görünümün sizin alanınızda nasıl çalışacağı cihaz ve ölçü bilgisiyle değerlendirilir. Fotoğraftan malzeme markası, fiyat veya teslim süresi çıkarılmaz.']
 ],preparation:['Makinenin marka/modeli veya ürün belgesi.','Hazne ve kapak açılırken çekilmiş bir fotoğraf.','Duvarın tamamı, yaklaşık en ve priz konumları.','Açıkta kalmasını ve saklanmasını istediğiniz ekipmanlar.'],project:'kemerli-kahve-kosesi',note:'Üretim ölçüsü değildir. Cihaz açıklıkları üretici bilgisiyle, mobilya ve uygulama kapsamı Yunus Usta ile ayrıca teyit edilir.'},
 'mutfak':{title:'Mutfak dolabı. Görünüm kadar günlük düzen.',intro:'Mevcut alanı, korunacak cihazları ve sık kullandığınız eşyaları birlikte ele alalım. Bir planın fotoğrafta güzel görünmesi, sizin mutfağınıza aynen uyacağı anlamına gelmez.',sections:[
 ['Önce korunacakları belirleyin.','Beyaz eşya, tezgâh, evye ve tesisattan hangileri kalacak? Cihaz marka/modelini ve mevcut bağlantı noktalarını paylaşın. Dolap siparişi, tezgâh veya elektrik işlerinin otomatik olarak dahil olduğu anlamına gelmez.'],
 ['Çekmece ve kapağı kullanımına göre seçin.','Tencere, tabak, kuru gıda ve temizlik malzemelerinin nerede duracağını düşünün. Bir çekmecenin açılması için gereken alanı yalnız kapalı dolap ölçüsünden anlayamayız. Geçişler, kapılar ve karşıdaki mobilya da yerleşimin parçasıdır.'],
 ['Aynı ölçü, aynı teklif demek değildir.','Gövde, kapak, yüzey, ray ve menteşeleri ayrı kalemler olarak konuşun. İki teklifi karşılaştırırken yalnız toplam tutara değil, donanım ve montaj kapsamına da bakın. Gerçek ürün seçimi ve numune onayı olmadan aynı renk aynı malzeme sayılmaz.'],
 ['Yaklaşık ölçüyle başlayın, son ölçüyü onaylayın.','Duvar boyunca yaklaşık en, tavan yüksekliği, pencere ve kapı konumları ilk görüşmeye yardımcı olur. Fotoğraf ve ölçü hazırlığı, yerinde inceleme ya da imalata esas son ölçünün yerine geçmez.']
 ],preparation:['Mekânın iki köşesinden genel fotoğraf.','Kalacak cihazların marka/model listesi.','Yaklaşık duvar ölçüleri ve pencere/kapı konumları.','Bugünkü mutfakta zorlandığınız üç kullanım durumu.'],project:'sade-kose-mutfak',note:'Üretim öncesinde son ölçü, kapak ve donanım, tezgâh, tesisat, taşıma ve montaj kapsamları yazılı olarak netleşir.'},
 'tv-unitesi':{title:'TV ünitesi. Ekran, kablo ve depolama bir arada.',intro:'Panelin görünümünü seçmeden önce ekranınızı, diğer cihazları ve duvarın kullanımını konuşalım. Yalnız televizyonun inç ölçüsü bütün yerleşimi tarif etmez.',sections:[
 ['Ekranı ve diğer cihazları birlikte listeleyin.','TV modeli, ayak veya askı tercihi, ses sistemi, oyun konsolu ve modem gibi cihazları belirtin. Üreticinin montaj ve havalandırma talimatları cihaz özelinde değerlendirilmelidir. Evrensel askı yüksekliği veya kapalı raf ölçüsü vermiyoruz.'],
 ['Kablolar gizlensin, erişim kaybolmasın.','Priz, anten ve veri noktalarının fotoğrafını paylaşın. Günlük kullanımda görünmeyen bir kablonun bakım veya cihaz değişiminde erişilebilir olması da önemlidir. Panel ve dolabın arkasına nasıl ulaşılacağını tasarım görüşmesinde sorun.'],
 ['Sergileme ile depolamayı ayırın.','Kitap, dekor ve kapalı tutulacak cihazlar için farklı alanlar gerekebilir. Açık raf, cam bölüm ve kapaklı alt dolap seçeneklerini neyi kullanacağınız üzerinden karşılaştırın. Aydınlatma ve elektrik bağlantıları ayrı iş kapsamlarıdır.'],
 ['Duvar ve geçiş alanı belirleyicidir.','Duvarın eni, kapı açılımı, süpürgelik ve yakın mobilyalar yerleşimi etkiler. Duvara sabitleme uygunluğu ve taşıma ihtiyacı yerinde kontrol edilmelidir. Bir arşiv fotoğrafı duvarınızın taşıma kapasitesini kanıtlamaz.']
 ],preparation:['TV marka/modeli, ayak veya askı tercihi.','Ses sistemi ve diğer cihazların listesi.','Duvarın tamamı ve bağlantı noktalarının fotoğrafı.','Saklanacak eşyalar ve açıkta sergilenecek parçalar.'],project:'isikli-tv-unitesi',note:'Üretim ölçüsü, duvar bağlantısı ve cihaz gereklilikleri ayrıca kontrol edilir. Görseldeki TV, dekor ve elektrik işleri kendiliğinden teklif kapsamına girmez.'}
};
