import { createElement, Fragment, Component } from 'react';
import { products } from '../lib/data';
import { money, lineTotal, downloadText, validateQuoteStep } from '../lib/domain';
import { image, Icon, Link, ButtonLink, Eyebrow, PageIntro, ProductCard, Callout, type PageProps } from '../components/ui';
export function Cart(a: PageProps) { const total = a.cart.reduce((s, l) => s + lineTotal(l.unitMinor, l.quantity), 0); return <><PageIntro kicker="SEPET / YEREL ÖNİZLEME" title={<>Seçtiğiniz<br /><em>parçalar.</em></>} desc="Bu sepet yalnız tasarım akışını denemek içindir. Fiyatlar örnektir; canlı sipariş ve ödeme oluşturulmaz."/><section className="wrap cart-layout">{!a.cart.length ? <div className="empty-state"><Icon name="bag" size={42}/><h2>Bir parça ile başlayalım.</h2><p>Örnek satın alma akışını Vera veya Kavis üzerinden deneyebilirsiniz.</p><ButtonLink to="/urunler" navigate={a.navigate}>Koleksiyonu keşfet</ButtonLink></div> : <><div className="cart-lines">{a.cart.map(l => { const p = products.find(x => x.id === l.id)!; return <article className="cart-line" key={l.key}><Link to={'/urun/' + p.id} navigate={a.navigate}><img src={image(p.image)} alt={p.name + ' konsepti'}/></Link><div><span className="label">{p.categoryLabel}</span><h2><Link to={'/urun/' + p.id} navigate={a.navigate}>{p.name}</Link></h2><p>{l.material} · {l.size}</p><span className="small">Örnek birim fiyat: {money(l.unitMinor)}</span><div className="quantity"><button aria-label={p.name + ' adedini azalt'} disabled={l.quantity === 1} onClick={() => a.changeCart(l.key, l.quantity - 1)}><Icon name="minus" size={15}/></button><span aria-label="Adet">{l.quantity}</span><button aria-label={p.name + ' adedini artır'} disabled={l.quantity === 100} onClick={() => a.changeCart(l.key, l.quantity + 1)}><Icon name="plus" size={15}/></button></div></div><div className="line-price"><strong>{money(lineTotal(l.unitMinor, l.quantity))}</strong><button onClick={() => a.removeCart(l.key)} aria-label={p.name + ' ürününü sepetten çıkar'}>Kaldır</button></div></article>; })}</div><aside className="order-summary"><Eyebrow>ÖRNEK SİPARİŞ ÖZETİ</Eyebrow><h2>Güzel bir<br /><em>başlangıç.</em></h2><dl><div><dt>Ürün tutarı</dt><dd>{money(total)}</dd></div><div><dt>Teslimat / kurulum</dt><dd>Henüz belirlenmedi</dd></div><div><dt>Vergi görünümü</dt><dd>Canlı katalogda doğrulanacak</dd></div></dl><div className="order-total"><span>Örnek ürün toplamı</span><strong>{money(total)}</strong></div><ButtonLink to="/odeme" navigate={a.navigate}>Sipariş akışını incele</ButtonLink><p className="small">Bu tutar satış teklifi değildir. Ödeme alınmaz, stok ayrılmaz.</p></aside></>}</section><section className="wrap note-box"><Icon name="info"/><p>Özel ölçü gerektiren ürünler sepete eklenmez. Denge ve Rota için önce teklif stüdyosundan ihtiyacınızı paylaşabilirsiniz.</p></section></>; }
export function Saved(a: PageProps) { return <><PageIntro kicker="ÇALIŞMA DOSYANIZ / BU CİHAZDA" title={<>Aklınızda kalan<br /><em>parçalar.</em></>} desc="Kaydettikleriniz yalnız bu tarayıcıda tutulur. Bu alan bir müşteri hesabı veya bulut yedeği değildir."/><section className="wrap section">{a.favorites.length ? <div className="catalog-grid">{products.filter(p => a.favorites.includes(p.id)).map(p => <ProductCard key={p.id} product={p} actions={a}/>)}</div> : <div className="empty-state"><Icon name="heart" size={38}/><h2>Henüz bir parça kaydetmediniz.</h2><p>Koleksiyondaki kalp simgesiyle sevdiğiniz tasarımları burada bir araya getirebilirsiniz.</p><ButtonLink to="/urunler" navigate={a.navigate}>Koleksiyona göz at</ButtonLink></div>}<div className="note-box"><Icon name="info"/><p>Bu sürümde gerçek üyelik, parola ve kişisel sipariş erişimi yoktur. Kaydedilenler ve örnek sepet en fazla 30 gün bu cihazda tutulur.</p></div></section><Callout navigate={a.navigate}/></>; }
export class Checkout extends Component<PageProps, {
    name: string;
    email: string;
    phone: string;
    delivery: string;
    errors: Record<string, string>;
    done: boolean;
}> {
    state = { name: '', email: '', phone: '', delivery: 'Teslimatı birlikte planlayalım', errors: {}, done: false };
    render() { const a = this.props, total = a.cart.reduce((s, l) => s + lineTotal(l.unitMinor, l.quantity), 0); return <><PageIntro kicker="SİPARİŞ / ÖDEME BAĞLANTISI KAPALI" title={<>Sonraki adım,<br /><em>birlikte netleşir.</em></>} desc="Ödeme kuruluşu bağlı olmadığı için kart bilgisi istemiyor ve tahsilat yapmıyoruz."/><section className="wrap checkout-layout">{!a.cart.length ? <div className="empty-state"><h2>Önce bir parça seçin.</h2><ButtonLink to="/urunler" navigate={a.navigate}>Koleksiyona dön</ButtonLink></div> : this.state.done ? <div className="empty-state"><span className="success-mark"><Icon name="check"/></span><h2>Örnek dosyanız hazır.</h2><p>Cihazınıza indirilmek üzere hazırlandı. <strong>Sipariş verilmedi, ödeme alınmadı.</strong></p><ButtonLink to="/sepet" navigate={a.navigate}>Sepete dön</ButtonLink></div> : <><form className="checkout-form" noValidate onSubmit={e => { e.preventDefault(); const errors = validateQuoteStep(5, this.state); if (Object.keys(errors).length) {
        this.setState({ errors });
        return;
    } const text = ['ELİF TASARIM — ÖRNEK SİPARİŞ DOSYASI', 'Canlı sipariş değildir. Ödeme alınmadı. Stok ayrılmadı.', '', ...a.cart.map(l => `${products.find(p => p.id === l.id)!.name} / ${l.material} / ${l.size} / ${l.quantity} adet / örnek tutar ${money(l.unitMinor * l.quantity)}`), '', `Örnek ürün toplamı: ${money(total)}`, `Örnek isim: ${this.state.name}`, `Örnek e-posta: ${this.state.email}`, `Teslim yaklaşımı: ${this.state.delivery}`].join('\n'); downloadText('Elif_Ornek_Siparis.txt', text); this.setState({ done: true }); }}><Eyebrow>01 / İLETİŞİM BİLGİSİ</Eyebrow><h2>Örnek bilgilerinizi girin.</h2><p className="small muted">Bu alanları test verisiyle doldurun. Bilgiler sunucuya gönderilmez.</p>{(['name', 'email'] as const).map((k, i) => <label key={k} className="form-field">{i ? 'E-posta' : 'Adınız'}<input type={i ? 'email' : 'text'} autoComplete="off" value={this.state[k]} maxLength={160} onInput={e => this.setState({ ...this.state, [k]: e.currentTarget.value, errors: {} })}/>{(this.state.errors as any)[k] && <small className="field-error">{(this.state.errors as any)[k]}</small>}</label>)}<label className="form-field spaced">Teslim tercihi<select value={this.state.delivery} onChange={e => this.setState({ delivery: e.currentTarget.value })}><option value="Teslimatı birlikte planlayalım">Teslimatı birlikte planlayalım</option><option value="Atölyeden teslim alma">Atölyeden teslim alma</option><option value="Teslim ve kurulum görüşmesi">Teslim ve kurulum görüşmesi</option></select></label><div className="payment-unavailable"><Icon name="info" size={26}/><div><h3>Canlı ödeme bu sürümde kapalı.</h3><p>iyzico / PayTR hesabı, gerçek fiyatlar, satıcı bilgileri ve sunucu entegrasyonu doğrulanmadan tahsilat açılmaz.</p></div></div><button className="button" type="submit">Örnek sipariş dosyasını hazırla <Icon name="download"/></button></form><aside className="order-summary"><Eyebrow>ÖRNEK SEÇİMİNİZ</Eyebrow>{a.cart.map(l => <div className="summary-product" key={l.key}><img src={image(products.find(p => p.id === l.id)!.image)} alt=""/><span><strong>{products.find(p => p.id === l.id)!.name}</strong><small>{l.quantity} adet · {l.material}</small></span><b>{money(l.unitMinor * l.quantity)}</b></div>)}<div className="order-total"><span>Örnek ürün toplamı</span><strong>{money(total)}</strong></div><p className="small">Teslimat ve gerçek satış koşulları belirlenmedi. Bu bir ödeme ekranı simülasyonu değil; güvenli bir sipariş hazırlık örneğidir.</p></aside></>}</section></>; }
}
export class Contact extends Component<PageProps, {
    name: string;
    email: string;
    note: string;
    error: string;
}> {
    state = { name: '', email: '', note: '', error: '' };
    render() { const a = this.props; return <><PageIntro kicker="İLETİŞİM / DOĞRUDAN ATÖLYEYE" title={<>Bir fikir.<br /><em>Bir konuşma.</em></>} desc="Ne düşündüğünüzü duymak isteriz. Hazır bir çiziminiz olmasa da başlayabiliriz."/><section className="wrap contact-layout"><div><Eyebrow>ELİF TASARIM</Eyebrow><h2>İstanbul’daki<br /><em>atölyemizden.</em></h2><p>El yapımı mobilya ve özel üretim üzerine bir aile atölyesi.</p><dl className="contact-details"><div><dt>Konum</dt><dd>İstanbul, Türkiye</dd></div><div><dt>Telefon ve açık adres</dt><dd>İşletme tarafından doğrulandığında eklenecek.</dd></div><div><dt>Görüşme ve teslimat</dt><dd>İşin kapsamına göre birlikte planlanır.</dd></div></dl><div className="contact-studio"><Icon name="ruler" size={30}/><h3>Ölçülü bir başlangıç için</h3><p>İhtiyaç, malzeme ve görselleri bir araya getiren özel stüdyomuzu kullanabilirsiniz.</p><ButtonLink to="/teklif-al" navigate={a.navigate}>Özel ölçü stüdyosu</ButtonLink></div></div><form className="contact-form" noValidate onSubmit={e => { e.preventDefault(); if (this.state.name.trim().length < 2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.state.email) || this.state.note.trim().length < 5) {
        this.setState({ error: 'Adınızı, geçerli bir e-postayı ve en az 5 karakterlik notunuzu yazın.' });
        return;
    } downloadText('Elif_Iletisim_Notu.txt', `ELİF TASARIM — İLETİŞİM NOTU\nBu not gönderilmedi.\n\nİsim: ${this.state.name}\nE-posta: ${this.state.email}\n\n${this.state.note}`); a.notify('İletişim notu indirmeniz için hazırlandı. Atölyeye gönderilmedi.'); }}><Eyebrow>İLETİŞİM NOTU / ÖNİZLEME</Eyebrow><h2>Ne düşünüyorsunuz?</h2><p className="small muted">Canlı iletişim kanalı bağlı değil. Notunuzu bir metin dosyası olarak hazırlayabilirsiniz.</p><label className="form-field">Adınız<input maxLength={100} value={this.state.name} onInput={e => this.setState({ name: e.currentTarget.value })}/></label><label className="form-field">E-posta<input type="email" maxLength={160} value={this.state.email} onInput={e => this.setState({ email: e.currentTarget.value })}/></label><label className="form-field">Notunuz<textarea rows={5} maxLength={2000} value={this.state.note} onInput={e => this.setState({ note: e.currentTarget.value })}/></label>{this.state.error && <p className="field-error" role="alert">{this.state.error}</p>}<button className="button" type="submit">İletişim notunu indir <Icon name="download"/></button></form></section></>; }
}
