import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Accordion,Photo,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,featuredWorks,workCategories,concepts} from '../lib/portfolio';
import {ConceptCard} from './Portfolio';
import {defaultDesk,deskQuery,type Desk} from '../lib/desk';
const scenes=[{image:'concept-hero',caption:'Bir masanın etrafında.',label:'Yaşam',kind:'concept'},{image:'r13',caption:'Atölyeden, evin kalbine.',label:'Mutfak',kind:'work'},{image:'r07',caption:'Yunus Usta’nın arşivinden.',label:'Kahve',kind:'work'}];
export class Home extends Component<PageProps,{scene:number;desk:Desk;chapter:number}>{
 state={scene:0,desk:{...defaultDesk},chapter:0};
 render(){const a=this.props,s=this.state,scene=scenes[s.scene];return <div className="v6-home">
 <section className="v6-hero" aria-label="Elif Tasarım açılış seçkisi"><div className="v6-hero-scene" key={scene.image}><VImage asset={scene.image} alt={scene.caption+(scene.kind==='concept'?' Konsept mobilya sahnesi.':' Atölyeden paylaşılan çalışma fotoğrafı.')} eager full sizes="100vw"/></div><div className="v6-hero-shade"/><div className="wrap v6-hero-inner"><Eyebrow>İSTANBUL / EL YAPIMI MOBİLYA ATÖLYESİ</Eyebrow><h1>Zamana değer<br/>{" "}<em>katan mobilyalar.</em></h1><p>İstanbul’daki aile atölyemizden, yaşam alanınıza.<br/>Ölçünüze ve ihtiyacınıza göre, doğrudan ustasıyla.</p><div className="v6-hero-actions"><ButtonLink to="/projeler" navigate={a.navigate}>Bitirdiğimiz işleri keşfedin</ButtonLink><TextLink to="/modelini-getir" navigate={a.navigate} light>Kendi modelinizi getirin</TextLink></div></div><div className="wrap v6-hero-bottom"><div className="v6-scene-controls" role="group" aria-label="Açılış sahneleri">{scenes.map((sc,i)=><button key={sc.image} onClick={()=>this.setState({scene:i})} aria-pressed={s.scene===i} aria-label={sc.label+' sahnesi'}><span>{String(i+1).padStart(2,'0')}</span><i/><span className="scene-word">{sc.label}</span></button>)}</div><span className="v6-hero-caption">{scene.caption}</span><button className="hero-down" aria-label="Bitirdiğimiz işlere kaydır" onClick={()=>document.getElementById('bitirdigimiz-isler')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant' as ScrollBehavior:'smooth'})}><Icon name="down"/></button></div><span className="hero-source">{scene.kind==='concept'?'KONSEPT MODEL':'GERÇEK ÇALIŞMA FOTOĞRAFI / ATÖLYE ARŞİVİ'}</span></section>
 <section id="bitirdigimiz-isler" className="wrap v6-section home-works"><div className="v6-heading"><div><Eyebrow>01 / ATÖLYEDEN YAŞAMA</Eyebrow><h2>Bitirdiğimiz işlerden<br/><em>seçkiler.</em></h2></div><div><p>Gerçek mekânlar, gerçek çalışmalar.<br/>Yunus Usta'nın paylaştığı uygulama arşivinden.</p><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div></div><div className="work-grid">{featuredWorks.map((id,i)=><WorkCard key={id} work={works.find(w=>w.id===id)!} actions={a} featured index={i}/>)}</div></section>
 <nav className="wrap v9-category-ribbon" aria-label="Yaşam alanına göre keşfet">{workCategories.map(c=><Link key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate}><div><VImage asset={c.image} alt={c.name+' konsept seçkisi'} sizes="180px"/><span>Konsept</span></div><strong>{c.name}</strong><Icon name="diagonal" size={15}/></Link>)}</nav>
 <section className="home-yunus"><div className="home-yunus-image"><VImage asset="work-joinery" alt="Ahşap kamelya çalışmasından gerçek çatı ve birleşim ayrıntıları" sizes="(max-width: 800px) 100vw, 60vw"/><span>UYGULAMA ARŞİVİNDEN BİR AYRINTI</span></div><div className="home-yunus-copy"><Eyebrow>YUNUS USTA'NIN ELİNDEN ÇIKANLAR</Eyebrow><h2>Bir meslekten fazlası.<br/><em>Bir aile mirası.</em></h2><p>Babasından öğrendiği marangozluk, Yunus Usta'nın elinde bugünün yaşam alanlarına uyarlanıyor. Her iş, bir ihtiyacı dinlemekle başlıyor.</p><p>Ölçüyü birlikte düşünmek, malzemeyi doğru seçmek ve atölyedeki emeği yerinde uygulamayla tamamlamak. Bizim için işin özü bu.</p><TextLink to="/hakkimizda" navigate={a.navigate} light>Hikâyemizi keşfedin</TextLink><div className="yunus-notes"><span>Aile atölyesi</span><span>Ölçüye özel</span><span>Üretim & uygulama</span></div></div></section>
 <section className="v6-process"><div className="wrap"><div className="v6-heading"><div><Eyebrow>03 / FİKİRDEN UYGULAMAYA</Eyebrow><h2>Birlikte <em>nasıl ilerleriz?</em></h2></div><p>Acele bir seçim değil, iyi düşünülmüş bir parça. Her aşamada ihtiyacınızı ve kullanımınızı merkeze alırız.</p></div><div className="process-steps">{[['Fikrinizi dinleriz.','Bir Pinterest bağlantısı, fotoğraf veya kendi çiziminiz. Önce nasıl kullanacağınızı konuşuruz.'],['Ölçüyü netleştiririz.','Malzeme, renk, donanım ve alanın ölçülerini birlikte değerlendiririz. Teklif bu ayrıntılarla şekillenir.'],['Atölyede şekillenir.','Üzerinde anlaşılan tasarım, ölçü ve malzemeyle üretim planlanır.'],['Yerini bulur.','Teslim ve gerekiyorsa yerinde uygulama, projenin koşullarına göre birlikte düzenlenir.']].map(([title,text],i)=><article key={title}><span className="process-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="wrap v11-studio-invitation" id="uc-boyutlu-studyo"><div><Eyebrow>DEVİR 01 / İNTERAKTİF KONSEPT STÜDYOSU</Eyebrow><h2>Bir masa.<br/><em>Size göre yeni bir düzen.</em></h2><p>Yüksekliği ve ölçüleri değiştirin. Çekmeceleri, döner yan yüzeyi ve çift taraflı kitaplıklarla çalışma alanınızı keşfedin.</p><ButtonLink to="/tasarim-masasi" navigate={a.navigate}>3D stüdyoyu keşfet</ButtonLink><TextLink to="/ilham-modelleri" navigate={a.navigate}>Diğer ilham modelleri</TextLink><small>Görsel bir konsepttir. İmalat ve mekanizma uygunluğu atölye görüşmesinde netleşir.</small></div><Link className="v11-studio-poster" to="/tasarim-masasi" navigate={a.navigate} aria-label="Devir 01. Çift raflı 3D tasarım stüdyosunu aç"><Photo name="atelier-poster-v9.webp" alt="Devir 01 modelinin iki kitaplıklı çalışma ortamı, gerçek Three.js sahnesinden konsept görünümü" ratio="3/2"/><span className="v11-poster-action"><Icon name="grid"/>Keşfet. Döndür. Birlikte düşün.</span><SourceTag kind="concept"/></Link></section>
 <section className="v6-final-cta"><div className="wrap"><Eyebrow>SİZİN FİKRİNİZ. BİZİM USTALIĞIMIZ.</Eyebrow><h2>Aklınızdaki modeli gönderin.<br/><em>Birlikte yorumlayalım.</em></h2><ButtonLink to="/modelini-getir" navigate={a.navigate}>Fikrimi paylaşayım</ButtonLink><p>Bir fotoğraf, bir bağlantı ya da yalnızca bir fikir.</p><TextLink to="/iletisim" navigate={a.navigate} light>Doğrudan Yunus Usta ile görüşün</TextLink></div></section>
 </div>}
}
