import {ScopeNotes,CategoryDecision,categorySupport} from './V7Pages';
import {PinterestPreview} from '../components/PinterestPreview';
import {pinLookup} from '../lib/pinterest';
import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Dialog,Accordion,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,workCategories,concepts,pinterestReferences,categoryName,modelHref,type Work} from '../lib/portfolio';
import {searchKey,publicHref} from '../lib/domain';
export class Projects extends Component<PageProps&{query?:string},{category:string;search:string;stage:string}>{
 constructor(p:any){super(p);const q=new URLSearchParams(p.query||'');this.state={category:workCategories.some(c=>c.id===q.get('alan'))?q.get('alan')!:'all',search:q.get('ara')||'',stage:q.get('durum')==='process'?'process':'work'}}
 update=(key:string,value:string)=>this.setState({[key]:value} as any,()=>{const s=this.state,q=new URLSearchParams();if(s.category!=='all')q.set('alan',s.category);if(s.search)q.set('ara',s.search);if(s.stage!=='work')q.set('durum',s.stage);history.replaceState({},'',publicHref('/projeler'+(q.size?'?'+q:'')))});
 render(){const a=this.props,s=this.state,list=works.filter(w=>(s.category==='all'||w.category===s.category)&&w.status===s.stage&&searchKey(w.title+' '+w.subtitle+' '+categoryName(w.category)).includes(searchKey(s.search)));return <>
 <header className="v6-page-head wrap"><Eyebrow>ELİF / UYGULAMA ARŞİVİ</Eyebrow><div><h1>Söz değil.<br/><em>İşin kendisi.</em></h1><p>Atölyeden çıkıp yaşam alanlarına yerleşen çalışmalar. Fotoğrafların arkasında, ölçüsünden son ayrıntısına kadar düşünülmüş bir emek var.</p></div></header>
 <section className="wrap portfolio-section"><div className="portfolio-toolbar"><div className="view-segments" role="group" aria-label="Proje durumu"><button onClick={()=>this.update('stage','work')} aria-pressed={s.stage==='work'}>Bitirdiğimiz İşler</button><button onClick={()=>this.update('stage','process')} aria-pressed={s.stage==='process'}>Uygulama Aşamaları</button></div><label className="portfolio-search"><Icon name="search"/><input type="search" value={s.search} maxLength={100} onInput={e=>this.update('search',e.currentTarget.value)} placeholder="Bir çalışma arayın" aria-label="Projelerde ara"/></label></div>
 <div className="filter-chips" role="group" aria-label="Proje kategorisi">{[{id:'all',name:'Tümü'},...workCategories].map(c=><button key={c.id} onClick={()=>this.update('category',c.id)} aria-pressed={s.category===c.id}>{c.name}</button>)}</div>
 <div className="result-line" aria-live="polite"><span>{list.length} çalışma</span><span>Gerçek fotoğraflar, atölyenin paylaştığı arşivden.</span></div>
 {list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="v6-empty"><Icon name="search" size={34}/><h2>Bu seçimde henüz bir çalışma yok.</h2><p>Kategorinin ilham fikirlerini inceleyebilir veya kendi modelinizle başlayabilirsiniz.</p><button className="button button-outline" onClick={()=>this.setState({category:'all',search:'',stage:'work'},()=>history.replaceState({},'',publicHref('/projeler')))}>Filtreleri temizle <Icon/></button><TextLink to="/modelini-getir" navigate={a.navigate}>Kendi modelimle başlayayım</TextLink></div>}
 </section><ModelCallout navigate={a.navigate} compact/></>}
}
export class WorkDetail extends Component<PageProps&{work:Work},{photo:number;zoom:boolean}>{
 state={photo:0,zoom:false};move=(delta:number)=>this.setState(s=>({photo:(s.photo+delta+this.props.work.images.length)%this.props.work.images.length}));
 render(){const a=this.props,w=a.work,others=works.filter(p=>p.category===w.category&&p.id!==w.id&&p.status==='work').slice(0,3);return <>
 <div className="wrap v6-crumb"><Link to="/projeler" navigate={a.navigate}>Bitirdiğimiz İşler</Link><span>/</span><Link to={'/kategoriler/'+w.category} navigate={a.navigate}>{categoryName(w.category)}</Link></div>
 <section className="wrap work-detail"><div className="work-detail-media"><button className="work-main-photo" onClick={()=>this.setState({zoom:true})} aria-label="Proje fotoğrafını büyüt"><VImage asset={w.images[this.state.photo]} alt={w.subtitle} eager full/><span><Icon name="plus"/>Fotoğrafı incele</span></button>{w.images.length>1&&<div className="work-thumbnails">{w.images.map((im,i)=><button key={im} onClick={()=>this.setState({photo:i})} aria-label={'Fotoğraf '+(i+1)} aria-pressed={i===this.state.photo}><VImage asset={im} alt="" sizes="100px"/></button>)}</div>}<p className="photo-credit">Atölyenin paylaştığı özgün fotoğraf. Konsept görselle değiştirilmedi.</p></div>
 <div className="work-detail-copy"><SourceTag kind={w.status}/><Eyebrow>{categoryName(w.category)}</Eyebrow><h1>{w.title}</h1><p className="work-lead">{w.description}</p><dl className="work-facts"><div><dt>Çalışma</dt><dd>{w.subtitle}</dd></div><div><dt>Yaklaşım</dt><dd>Ölçü ve ihtiyaca göre değerlendirme</dd></div><div><dt>Malzeme & ölçü</dt><dd>Yeni teklifinizde birlikte netleştirilir</dd></div></dl><div className="work-features">{w.features.map(f=><span key={f}><Icon name="check" size={16}/>{f}</span>)}</div><ButtonLink to={modelHref('',w.category,w.subtitle+' benzeri bir çalışma istiyorum.')} navigate={a.navigate}>Benzerini birlikte düşünelim</ButtonLink><p className="fineprint">Her mekân farklıdır. Fotoğraf, yeni projeniz için kesin ölçü, malzeme, fiyat veya aynı sonucu elde etme taahhüdü değildir.</p></div>
 </section><div className="wrap"><ScopeNotes category={w.category}/></div>{others.length>0&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>AYNI ALANDAN</Eyebrow><h2>Biraz daha <em>keşfedin.</em></h2></div><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div><div className="work-grid">{others.map((p,i)=><WorkCard key={p.id} work={p} actions={a} index={i}/>)}</div></section>}
 <ModelCallout navigate={a.navigate} compact/>
 {this.state.zoom&&<Dialog title={w.subtitle} onClose={()=>this.setState({zoom:false})}><div className="v6-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')this.move(1);if(e.key==='ArrowLeft')this.move(-1)}}><VImage asset={w.images[this.state.photo]} alt={w.subtitle+' büyük görünüm'} eager full sizes="95vw"/>{w.images.length>1&&<div><button className="icon-button" aria-label="Önceki fotoğraf" onClick={()=>this.move(-1)}><span className="reverse-arrow"><Icon/></span></button><span>{this.state.photo+1} / {w.images.length}</span><button className="icon-button" aria-label="Sonraki fotoğraf" onClick={()=>this.move(1)}><Icon/></button></div>}<p>Özgün uygulama fotoğrafı</p></div></Dialog>}
 </>}
}
export function ConceptCard({c,navigate,actions}:{c:typeof concepts[number];navigate:(p:string)=>void;actions?:PageProps}){return <article className="concept-card"><Link to={modelHref('',c.category,c.subtitle+' üzerine konuşmak istiyorum.')} navigate={navigate} className="concept-image"><VImage asset={c.image} alt={c.subtitle+', yapay zekâ ile üretilmiş temsili tasarım'} sizes="(max-width: 680px) 90vw, 45vw"/><SourceTag kind="concept"/><span className="concept-open"><Icon name="diagonal"/></span></Link><div className="concept-caption"><span>{categoryName(c.category)}</span><h3>{c.title}</h3><TextLink to={modelHref('',c.category,c.subtitle+' üzerine konuşmak istiyorum.')} navigate={navigate}>Bu fikirle başlayalım</TextLink>{actions&&<button className="v7-save-text" aria-pressed={actions.favorites.includes('concept:'+c.id)} onClick={()=>actions.favorite('concept:'+c.id)}><Icon name="heart" size={18}/>{actions.favorites.includes('concept:'+c.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button>}</div></article>}
export function Categories(a:PageProps&{slug?:string}){
 const cat=workCategories.find(c=>c.id===a.slug);
 if(cat){const list=works.filter(w=>w.category===cat.id&&w.status==='work'),ideas=concepts.filter(c=>c.category===cat.id);return <>
 <section className="category-hero"><VImage asset={categorySupport[cat.id]?.asset||cat.image} alt={cat.name+(categorySupport[cat.id]?' atölye fotoğrafı':' için temsili tasarım sahnesi')} eager sizes="100vw"/><div className="category-shade"/><div className="wrap"><Link className="v6-backlink" to="/kategoriler" navigate={a.navigate}>Kategoriler <Icon size={16}/></Link><Eyebrow>ÖLÇÜNÜZE, ALANINIZA, SİZE</Eyebrow><h1>{cat.name}</h1><p>{cat.line}</p></div><SourceTag kind={categorySupport[cat.id]?'work':'concept'}/></section>
 <CategoryDecision category={cat.id} navigate={a.navigate}/><section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>ATÖLYEDEN</Eyebrow><h2>{cat.short} için<br/><em>düşündüklerimiz.</em></h2></div><p>{cat.detail}</p></div>{list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="category-no-work"><p>Bu kategoride paylaşılmış bir bitmiş iş fotoğrafı henüz yok. Aşağıdaki konseptleri başlangıç noktası olarak inceleyebilirsiniz.</p><TextLink to={modelHref('',cat.id)} navigate={a.navigate}>Kendi fikrimle başlayayım</TextLink></div>}</section>
 {ideas.length>0&&<section className="concept-band"><div className="wrap"><div className="v6-heading"><div><Eyebrow>TEMSİLİ TASARIM SEÇKİSİ</Eyebrow><h2>Bir başlangıç <em>fikri.</em></h2></div><p>Bu görseller konsept modeldir. Atölyenin tamamladığı işler değildir. Üretilebilirlik ve ayrıntılar birlikte değerlendirilir.</p></div><div className="concept-grid">{ideas.map(c=><ConceptCard key={c.id} c={c} navigate={a.navigate} actions={a}/>)}</div></div></section>}<ModelCallout navigate={a.navigate}/></>}
 return <><header className="v6-page-head wrap"><Eyebrow>ELİF / YAŞAM ALANLARI</Eyebrow><div><h1>Evin her köşesine.<br/><em>Size göre.</em></h1><p>Mutfaktan bir fincan kahveye ayrılan köşeye. Hazır bir ölçüye sığmak yerine, alanınızdan ve ihtiyacınızdan başlayalım.</p></div></header><section className="wrap v6-section categories-index"><div className="category-grid">{workCategories.map((c,i)=><Link key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate} className="category-tile"><div><VImage asset={c.image} alt={c.name+' konsepti'} sizes="(max-width: 680px) 90vw, 30vw"/><SourceTag kind="concept"/></div><span className="category-number">{String(i+1).padStart(2,'0')}</span><h2>{c.name}</h2><p>{c.line}</p><Icon name="diagonal"/></Link>)}<Link to="/ilham-modelleri" navigate={a.navigate} className="category-tile category-inspiration"><span className="category-number">09</span><Eyebrow>SEÇKİLER VE SİZİN FİKİRLERİNİZ</Eyebrow><h2>İlham<br/><em>Modelleri</em></h2><p>Kendi modelinizi getirin, birlikte yorumlayalım.</p><Icon name="diagonal"/></Link></div></section><ModelCallout navigate={a.navigate}/></>
}
export class Inspiration extends Component<PageProps,{category:string;group:string}>{state={category:'all',group:'atelier'};
 render(){const a=this.props,items=concepts.filter(c=>this.state.category==='all'||c.category===this.state.category);return <>
 <header className="v6-page-head wrap inspiration-heading"><Eyebrow>ELİF / İLHAM DEFTERİ</Eyebrow><div><h1>Bir yerde gördünüz.<br/><em>Aklınızda kaldı.</em></h1><p>Bir Pinterest kaydı, bir eskiz, küçük bir ayrıntı. O fikri mekânınızın ölçüsüne ve sizin kullanımınıza göre birlikte düşünelim.</p></div><ButtonLink to="/modelini-getir" navigate={a.navigate}>Kendi modelimi getireyim</ButtonLink></header>
 <section className="wrap v6-section inspiration-concepts"><div className="v6-heading"><div><Eyebrow>BİZİM KONSEPT SEÇKİMİZ</Eyebrow><h2>Biraz <em>ilham.</em></h2></div><p>Yapay zekâ ile hazırlanmış tasarım fikirleri. Bitmiş proje veya teknik üretim onayı değildir.</p></div><div className="filter-chips" role="group" aria-label="İlham kategorisi">{[{id:'all',name:'Tümü'},...workCategories].map(c=><button key={c.id} aria-pressed={c.id===this.state.category} onClick={()=>this.setState({category:c.id})}>{c.name}</button>)}</div><div className="concept-grid">{items.map(c=><ConceptCard c={c} key={c.id} navigate={a.navigate} actions={a}/>)}</div></section>
 <section className="pinterest-section"><div className="wrap"><div className="v6-heading"><div><Eyebrow>KAYNAĞINDAN KEŞFEDİN</Eyebrow><h2>Pinterest'ten<br/><em>kaydettiğimiz fikirler.</em></h2></div><p>Ustanın paylaştığı modeller ve birlikte önerilenler. Kaynağı Pinterest'te açabilir, beğendiğiniz bağlantıyla kendi projenize başlayabilirsiniz.</p></div><div className="view-segments pin-segments" role="group" aria-label="Pinterest seçkisi"><button aria-pressed={this.state.group==='atelier'} onClick={()=>this.setState({group:'atelier'})}>Ustanın seçtikleri</button><button aria-pressed={this.state.group==='shared'} onClick={()=>this.setState({group:'shared'})}>Birlikte önerilenler</button></div><div className="pin-grid">{pinterestReferences.filter(p=>p.group===this.state.group).map(p=><article className="pin-card" key={p.id}><div className="pin-mark" aria-hidden="true">P</div><span className="eyebrow">DIŞ KAYNAK İLHAM BAĞLANTISI</span><h3>{pinLookup[p.id]?.label||p.title}</h3><p>{p.category==='vestiyer'?'Vestiyer için paylaşılan model.':'Paylaşılan tasarım referansı.'}</p><PinterestPreview pin={p.id}/><button className="v7-save-text" aria-label={(pinLookup[p.id]?.label||p.title)+' modelini kaydet'} aria-pressed={a.favorites.includes('pin:'+p.id)} onClick={()=>a.favorite('pin:'+p.id)}><Icon name="heart" size={18}/>{a.favorites.includes('pin:'+p.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button><div><a href={'https://pin.it/'+p.id} target="_blank" rel="noopener noreferrer" className="text-link">Pinterest'te incele <Icon name="diagonal" size={17}/></a><TextLink to={modelHref('https://pin.it/'+p.id,p.category)} navigate={a.navigate}>Bu modelle başlayalım</TextLink></div></article>)}</div><p className="pin-note">Pinterest içerikleri ilgili üreticilerine ve kaynaklarına aittir. Burada bitmiş Elif projesi olarak gösterilmez. Görsel yükleyicisi yalnız isteğinizle Pinterest bağlantısı kurar. Model paylaşım formuna bilgi aktarmaz. Pinterest kaynağı ayrı sekmede de açılabilir. Bağlantılar zaman içinde değişebilir veya giriş gerektirebilir.</p></div></section><ModelCallout navigate={a.navigate}/></>}
}
export function AboutAtelier(a:PageProps&{atelier?:boolean}){return <>
 <header className="v6-page-head wrap"><Eyebrow>{a.atelier?'ELİF / TEZGÂHTAN MEKÂNA':'ELİF / AİLEDEN GELEN USTALIK'}</Eyebrow><div><h1>{a.atelier?<>Bir fikrin<br/><em>şekil aldığı yer.</em></>:<>Bir meslekten fazlası.<br/><em>Bir aile mirası.</em></>}</h1><p>Yusuf Usta'nın babasından öğrendiği marangozluk, bugün farklı yaşam alanlarında devam ediyor. Hazır bir kalıp değil, ihtiyaca göre düşünülmüş bir çalışma.</p></div></header>
 <section className="atelier-documentary"><div className="atelier-documentary-image"><VImage asset="work-joinery" alt="Atölyenin ahşap kamelya uygulamasındaki çatı birleşimi ayrıntısı" eager sizes="70vw"/><SourceTag kind="process"/></div><div><Eyebrow>YUSUF USTA'NIN ELİNDEN ÇIKANLAR</Eyebrow><h2>Ölçüsünde dikkat.<br/><em>Ayrıntısında emek.</em></h2><p>Bir dolabın nasıl açıldığını, bir rafın ne taşıyacağını, bir köşenin günlük yaşamda nasıl kullanılacağını birlikte konuşarak başlarız.</p><p>Üretim ve uygulamayı aynı hikâyenin parçaları olarak görürüz. Doğru ölçü, malzeme seçimi ve özenli yerleşim, fikrin mekâna dönüşmesini sağlar.</p><TextLink to="/modelini-getir" navigate={a.navigate}>Fikrinizi birlikte düşünelim</TextLink></div></section>
 <section className="wrap atelier-values"><div><span>01</span><h2>Aile atölyesi.</h2><p>Nesilden nesile aktarılan meslek bilgisi. Doğrudan ustayla konuşarak ilerleyen bir süreç.</p></div><div><span>02</span><h2>Ölçüye özel.</h2><p>Alanınızın ihtiyacından başlar, kullanım biçiminize göre şekillendiririz.</p></div><div><span>03</span><h2>Üretim ve uygulama.</h2><p>Tezgâhta verilen emeği, yerinde uygulama ve montaj ayrıntılarıyla tamamlarız.</p></div></section>
 {a.atelier&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>UYGULAMA ARŞİVİ</Eyebrow><h2>İşin <em>içinden.</em></h2></div><p>Bu kareler uygulama aşamasını gösterir. Bitmiş projelerin tanıtım çekimleri olarak sunulmaz.</p></div><div className="work-grid">{works.filter(w=>w.status==='process').map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div></section>}
 <div className="wrap address-note"><Icon name="pin" size={28}/><div><h2>İstanbul'da, yeni atölyemize hazırlanıyoruz.</h2><p>Yeni atölye adresi netleştiğinde burada paylaşılacak. Ziyaret öncesinde Yusuf Usta ile görüşerek adresi ve uygunluğu teyit edin. Projenizi bir fikir ve yaklaşık ölçüyle hazırlamaya başlayabilirsiniz.</p></div></div><ModelCallout navigate={a.navigate}/></>}
