'use client';
import {createElement,Fragment,Component} from 'react';
import {Icon,Link,TextLink,ButtonLink,Eyebrow,Dialog,image,type PageProps} from './components/ui';
import {Home} from './pages/Home';
import {DesignDesk} from './pages/DesignDesk';
import {Bespoke,Journal,FAQ} from './pages/Editorial';
import {Projects,WorkDetail,Categories,Inspiration,AboutAtelier} from './pages/Portfolio';
import {BringModel} from './pages/BringModel';
import {SearchPage,SavedBoard,ContactV7,PrivacyV7,MaterialsV7} from './pages/V7Pages';
import {works,workCategories,mainNavigation,categoryName} from './lib/portfolio';
import {selectionEntries,validSelectionIds,searchEntries} from './lib/selections';
import {business,whatsappUrl,projectStore,attachmentStore,hasPrivateDraft,contextMessage} from './lib/project';
import {publicHref,searchKey} from './lib/domain';
import {pageTitle,pageDescription,pageShareImage,pageSchema} from './lib/routes';
import {VImage,SourceTag} from './components/PortfolioUI';
const aliases:Record<string,string>={'/urunler':'/kategoriler','/sepet':'/modelini-getir','/odeme':'/modelini-getir','/atolye-demolari':'/atolye','/atolyemiz':'/hakkimizda','/mekan-fikirleri':'/ilham-modelleri'};
function normalizePath(p:string){const [route,qs]=p.split('?');if(route.startsWith('/urun/'))return '/kategoriler';if(route.startsWith('/mekan-fikirleri/'))return '/ilham-modelleri';return aliases[route]?(aliases[route]+(qs?'?'+qs:'')):p;}
type State={path:string;scrolled:boolean;favorites:string[];remember:boolean;menu:boolean;search:boolean;searchQuery:string;info:boolean;toast:string};
export default class App extends Component<{initialPath?:string},State>{
 state:State={path:this.props.initialPath||'/',scrolled:false,favorites:[],remember:false,menu:false,search:false,searchQuery:'',info:false,toast:''};private timer:any;private entry=0;private entries=new Map<number,{path:string;y:number}>();private restoring:number|null=null;private oldRestoration:ScrollRestoration='auto';
 currentLocation=()=>{const w=window as any;const hash=window.location.hash;if(hash.startsWith('#/'))return normalizePath(hash.slice(1));if(w.__ELIF_PREVIEW__)return w.__ELIF_INITIAL__||'/';const base=w.__ELIF_BASE__||'',path=window.location.pathname;return normalizePath((base&&path.startsWith(base+'/')?path.slice(base.length):path).replace(/\/+$/,'')+window.location.search||'/')};
 saveEntry=()=>{if(!this.entry)return;const path=this.currentLocation(),route=this.state.path.split('?')[0];this.entries.set(this.entry,{path:path.split('?')[0]===route&&!['/modelini-getir','/teklif-al'].includes(route)?path:this.state.path,y:window.scrollY})};
 onLocation=()=>{const id=history.state?.elifEntry,found=typeof id==='number'?this.entries.get(id):undefined;if(id===this.entry&&found)return;this.entry=found?id:Date.now()+Math.random();this.restoring=found?.y??0;const path=found?.path||this.currentLocation();if(!found)this.entries.set(this.entry,{path,y:0});history.replaceState({...history.state,elifEntry:this.entry},'');this.setState({path,menu:false,search:false},this.afterRoute)};
 onScroll=()=>{this.saveEntry();const scrolled=window.scrollY>550;if(scrolled!==this.state.scrolled)this.setState({scrolled})};
 beforeUnload=(e:BeforeUnloadEvent)=>{if(hasPrivateDraft()){e.preventDefault();e.returnValue=''}};
 componentDidMount(){this.entry=Date.now()+Math.random();this.entries.set(this.entry,{path:this.currentLocation(),y:0});this.oldRestoration=history.scrollRestoration;history.scrollRestoration='manual';history.replaceState({...history.state,elifEntry:this.entry},'');let favorites:string[]=[],remember=false;try{const raw=JSON.parse(localStorage.getItem('elif-v7:selections')||'null');if(raw&&raw.expires>Date.now()){favorites=validSelectionIds(raw.ids);remember=true}else localStorage.removeItem('elif-v7:selections')}catch{}this.setState({path:this.currentLocation(),favorites,remember},this.afterRoute);window.addEventListener('hashchange',this.onLocation);window.addEventListener('popstate',this.onLocation);window.addEventListener('scroll',this.onScroll,{passive:true});window.addEventListener('beforeunload',this.beforeUnload);document.getElementById('static-content')?.remove();document.documentElement.dataset.appReady='true';}
 componentWillUnmount(){history.scrollRestoration=this.oldRestoration;window.removeEventListener('hashchange',this.onLocation);window.removeEventListener('popstate',this.onLocation);window.removeEventListener('scroll',this.onScroll);window.removeEventListener('beforeunload',this.beforeUnload);clearTimeout(this.timer)}
 afterRoute=()=>{
  const route=this.state.path.split('?')[0],site=((window as any).__ELIF_SITE_URL__||'https://onourimpram.github.io/elif-tasarim').replace(/\/$/,''),title=pageTitle(route),description=pageDescription(route);
  const setMeta=(key:string,value:string,property=false)=>{const attr=property?'property':'name';let node=document.querySelector<HTMLMetaElement>('meta['+attr+'="'+key+'"]');if(!node){node=document.createElement('meta');node.setAttribute(attr,key);document.head.appendChild(node)}node.content=value};
  document.title=title;setMeta('description',description);setMeta('og:title',title,true);setMeta('og:description',description,true);setMeta('og:url',site+(route==='/'?'/':route+'/'),true);setMeta('og:image',site+'/assets/'+pageShareImage(route),true);setMeta('og:site_name','Elif Tasarım',true);
  let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=site+(route==='/'?'/':route+'/');
  let schema=document.querySelector<HTMLScriptElement>('script[type="application/ld+json"]');if(!schema){schema=document.createElement('script');schema.type='application/ld+json';document.head.appendChild(schema)}schema.textContent=JSON.stringify(pageSchema(route,site));
  document.documentElement.dataset.page=route==='/tasarim-masasi'?'studio':route==='/modelini-getir'||route==='/teklif-al'?'project':'content';const restore=this.restoring;this.restoring=null;const y=restore??0;window.scrollTo({top:y,behavior:'instant' as ScrollBehavior});if(restore!==null)requestAnimationFrame(()=>requestAnimationFrame(()=>{window.scrollTo({top:y,behavior:'instant' as ScrollBehavior});this.onScroll()}));this.onScroll();if(!((window as any).__ELIF_PREVIEW__)){const p=new URLSearchParams(this.state.path.split('?')[1]||'');p.delete('ref');p.delete('fikir');history.replaceState({...history.state,elifEntry:this.entry},'',publicHref(route+(p.size?'?'+p.toString():'')));}
 };
 navigate=(path:string)=>{path=normalizePath(path);if(!path.startsWith('/')||path.startsWith('//'))path='/';if(path===this.state.path){this.setState({menu:false,search:false});return}this.saveEntry();this.entry=Date.now()+Math.random();this.entries.set(this.entry,{path,y:0});this.restoring=null;history.pushState({elifEntry:this.entry},'',publicHref(path));this.setState({path,menu:false,search:false,searchQuery:''},()=>{this.afterRoute();document.getElementById('main-content')?.focus({preventScroll:true})})};
 notify=(toast:string)=>{clearTimeout(this.timer);this.setState({toast});this.timer=setTimeout(()=>this.setState({toast:''}),5500)};
 persist=(ids:string[],remember:boolean)=>{try{if(remember)localStorage.setItem('elif-v7:selections',JSON.stringify({ids:validSelectionIds(ids),expires:Date.now()+30*86400000}));else localStorage.removeItem('elif-v7:selections');return true}catch{return false}};
 favorite=(id:string)=>{if(!selectionEntries.some(x=>x.id===id))return;const exists=this.state.favorites.includes(id);if(!exists&&this.state.favorites.length>=24){this.notify('İlham dosyanızda en fazla 24 seçim bulunabilir.');return}const favorites=exists?this.state.favorites.filter(x=>x!==id):[...this.state.favorites,id];const ok=this.persist(favorites,this.state.remember);this.setState({favorites,remember:ok?this.state.remember:false});this.notify(exists?'Seçiminiz ilham dosyanızdan çıkarıldı.':'İlham dosyanıza eklendi. '+(this.state.remember&&ok?'Bu cihazda 30 gün saklanır.':'Yalnız bu açık sekmede tutulur.'))};
 actions=():PageProps=>({navigate:this.navigate,notify:this.notify,favorites:this.state.favorites,favorite:this.favorite,cart:[],addCart:()=>{},changeCart:()=>{},removeCart:()=>{},openInfo:()=>this.setState({info:true})});
 renderPage(){const a=this.actions(),[p,qs='']=this.state.path.split('?');if(p==='/')return <Home {...a}/>;if(p==='/arama')return <SearchPage key={p} {...a} query={qs}/>;if(p==='/projeler')return <Projects key={this.state.path} {...a} query={qs}/>;if(p.startsWith('/proje/')){const w=works.find(x=>'/proje/'+x.id===p);if(w)return <WorkDetail key={w.id} {...a} work={w}/>;}if(p==='/kategoriler')return <Categories {...a}/>;if(p.startsWith('/kategoriler/')&&workCategories.some(c=>p==='/kategoriler/'+c.id))return <Categories {...a} slug={p.split('/').pop()}/>;if(p==='/ilham-modelleri')return <Inspiration key={this.state.path} {...a} query={qs}/>;if(p==='/modelini-getir'||p==='/teklif-al')return <BringModel key={this.state.path} {...a} query={qs} advanced={p==='/teklif-al'||new URLSearchParams(qs).get('detay')==='1'}/>;if(p==='/hakkimizda'||p==='/atolye')return <AboutAtelier {...a} atelier={p==='/atolye'}/>;if(p==='/tasarim-masasi')return <DesignDesk key={this.state.path} {...a} query={qs}/>;if(p==='/iletisim')return <ContactV7 {...a}/>;if(p==='/gizlilik')return <PrivacyV7 {...a}/>;if(p==='/malzemeler')return <MaterialsV7 {...a}/>;if(p==='/ozel-uretim')return <Bespoke {...a}/>;if(p==='/sikca-sorulan-sorular')return <FAQ {...a}/>;if(p==='/rehber'||p.startsWith('/rehber/'))return <Journal {...a} slug={p.split('/')[2]}/>;if(p==='/calisma-dosyam')return <SavedBoard {...a} remember={this.state.remember} setRemember={remember=>{const ok=this.persist(this.state.favorites,remember);this.setState({remember:remember&&ok});if(!ok)this.notify('Tarayıcı kaydetmeye izin vermedi. Seçimler bu açık sekmede korunur.')}}/>;return <section className="wrap empty-state missing-page"><Eyebrow>404 / BİR YOL AYRIMI</Eyebrow><h1>Bu sayfayı<br/><em>bulamadık.</em></h1><p>Çalışmaları keşfedebilir veya kendi fikrinizle başlayabilirsiniz.</p><ButtonLink to="/projeler" navigate={this.navigate}>Çalışmaları keşfet</ButtonLink></section>}
 render(){const s=this.state,a=this.actions(),nav=(to:string,label:string)=><Link key={to} to={to} navigate={this.navigate} aria-current={s.path.split('?')[0]===to?'page':undefined}>{label}</Link>;const results=searchEntries(s.searchQuery).slice(0,8),contactText=contextMessage(s.path,pageTitle(s.path.split('?')[0]).split('|')[0].trim(),(typeof window!=='undefined'&&(window as any).__ELIF_SITE_URL__)||undefined),studio=s.path.split('?')[0]==='/tasarim-masasi';return <>
 <a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>İçeriğe geç</a><div className="preview-bar"><span>V12 C+ / TASARIM ÖNİZLEMESİ <i/><span className="v9-preview-detail">Gerçek iş arşivi, doğrudan iletişim</span></span><button onClick={()=>this.setState({info:true})}>Bilgi ve tercihler <Icon name="info" size={16}/></button></div>
 <header className={'site-header v6-header '+(s.path==='/'?'home-header':'')+(s.scrolled&&!studio?' is-floating':'')}><div className="v6-header-main wrap"><button className="icon-button v6-menu-toggle" aria-label="Menüyü aç" onClick={()=>this.setState({menu:true})}><Icon name="menu" size={25}/></button><span className="v6-header-note">İSTANBUL<br/>ÖLÇÜYE ÖZEL ÜRETİM</span><Link to="/" navigate={this.navigate} className="brand" aria-label="Elif Tasarım ana sayfa"><img src={image('elif-amblem.png')} alt=""/><span>ELİF TASARIM<small>EL YAPIMI MOBİLYA ATÖLYESİ</small></span></Link><div className="v6-header-tools"><Link to="/tasarim-masasi" navigate={this.navigate} className="v9-studio-shortcut">3D Stüdyo <Icon name="grid" size={15}/></Link><button className="icon-button" aria-label="Sitede ara" onClick={()=>this.setState({search:true})}><Icon name="search"/></button><Link to="/calisma-dosyam" navigate={this.navigate} className="icon-button v6-saved" aria-label={'İlham dosyam, '+s.favorites.length+' seçim'}><Icon name="heart"/>{s.favorites.length>0&&<span className="v7-count">{s.favorites.length}</span>}</Link><a className="v7-header-phone" href={'tel:'+business.telephone} aria-label="Yunus Usta’yı telefonla ara"><Icon name="phone"/></a><Link to="/modelini-getir" navigate={this.navigate} className="v6-header-cta">Projenizi konuşalım <Icon size={16}/></Link></div></div><nav className="v6-header-nav wrap" aria-label="Ana gezinme">{mainNavigation.map(([p,label])=>nav(p,label))}</nav></header>
 <main id="main-content" tabIndex={-1} key={s.path.split('?')[0]}>{this.renderPage()}</main>
 <footer className="site-footer"><div className="wrap"><div className="footer-top"><div><Link to="/" navigate={this.navigate} className="brand footer-brand"><img src={image('elif-amblem-light.png')} alt=""/><span>ELİF TASARIM<small>EL YAPIMI MOBİLYA ATÖLYESİ</small></span></Link><p>Zamana değer<br/><em>katan mobilyalar.</em></p></div><div className="footer-column"><h2>Keşfedin</h2>{nav('/tasarim-masasi','3D Tasarım Stüdyosu')}{nav('/projeler','Çalışma arşivi')}{nav('/kategoriler','Kategoriler')}{nav('/ilham-modelleri','İlham modelleri')}{nav('/calisma-dosyam','İlham dosyanız')}{nav('/malzemeler','Malzeme ve bakım')}</div><div className="footer-column"><h2>Atölye</h2>{nav('/hakkimizda','Hikâyemiz')}{nav('/atolye','Atölye')}{nav('/ozel-uretim','Nasıl çalışıyoruz?')}{nav('/rehber','Atölye notları')}{nav('/gizlilik','Veri ve dış servisler')}</div><div className="footer-column footer-contact"><h2>Doğrudan Yunus Usta</h2><a className="v7-footer-phone" href={'tel:'+business.telephone}>{business.display}</a><a href={whatsappUrl(contactText)} target="_blank" rel="noopener noreferrer" className="text-link on-dark">WhatsApp'ta görüş <Icon name="diagonal"/></a><p>İstanbul, Türkiye.<br/>Yeni adresi ziyaret öncesinde teyit edin.</p>{nav('/iletisim','İletişim ayrıntıları')}</div></div><div className="footer-wordmark" aria-hidden="true">elif tasarım<span>ATÖLYE</span></div><div className="footer-bottom"><span>ELİF TASARIM · V12 C+ / 2026</span><div>{nav('/gizlilik','Gizlilik ve dış servisler')}<button onClick={()=>this.setState({info:true})}>Cihaz kayıtlarını yönet</button></div><span>Özenle düşünülür. Atölyede şekillenir.</span></div><p className="footer-disclosure">Atölye arşivi, uygulama aşaması, konsept model ve dış referanslar ayrı etiketlidir. Bu bir tasarım önizlemesidir. Sitede ödeme veya otomatik talep kaydı yoktur. WhatsApp mesajı harici uygulamada sizin tarafınızdan gönderilir.</p></div></footer>
 {s.menu&&<Dialog title="Elif Tasarım" onClose={()=>this.setState({menu:false})}><nav className="mobile-links" aria-label="Mobil menü">{[...mainNavigation,['/calisma-dosyam','İlham Dosyanız'],['/tasarim-masasi','Devir 01. 3D Stüdyo']].map(([p,label],i)=><Link key={p} to={p} navigate={this.navigate}><span>{String(i+1).padStart(2,'0')}</span>{label}<Icon name="diagonal"/></Link>)}</nav><a className="v7-direct" href={'tel:'+business.telephone}>Yunus Usta · {business.display}</a></Dialog>}
 {s.search&&<Dialog title="Atölyede bir şey arayın" onClose={()=>this.setState({search:false})}><label className="search-dialog-input"><Icon name="search"/><input autoFocus type="search" placeholder="Mutfak, kahve köşesi, gardırop…" aria-label="Arama kelimesi" value={s.searchQuery} maxLength={100} onInput={e=>this.setState({searchQuery:e.currentTarget.value})}/></label><div className="search-results" role="region" aria-live="polite">{results.map(x=><Link key={x.id} to={x.path} navigate={this.navigate}>{x.image&&<VImage asset={x.image} alt="" sizes="80px"/>}<span><strong>{x.title}</strong><small>{categoryName(x.category)} · {x.kind==='page'?'Stüdyo ve rehber':x.kind==='concept'?'Konsept model':x.kind==='reference'?'Pinterest referansı':'Atölye arşivi'}</small></span><Icon name="diagonal"/></Link>)}{!results.length&&<p className="empty-state">Sonuç bulunamadı. Başka bir kelime deneyin.</p>}</div><TextLink to={'/arama?q='+encodeURIComponent(s.searchQuery.trim())} navigate={this.navigate}>Tüm sonuçları gör</TextLink></Dialog>}
 {s.info&&<Dialog title="Bilgi ve cihaz kayıtları" onClose={()=>this.setState({info:false})}><div className="info-dialog"><Eyebrow>V12 C+ / ŞEFFAF BİR BAŞLANGIÇ</Eyebrow><p>Yunus Usta'nın kullanıcı tarafından paylaşılan iş telefonu {business.display}. WhatsApp ve telefon bağlantıları bu numarayı açar. Yeni açık adres henüz kesinleşmemiştir.</p><h3>Mesajı siz gönderirsiniz.</h3><p>Site proje özetinizi hazırlar. Sitede ödeme, sipariş kaydı veya otomatik gönderim yoktur. WhatsApp mesajını orada gönderirsiniz. Dosya paylaşımı ayrı bir adımdır. Açıldı, gönderildi ve teslim alındı aynı durum değildir.</p><h3>Kişisel taslak yalnız bellekte.</h3><p>Not, ilçe, model ve görseller açık sekme içinde korunur, yeniden yüklemede silinebilir. Açıkça seçtiğinizde yalnız herkese açık ilham kimlikleri 30 gün cihazda kalır. 3D seçenekleri bu açık sekmede hatırlanır ve yalnız oluşturduğunuz model bağlantısında paylaşılır. Analitik veya reklam pikseli yüklenmez.</p><button className="button button-outline" onClick={()=>{if(window.confirm('Bu açık sekmedeki proje fikri, görseller ve bu cihazdaki Elif kayıtları silinsin mi?')){projectStore.clear();attachmentStore.clear();try{Object.keys(localStorage).filter(k=>k.startsWith('elif-v2:')||k.startsWith('elif-v7:')).forEach(k=>localStorage.removeItem(k))}catch{}this.setState({favorites:[],remember:false,info:false});this.navigate('/');this.notify('Elif taslağı ve bu cihazdaki kayıtlar temizlendi.')}}}>Taslağı ve cihaz kayıtlarını sil <Icon name="close"/></button><Link to="/gizlilik" navigate={p=>{this.setState({info:false});this.navigate(p)}} className="text-link">Veri ve dış servis açıklaması <Icon/></Link></div></Dialog>}
 {s.scrolled&&!studio&&!s.menu&&!s.search&&!s.info&&<div className="v7-mobile-contact"><a href={'tel:'+business.telephone}><Icon name="phone" size={18}/>Ara</a><a href={whatsappUrl(contactText)} target="_blank" rel="noopener noreferrer">Yunus Usta’ya yaz <Icon name="diagonal" size={18}/></a></div>}
 {s.scrolled&&!studio&&<button className="v5-backtop" type="button" aria-label="Sayfanın başına dön" onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant' as ScrollBehavior:'smooth'})}><span className="v5-up"><Icon name="down" size={18}/></span><span>Başa dön</span></button>}
 {s.toast&&<div className="toast" role="status"><Icon name="check"/><span>{s.toast}</span><button className="icon-button" onClick={()=>this.setState({toast:''})} aria-label="Bildirimi kapat"><Icon name="close" size={16}/></button></div>}
 </>}
}
