const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(p,cache={}){p=path.resolve(p);if(cache[p])return cache[p].exports;const m={exports:{}};cache[p]=m;const code=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('module','exports','require',code)(m,m.exports,id=>id.startsWith('.')?load(path.resolve(path.dirname(p),id)+'.ts',cache):require(id));return m.exports;}
const {DesignBoard,parseWholeNumber}=load('src/lib/design-board.ts');const {defaultStudio}=load('src/lib/desk-v8.ts');
test('V20 comparison is bounded to three independent configurations',()=>{const b=new DesignBoard();for(const width of [160,180,200])assert.equal(b.add({...defaultStudio,width}).status,'added');assert.equal(b.add({...defaultStudio,width:220}).status,'full');assert.equal(b.list().length,3);});
test('V20 duplicate configuration reuses entry and preview without adding a fourth',()=>{const b=new DesignBoard();const a=b.add(defaultStudio);const d=b.add(defaultStudio);assert.equal(a.id,d.id);assert.equal(d.status,'duplicate');assert.equal(b.list().length,1);});
test('V20 comparison snapshots do not mutate source or each other',()=>{const b=new DesignBoard();b.add(defaultStudio);const a=b.list();a[0].config.height=120;assert.equal(b.list()[0].config.height,80);});
test('V20 export carries configuration only and import validates before replacing',()=>{const b=new DesignBoard();b.add({...defaultStudio,note:'PRIVATE'});const text=b.serialize();assert.ok(!text.includes('PRIVATE'));const c=new DesignBoard();assert.equal(c.import(text),1);assert.equal(c.list()[0].config.width,180);assert.throws(()=>c.import('{"kind":"other"}'));assert.equal(c.list().length,1);});
test('V20 rejects malformed, oversize or out-of-bounds configuration files',()=>{const b=new DesignBoard();for(const options of [[{...defaultStudio,width:990}],Array(4).fill(defaultStudio),[{...defaultStudio,note:'sensitive'}]])assert.throws(()=>b.import(JSON.stringify({kind:'elif.design-board',version:1,options})));assert.throws(()=>b.import(' '.repeat(20000)));});
test('V20 editor accepts intermediate typing at commit, not scientific or decimal values',()=>{assert.equal(parseWholeNumber('203',120,220),203);assert.equal(parseWholeNumber(' 180 ',120,220),180);for(const x of ['','1e2','180.5','119','221','-150'])assert.equal(parseWholeNumber(x,120,220),null);});
const {evaluateRoomFit}=load('src/lib/room-fit.ts');
test('V20 tiny overflow cannot be rounded into a false fit',()=>{assert.equal(evaluateRoomFit(199.99,300,{width:200,depth:120}).fits,false);});
