import {createElement,Fragment} from 'react';
import {image,Link,Icon,type PageProps} from './ui';
import {imageManifest} from '../lib/image-manifest';
import {categoryName,type Work} from '../lib/portfolio';
export function VImage({asset,alt,className='',eager=false,sizes='(max-width: 680px) 100vw, 50vw',full=false}:{asset:string;alt:string;className?:string;eager?:boolean;sizes?:string;full?:boolean}) {
 const m=(imageManifest as any)[asset];
 if(!m)return <img src={image(asset)} alt={alt} className={className} loading={eager?'eager':'lazy'}/>;
 const max=m.variants[m.variants.length-1],fallback=full?max:m.variants[Math.min(1,m.variants.length-1)];
 return <img src={image(fallback.file)} srcSet={m.variants.map((v:any)=>image(v.file)+' '+v.width+'w').join(', ')} sizes={sizes} width={m.width} height={m.height} alt={alt} className={className} loading={eager?'eager':'lazy'} decoding={eager?'sync':'async'} fetchPriority={eager?'high':'auto'}/>;
}
export function SourceTag({kind='work'}:{kind?:'work'|'process'|'concept'|'reference'}){return <span className={'source-tag source-'+kind}>{({work:'Atölye arşivi',process:'Uygulama aşaması',concept:'Konsept model',reference:'Pinterest ilhamı'})[kind]}</span>}
export function WorkCard({work:w,actions:a,featured=false,index=0}:{work:Work;actions:PageProps;featured?:boolean;index?:number}){return <article className={'work-card'+(featured?' featured-work':'')} data-work={w.id}>
 <Link to={'/proje/'+w.id} navigate={a.navigate} className="work-photo"><VImage asset={w.images[0]} alt={w.subtitle+', atölyeden paylaşılan fotoğraf'} sizes="(max-width: 680px) 90vw, (max-width: 1024px) 45vw, 30vw"/><SourceTag kind={w.id==='ahsap-bahce-kamelyasi'?'process':w.status}/><span className="work-open"><Icon name="diagonal" size={22}/></span></Link>
 <div className="work-caption"><span className="work-index">{String(index+1).padStart(2,'0')}</span><div><span className="work-category">{categoryName(w.category)}</span><h3><Link to={'/proje/'+w.id} navigate={a.navigate}>{featured?categoryName(w.category):w.title}</Link></h3><p>{w.subtitle}</p></div></div>
 <button type="button" className="v7-save-text" aria-label={w.subtitle+(a.favorites.includes('work:'+w.id)?' kaydını kaldır':' çalışmasını kaydet')} aria-pressed={a.favorites.includes('work:'+w.id)} onClick={()=>a.favorite('work:'+w.id)}><Icon name="heart" size={18}/>{a.favorites.includes('work:'+w.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button></article>}
export function ModelCallout({navigate,compact=false}:{navigate:(p:string)=>void;compact?:boolean}){return <section className={'model-callout'+(compact?' compact':'')}><div className="model-callout-image"><VImage asset="concept-model" alt="Malzeme numuneleri, çizimler ve görsel fikirlerden oluşan temsili tasarım masası"/><SourceTag kind="concept"/></div><div className="model-callout-copy"><span className="eyebrow">KATALOGDA OLMAYANI DA KONUŞALIM</span><h2>Kendi modelinizi getirin.<br/><em>Birlikte üretelim.</em></h2><p>Pinterest'te kaydettiğiniz bir model, bir fotoğraf ya da elinizle çizdiğiniz bir fikir. Bize gösterin, ölçünüze ve ihtiyacınıza göre birlikte yorumlayalım.</p><Link to="/modelini-getir" navigate={navigate} className="button">Modelimi paylaşmak istiyorum <Icon/></Link><small>Ölçü, malzeme ve üretilebilirlik Yusuf Usta ile değerlendirilir.</small></div></section>}
