import {normalizeReference} from './model-request';
export const business=Object.freeze({name:'Elif Tasarım',contact:'Yusuf Usta',digits:'905308797169',telephone:'+905308797169',display:'+90 530 879 71 69',city:'İstanbul',verifiedBy:'Kullanıcı beyanı, 24 Eylül 2026'});
export function whatsappUrl(text='Merhaba Yusuf Usta. Elif Tasarım üzerinden yazıyorum, projem hakkında görüşmek istiyorum.'):string{return 'https://wa.me/'+business.digits+'?text='+encodeURIComponent(text)}
export type ProjectDraft={category:string;url:string;note:string;dimensions:string;district:string;timing:string;interpretation:string;width:string;depth:string;height:string;unit:'cm'|'mm';unknown:boolean;material:string;finish:string;details:string;readiness:string;selections:string[]};
export function emptyProject():ProjectDraft{return {category:'ozel-tasarim',url:'',note:'',dimensions:'',district:'',timing:'Birlikte planlayalım',interpretation:'Alanıma göre birlikte yorumlayalım',width:'',depth:'',height:'',unit:'cm',unknown:true,material:'Birlikte değerlendirelim',finish:'Birlikte değerlendirelim',details:'',readiness:'Fikir topluyorum',selections:[]}}
export function createProjectStore(){let value=emptyProject();const seen=new Set<string>();return {get:():ProjectDraft=>({...value,selections:[...value.selections]}),patch:(patch:Partial<ProjectDraft>)=>{value={...value,...patch,selections:patch.selections?[...patch.selections]:value.selections};return {...value,selections:[...value.selections]}},seed:(key:string,seed:Partial<ProjectDraft>,replace=false)=>{if(seen.has(key))return;seen.add(key);if(replace){value={...value,...seed};return;}for(const [k,v] of Object.entries(seed)){const name=k as keyof ProjectDraft;if(v!==undefined&&v!==''&&(!(value as any)[name]||(name==='category'&&value.category==='ozel-tasarim')))(value as any)[name]=v;}},clear:()=>{value=emptyProject();seen.clear()}}}
export const projectStore=createProjectStore();
export function convertMeasure(value:string,from:'cm'|'mm',to:'cm'|'mm'):string|null{if(!value.trim())return '';if(!/^\d+(?:[.,]\d+)?$/.test(value.trim()))return null;const n=Number(value.replace(',','.'));if(!Number.isFinite(n)||n<=0)return null;return String(Math.round(n*(from===to?1:from==='cm'?10:0.1)*10000)/10000)}
export function projectText(v:ProjectDraft,files:string[],selectionLabels:string[]=[]):string{return ['Merhaba Yusuf Usta, Elif Tasarım üzerinden yazıyorum.','Proje fikrimi birlikte değerlendirmek istiyorum.','', 'İhtiyaç, '+v.category,'Model, '+(normalizeReference(v.url)||'Yazılı fikir / fotoğraf'),'Fikrim, '+(v.note||'Seçtiğim örnekler üzerinden konuşalım.'),'Yaklaşık ölçü, '+(!v.unknown&&v.width?[v.width,v.depth,v.height].join(' × ')+' '+v.unit:v.dimensions||'Birlikte belirlenecek'),'Bölge, '+(v.district||'Görüşmede paylaşacağım'),'Malzeme, '+v.material,'Yüzey, '+v.finish,'Kullanım ayrıntıları, '+(v.details||'Birlikte değerlendirelim'),'Zaman, '+v.timing,'Aşama, '+v.readiness,'Yaklaşım, '+v.interpretation,selectionLabels.length?'Seçtiklerim, '+selectionLabels.join(' / '):'',files.length?'Görseller, '+files.join(', ')+' (bu bağlantıda ekli değil, ayrıca paylaşacağım)':'','', 'Ölçü, donanım ve uygulanabilirlik görüşmede netleşsin. Bu mesaj kesin sipariş veya üretim onayı değildir.'].filter(Boolean).join('\n')}
export type Attachment={id:string;name:string;file:File;preview:string;sourceBytes:number};
let items:Attachment[]=[];
export const attachmentStore={get:()=>[...items],add:(a:Attachment[])=>{items=[...items,...a]},remove:(id:string)=>{items.filter(x=>x.id===id).forEach(x=>URL.revokeObjectURL(x.preview));items=items.filter(x=>x.id!==id)},clear:()=>{items.forEach(x=>URL.revokeObjectURL(x.preview));items=[]}};
export function hasPrivateDraft(){const d=projectStore.get();return Boolean(d.note||d.url||d.dimensions||d.district||d.details||attachmentStore.get().length)}
