/** Bounded header inspection before image decoding. No remote uploads. */
export type ImageSize={width:number;height:number;type:string};
export function imageDimensions(b:Uint8Array):ImageSize|null{
 const at=(n:number)=>b[n]||0,be16=(n:number)=>(at(n)<<8)|at(n+1),be32=(n:number)=>at(n)*16777216+at(n+1)*65536+at(n+2)*256+at(n+3),le24=(n:number)=>at(n)+at(n+1)*256+at(n+2)*65536,word=(n:number,s:string)=>s.split('').every((c,i)=>at(n+i)===c.charCodeAt(0));
 if(b.length>=24&&[137,80,78,71,13,10,26,10].every((v,i)=>at(i)===v)&&word(12,'IHDR'))return {width:be32(16),height:be32(20),type:'image/png'};
 if(b.length>=12&&at(0)===255&&at(1)===216){let i=2;while(i+4<b.length){if(at(i)!==255)return null;while(at(i)===255)i++;const marker=at(i++);if(marker===217||marker===218)break;if(marker===1||(marker>=208&&marker<=215))continue;const len=be16(i);if(len<2||i+len>b.length)return null;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)&&len>=8)return {width:be16(i+5),height:be16(i+3),type:'image/jpeg'};i+=len;}return null;}
 if(b.length>=30&&word(0,'RIFF')&&word(8,'WEBP')){if(word(12,'VP8X')){if(at(20)&2)return null;return {width:le24(24)+1,height:le24(27)+1,type:'image/webp'}}if(word(12,'VP8 ')&&at(23)===157&&at(24)===1&&at(25)===42)return {width:(at(26)+at(27)*256)&16383,height:(at(28)+at(29)*256)&16383,type:'image/webp'};if(word(12,'VP8L')&&at(20)===47)return {width:1+(((at(22)&63)<<8)|at(21)),height:1+(((at(24)&15)<<10)|(at(23)<<2)|((at(22)&192)>>6)),type:'image/webp'};}
 return null;
}
export function fileTypeError(type:string,name:string):string|null{if(/heic|heif/i.test(type+' '+name))return 'HEIC/HEIF bu sürümde desteklenmiyor. Fotoğrafı JPG olarak dışa aktarın veya ekran görüntüsünü PNG olarak ekleyin.';return ['image/jpeg','image/png','image/webp'].includes(type)?null:'JPG, PNG veya WebP biçiminde gerçek bir fotoğraf seçin.'}
export function imageBudgetError(size:ImageSize|null,bytes:number,total:number):string|null{if(!size||!Number.isInteger(size.width)||!Number.isInteger(size.height)||size.width<1||size.height<1)return 'Görsel başlığı okunamadı. JPG veya PNG olarak yeniden kaydedin.';if(bytes>10*1024*1024)return 'Bir görsel en fazla 10 MB olabilir.';if(bytes+total>25*1024*1024)return 'Görsellerin kaynak boyutu toplam en fazla 25 MB olabilir.';if(size.width*size.height>20000000)return '20 megapikselden küçük bir görsel seçin.';return null}
export async function prepareImage(file:File,total:number){const typeError=fileTypeError(file.type,file.name);if(typeError)throw Error(typeError);if(file.size>10*1024*1024)throw Error('Bir görsel en fazla 10 MB olabilir.');if(file.size+total>25*1024*1024)throw Error('Görsellerin kaynak boyutu toplam en fazla 25 MB olabilir.');const header=new Uint8Array(await file.slice(0,524288).arrayBuffer()),size=imageDimensions(header),error=imageBudgetError(size,file.size,total);if(error)throw Error(error);if(size!.type!==file.type)throw Error('Dosya türü ile görsel içeriği uyuşmuyor.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>20000000)throw Error('20 megapikselden küçük bir görsel seçin.');const scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Bu tarayıcı görsel hazırlayamıyor.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Görsel hazırlanamadı.')),'image/jpeg',0.9));const id=typeof crypto.randomUUID==='function'?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(36).slice(2);return {id,name:file.name,file:new File([blob],'model-'+id.slice(0,8)+'.jpg',{type:'image/jpeg'}),preview:URL.createObjectURL(blob),sourceBytes:file.size};}finally{bitmap.close()}}
