import {createElement,Fragment,Component} from 'react';
import {WorkCard} from '../components/PortfolioUI';
import {works,workDisplayStage,prioritizeWorks} from '../lib/portfolio';
import {image,Link,Icon,TextLink,Eyebrow,Dialog,Accordion,type PageProps} from '../components/ui';
import {VImage,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {beds,type BedConcept} from '../lib/beds';
import {modelHref} from '../lib/portfolio';
import {targetElementId} from '../lib/selections';

const viewLabel=(open:boolean)=>open?'Depolama görünümü':'Kapalı görünüm';

/** The approved views are visual studies. A lift-frame image is not a tested mechanism. */
export class BedCard extends Component<{bed:BedConcept;navigate:(p:string)=>void;actions?:PageProps},{open:boolean;zoom:boolean}>{
 state={open:false,zoom:false};
 render(){const {bed:b,actions:a,navigate}=this.props,s=this.state,id='concept:'+b.id,asset=s.open?b.openImage:b.image;
 const choices=(large=false)=><div className={'bed-view-controls'+(large?' bed-view-controls-large':'')} role="group" aria-label={b.title+' görünümü'}>{[false,true].map(open=><button key={String(open)} type="button" aria-pressed={s.open===open} onClick={()=>this.setState({open})}>{viewLabel(open)}</button>)}</div>;
 return <article className="bed-card" id={targetElementId(id)} tabIndex={-1} data-bed={b.id}>
  <div className="bed-card-image"><button type="button" className="bed-zoom" aria-haspopup="dialog" aria-label={b.title+' görselini büyüt'} onClick={()=>this.setState({zoom:true})}><VImage asset={asset} alt={b.title+'. '+viewLabel(s.open)+'. Yapay zekâ ile hazırlanmış baza konsepti.'} sizes="(max-width: 700px) 92vw, (max-width: 1100px) 46vw, 580px"/><span className="bed-zoom-hint"><Icon name="search" size={16}/>Büyüt</span></button></div>
  {choices()}<div className="bed-card-copy"><div className="bed-card-meta"><SourceTag kind="concept"/><span>{b.group==='wood'?'Ahşap ağırlıklı':'Döşemeli yorum'}</span></div><h3>{b.title}</h3><p className="bed-material">{b.material}</p><p>{b.description}</p><details className="bed-details"><summary>Tasarım ayrıntıları</summary><ul>{b.details.map(d=><li key={d}>{d}</li>)}</ul><p>Ahşap türü, kaplama, kumaş ve mekanizma seçimi numune ve teknik değerlendirmeyle kesinleşir. Görseldeki donanım bir güvenlik veya taşıma kapasitesi beyanı değildir.</p><p className="bed-direct-views"><a href={image(b.image+'-full.webp')} target="_blank" rel="noopener noreferrer">Kapalı görseli aç</a><a href={image(b.openImage+'-full.webp')} target="_blank" rel="noopener noreferrer">Depolama görselini aç</a></p></details><div className="bed-actions"><TextLink to={modelHref('',b.category,b.subtitle+' üzerine konuşmak istiyorum.',id)} navigate={navigate}>Bu modeli konuşalım</TextLink>{a&&<button type="button" className="bed-save" aria-label={(a.favorites.includes(id)?'İlham dosyasından çıkar. ':'İlham dosyama ekle. ')+b.title} aria-pressed={a.favorites.includes(id)} onClick={()=>a.favorite(id)}><Icon name="heart" size={18}/><span>{a.favorites.includes(id)?'Kaydedildi':'Kaydet'}</span></button>}</div></div>
  {s.zoom&&<Dialog title={b.title+' · Konsept model'} onClose={()=>this.setState({zoom:false})} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();this.setState(previous=>({open:!previous.open}));}}}><div className="bed-gallery"><VImage asset={asset} alt={b.title+'. '+viewLabel(s.open)+'. Baza tasarım konsepti.'} eager full sizes="(max-width: 700px) 92vw, 1000px"/>{choices(true)}<p className="bed-gallery-note">{viewLabel(s.open)}. Yapay zekâ ile hazırlanmış tasarım görselidir. Bitmiş atölye işi veya teknik üretim çizimi değildir.</p></div></Dialog>}
 </article>;
 }
}

export class BedCollection extends Component<PageProps&{query?:string},{group:'all'|'wood'|'upholstered'}>{
 state:{group:'all'|'wood'|'upholstered'}={group:'all'};
 private focusFrame:number|undefined;
 focusModel=()=>{if(this.focusFrame!==undefined)cancelAnimationFrame(this.focusFrame);const id=new URLSearchParams(this.props.query||'').get('model');if(!id||!beds.some(b=>b.id===id))return;this.setState({group:'all'},()=>{this.focusFrame=requestAnimationFrame(()=>{this.focusFrame=requestAnimationFrame(()=>{const node=document.getElementById(targetElementId('concept:'+id));node?.focus({preventScroll:true});node?.scrollIntoView({block:'start',behavior:'instant' as ScrollBehavior});});});});};
 componentDidMount(){this.focusModel();}
 componentDidUpdate(previous:PageProps&{query?:string}){if(previous.query!==this.props.query)this.focusModel();}
 componentWillUnmount(){if(this.focusFrame!==undefined)cancelAnimationFrame(this.focusFrame);}

 render(){const a=this.props,items=beds.filter(b=>this.state.group==='all'||b.group===this.state.group);return <>
 <header className="wrap bed-collection-hero"><div className="bed-hero-copy"><Link to="/kategoriler" navigate={a.navigate} className="bed-back">Üretim alanları <Icon size={16}/></Link><Eyebrow>ELİF / BAZA VE YATAK</Eyebrow><h1>Günün sonunda,<br/><em>size ait bir yer.</em></h1><p>Ahşabın karakteri, döşemenin yumuşaklığı ve saklamaya ayrılan alan. Yatak odanız için sekiz farklı başlangıç fikri.</p><a className="button" href="#baza-seckisi">Modelleri keşfedin <Icon/></a><p><a href="#bed-completed-works" className="text-link">Bitirdiğimiz yatak odası işlerine bakın <Icon/></a></p><p className="bed-hero-disclosure">Bu seçki, yapay zekâ ile hazırlanmış tasarım konseptlerinden oluşur. Tamamlanmış atölye işi, stok ürünü veya üretim onayı değildir.</p></div><figure className="bed-hero-visual"><VImage asset="bed-ceviz-yalin-open" alt="Ceviz Yalın baza konseptinin açık depolama görünümü. Ahşap görünümlü gövde ve krem başlık." eager full priority="high" sizes="(max-width: 800px) 100vw, 58vw"/><figcaption><span>Ceviz Yalın</span><span>Ahşap ağırlıklı konsept</span></figcaption></figure></header>
 <div className="wrap bed-collection-summary"><span><strong>08</strong> tasarım yorumu</span><span><strong>04</strong> ahşap ağırlıklı model</span><span><strong>02</strong> görünüm, her modelde</span></div>
 <section className="wrap bed-collection" id="baza-seckisi"><div className="v6-heading"><div><Eyebrow>BAŞLIKTAN GÖVDEYE BİR BÜTÜN</Eyebrow><h2>Dokusu farklı.<br/><em>İhtiyacı sizin.</em></h2></div><p>Kapalı görünümde çizgisini, depolama görünümünde iç düzen fikrini inceleyin. Beğendiğiniz modeli kaydedin veya doğrudan o fikirle görüşmeye başlayın.</p></div><div className="bed-filter-row"><div className="filter-chips" role="group" aria-label="Baza tasarım türü">{[['all','Tüm modeller'],['wood','Ahşap ağırlıklı'],['upholstered','Döşemeli yorumlar']].map(([group,title])=><button type="button" key={group} aria-pressed={this.state.group===group} onClick={()=>this.setState({group:group as 'all'|'wood'|'upholstered'})}>{title}</button>)}</div><span className="bed-result" role="status" aria-live="polite">{items.length} model</span></div><div className="bed-grid">{items.map(b=><BedCard key={b.id} bed={b} navigate={a.navigate} actions={a}/>)}</div></section>
 <section className="bed-preparation"><div className="wrap bed-preparation-inner"><div><Eyebrow>GÖRSELDEN SİZİN ODANIZA</Eyebrow><h2>Ölçüyü değil,<br/><em>önce ihtiyacı konuşalım.</em></h2><p>Buradaki modeller birer başlangıç noktası. Seçtiğiniz çizgi, odanızın koşulları ve kullanımınızla birlikte değerlendirilir.</p><TextLink to="/rehber/malzeme-secimi" navigate={a.navigate}>Malzeme seçimini tanıyın</TextLink></div><div><Accordion items={[
 ['Ölçü ve yerleşim için neler gerekli?','Mevcut yatağınızın eni ve boyu, odadaki geçişler, komodinler ve başlık için ayrılabilen alanla başlayabiliriz. Yaklaşık ölçüler görüşme içindir. Kesin üretim ölçüsü yerinde veya teknik değerlendirmeyle teyit edilir.'],
 ['Görseldeki ahşap ve kumaş birebir mi?','Görseller renk ve tasarım fikrini gösterir. Ceviz veya meşe görünümü, bütün gövdenin masif ahşap olduğu anlamına gelmez. Masif, kaplama, gövde malzemesi, kumaş ve yüzey işlemi ayrı seçilir. Son karar gerçek numuneyle verilir.'],
 ['Açılır mekanizma nasıl seçilir?','Yatak ölçüsü ve ağırlığı, taşıyıcı yapı, bağlantılar, açılma mesafesi ve emniyet donanımı birlikte değerlendirilir. Görselden gazlı amortisör kuvveti veya taşıma kapasitesi belirlenmez. Üretim öncesinde uygun mekanizma ve teknik ayrıntılar usta ve donanım sağlayıcısıyla doğrulanmalıdır.'],
 ['Fiyat ve teslim kapsamı nasıl netleşir?','Baza gövdesi, başlık, döşeme, mekanizma, yatak, komodin, nakliye ve montaj kapsamları teklif aşamasında ayrı konuşulur. Bir görseli seçmek sipariş veya üretim onayı oluşturmaz. Fiyat ve süre, kesinleşen kapsam üzerinden belirlenir.']
 ]}/></div></div></section><section id="bed-completed-works" className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>ATÖLYEDEN</Eyebrow><h2>Bitirdiğimiz işlerden<br/><em>seçkiler.</em></h2></div></div><div className="work-grid">{prioritizeWorks(works.filter(w=>w.category==='baza-yatak'&&workDisplayStage(w)==='work')).map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div></section><ModelCallout navigate={a.navigate}/>
 </>;}
}
