import {createElement,Fragment} from 'react';
import {Link,ButtonLink,TextLink,Eyebrow,Icon,Photo,type PageProps} from '../components/ui';
import {studioQuery,defaultStudio} from '../lib/desk-v8';
import {whatsappUrl} from '../lib/project';
const configurations=[{title:'Odak',subtitle:'Kompakt bir başlangıç.',finish:'Açık meşe görünümü',width:160,depth:75,height:80,angle:0,material:'mese' as const,image:'devir-odak-v23.webp'},{title:'Akış',subtitle:'İki yüzey, tek çalışma düzeni.',finish:'Ceviz görünümü',width:180,depth:80,height:80,angle:90,material:'ceviz' as const,image:'devir-akis-v23.webp'},{title:'Hareket',subtitle:'Ayakta çalışmaya bir bakış.',finish:'Koyu ahşap görünümü',width:200,depth:85,height:110,angle:180,material:'koyu' as const,image:'devir-hareket-v23.webp'}];
export function Devir(a:PageProps){return <div className="v20-devir"><section className="v20-product-hero wrap"><div className="v20-product-copy"><Eyebrow>ELİF TASARIM / KONSEPT SERİSİ 01</Eyebrow><h1>DEVİR<span>Çalışma biçiminize<br/><em>yer açın.</em></span></h1><p>Biraz yükselir. Yön değiştirir. Günlük eşyalarınıza yer açar. Devir, çalışma alanını sabit bir kalıp yerine sizinle birlikte düşünmek için tasarlandı.</p><ButtonLink to="/tasarim-masasi" navigate={a.navigate}>Kendi Devir’inizi tasarlayın</ButtonLink><small>Yükseklik ayarlı masa konsepti. Henüz onaylanmış ürün şartnamesi değildir.</small></div><div className="v20-product-visual"><Photo name="devir-hareket-v23.webp" alt="Yükseltilmiş Devir konsepti, Three.js modelinden ürün görünümü" ratio="3/2" eager/><span className="v20-product-stamp">01<br/><small>KONSEPT MODEL</small></span><span className="v20-material-caption">DOKU. HAREKET. İŞLEV.</span></div></section>
 <nav className="v20-product-nav wrap" aria-label="Devir bölüm kısayolları"><a href="#devir-yaklasim" onClick={e=>{e.preventDefault();document.getElementById('devir-yaklasim')?.scrollIntoView({behavior:'auto'});}}>Tasarım fikri</a><a href="#devir-baslangic" onClick={e=>{e.preventDefault();document.getElementById('devir-baslangic')?.scrollIntoView({behavior:'auto'});}}>Üç başlangıç</a><a href="#devir-detay" onClick={e=>{e.preventDefault();document.getElementById('devir-detay')?.scrollIntoView({behavior:'auto'});}}>Ayrıntılar</a><Link to="/tasarim-masasi" navigate={a.navigate}>3D stüdyo <Icon size={16}/></Link></nav>
 <section className="wrap v20-product-story" id="devir-yaklasim"><Eyebrow>TEK MASA. BİRDEN FAZLA HÂL.</Eyebrow><h2>Gününüz değişir.<br/><em>Çalışma alanınız da değişebilir.</em></h2><div><p>Ana tabla ile yükselen çekmeceler, yerini koruyan alt depolama ve bağımsız yan çalışma yüzeyi. Her parça, başka bir kullanım ihtimalini birlikte düşünmek için.</p><p>Stüdyoda renk ve ölçü seçmek, üretim kararı vermek değildir. İhtiyacınızı daha açık anlatmanın bir yoludur. Sonra Yunus Usta ile malzemeyi, mekanizmayı ve uygulamayı netleştirirsiniz.</p></div></section>
 <section className="wrap v23-feature-strip" aria-labelledby="devir-ozellikleri"><div className="v23-feature-heading"><Eyebrow>DEVİR 01 / NEDEN BÖYLE?</Eyebrow><h2 id="devir-ozellikleri">Bir masa değil,<br/><em>üç kullanım kararı.</em></h2></div><div className="v23-feature-grid"><article><span>01</span><h3>Yükselir.</h3><p>Ana yüzey ve üst çekmeceler birlikte hareket eder. Oturarak ve ayakta çalışma fikrini aynı geometri üzerinde değerlendirin.</p></article><article><span>02</span><h3>Döner.</h3><p>Yan yüzey düzenden L biçimine kadar farklı çalışma yönlerine yaklaşır. Gerçek hareket sınırı prototiple doğrulanır.</p></article><article><span>03</span><h3>Saklar.</h3><p>Üst çekmeceler ve sabit alt gövde, günlük ekipmanı çalışma yüzeyinden uzak tutmak için düşünülmüştür.</p></article></div></section>
 <section className="v20-room-editorial"><Photo name="devir-atolye-v23.webp" alt="İki kitaplıklı çalışma alanında Devir konsepti" ratio="16/9" eager/><div><Eyebrow>MEKÂNI BİRLİKTE HAYAL EDELİM</Eyebrow><h2>Yalnız masa değil.<br/><em>Size ait bir çalışma köşesi.</em></h2><p>Stüdyodaki kitaplıklar ve ışık, yerleşimi düşünmek içindir. Masa teklifine kendiliğinden dahil değildir.</p><TextLink to="/tasarim-masasi" navigate={a.navigate} light>Mekânı üç boyutta inceleyin</TextLink></div></section>
 <section className="wrap v20-config-starts" id="devir-baslangic"><div className="v20-section-heading"><div><Eyebrow>NEREDEN BAŞLAYALIM?</Eyebrow><h2>Üç fikir.<br/><em>Son söz sizin.</em></h2></div><p>Hazır ürün paketi değil, değiştirilebilir görsel başlangıçlar. Her birini 3D stüdyoda kendi ihtiyacınıza göre düzenleyin.</p></div><div className="v20-start-grid">{configurations.map((c,i)=><Link to={'/tasarim-masasi?'+studioQuery({...defaultStudio,...c})} navigate={a.navigate} key={c.title}><span className="v20-start-num">0{i+1}</span><Photo name={c.image} alt={c.title+' başlangıcı. '+c.width+' × '+c.depth+' cm, '+c.height+' cm yükseklik, '+c.material+' görünümü. Gerçek 3D modelden konsept.'} ratio="3/2" caption={false} eager/><div className={'v20-start-swatch '+c.material} aria-hidden="true"/><h3>{c.title}</h3><p>{c.subtitle}</p><small><strong>{c.finish}</strong><br/>{c.width} × {c.depth} cm ana tabla.<br/>{c.height} cm çalışma yüksekliği.</small><span className="text-link">Bu fikirle başla <Icon/></span></Link>)}</div></section>
 <section className="wrap v20-detail-editorial" id="devir-detay"><Photo name="devir-detay-v23.webp" alt="Devir modelinin depolama ve birleşim ayrıntısı" ratio="3/2" eager/><div><Eyebrow>İYİ DÜŞÜNÜLMÜŞ BİR GÜNLÜK HAYAT</Eyebrow><h2>Ayrıntılar,<br/><em>kullanırken anlam kazanır.</em></h2><dl>{[['Yükselen yüzey','Oturma ve ayakta çalışma konumlarını görsel olarak değerlendirin.'],['Üç ince çekmece','Günlük küçük ekipmanlarınız için entegre depolama fikri.'],['Döner yan tabla','L veya açık yerleşimi kendi alanınıza göre karşılaştırın.'],['Sabit alt dolap','Dosya ve aksesuarlar için düzenlenebilir bir alt hacim.']].map(([title,desc])=><div key={title}><dt>{title}</dt><dd>{desc}</dd></div>)}</dl><TextLink to="/tasarim-masasi" navigate={a.navigate}>3D detay noktalarını keşfedin</TextLink></div></section>
 <section className="wrap v20-product-close"><Eyebrow>FİKİRDEN GERÇEK MOBİLYAYA</Eyebrow><h2>Şimdi sizin alanınızı<br/><em>konuşalım.</em></h2><p>Yaklaşık ölçünüz, ekipmanınız ve günlük çalışma biçiminiz. Başlamak için bu kadarı yeterli.</p><div><ButtonLink to="/tasarim-masasi" navigate={a.navigate}>3D’de tasarla ve paylaş</ButtonLink><a className="text-link" href={whatsappUrl('Merhaba Yunus Usta, Devir 01 çalışma masası konseptini kendi alanım için değerlendirmek istiyorum.')} rel="noopener noreferrer" target="_blank">Doğrudan Yunus Usta’ya sor <Icon name="diagonal" size={17}/></a></div><small>Motor, güvenli hareket sınırları, gerçek yüzey numunesi, son ölçü, kapsam ve fiyat üretim öncesi ayrıca onaylanır. Görseller konsepttir.</small></section></div>}
