import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Accordion,Photo,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,featuredWorks,homeConcepts} from '../lib/portfolio';
import {ConceptCard} from './Portfolio';
import {HERO_FIRST_DELAY,HERO_INTERVAL,decodeHeroFrame} from '../lib/hero-rotation';
import {defaultDesk,deskQuery,type Desk} from '../lib/desk';
const scenes=[
 {image:'concept-hero',alt:"Ahşap görünümlü oval yemek masası, sandalyeler ve aydınlatmalı mutfak. Konsept model.",caption:'Yaşamın etrafında toplandığı yer.',label:'Yemek',kind:'concept'},
 {image:'concept-gardrop',alt:"Cam kapaklı gardıroplar, aydınlatılmış raflar ve orta depolama adası. Giyinme odası konsepti.",caption:'Her ayrıntıya yer açan bir düzen.',label:'Giyinme',kind:'concept'},
 {image:'concept-kahve',alt:"Cam yan vitrinler, kemerli raflar ve çekmeceli kahve dolabı. Konsept model.",caption:'Günün en sevdiğiniz köşesi.',label:'Kahve',kind:'concept'},
 {image:'concept-sehpa',alt:"Oval orta sehpa ve iç içe zigonlar bulunan oturma alanı. Konsept model.",caption:'Bir arada, doğal ve yalın.',label:'Salon',kind:'concept'},
 {image:'concept-tv',alt:"Dikey çizgili TV paneli, açık raflar ve kapalı alt depolama. Konsept model.",caption:'Mekânınıza göre düşünülmüş.',label:'TV',kind:'concept'}
];
type HomeState={scene:number;desk:Desk;chapter:number;paused:boolean;requested:number[];loading:number|null;playing:boolean;epoch:number;status:string};
export class Home extends Component<PageProps,HomeState>{
 state:HomeState={scene:0,desk:{...defaultDesk},chapter:0,paused:false,requested:[0,1],loading:null,playing:false,epoch:0,status:''};
 private alive=false;private serial=0;private timer:number|undefined;private hero:HTMLElement|null=null;private observer:IntersectionObserver|null=null;private visible=true;private hover=false;private focus=false;private motion:MediaQueryList|null=null;private first=true;private automatic=false;private explicitPlay=false;private nextCandidate:number|null=null;
 componentDidMount(){this.alive=true;this.motion=matchMedia('(prefers-reduced-motion: reduce)');this.motion.addEventListener('change',this.reschedule);document.addEventListener('visibilitychange',this.reschedule);if(this.hero){this.observer=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting;this.reschedule()});this.observer.observe(this.hero)}this.reschedule()}
 componentWillUnmount(){this.alive=false;this.serial++;window.clearTimeout(this.timer);this.observer?.disconnect();this.motion?.removeEventListener('change',this.reschedule);document.removeEventListener('visibilitychange',this.reschedule)}
 canPlay=()=>!this.state.paused&&!this.motion?.matches&&!document.hidden&&this.visible&&(!(this.hover||this.focus)||this.explicitPlay);
 reschedule=()=>{
  window.clearTimeout(this.timer);this.timer=undefined;
  if(!this.canPlay()){
   if(this.automatic){this.serial++;this.automatic=false;if(this.state.loading!==null)this.setState({loading:null});}
   if(this.state.playing)this.setState({playing:false});return;
  }
  if(this.state.loading!==null)return;
  const delay=this.first?HERO_FIRST_DELAY:HERO_INTERVAL;
  this.setState(s=>({playing:true,epoch:s.epoch+1}));
  this.timer=window.setTimeout(()=>{this.timer=undefined;void this.setScene(this.nextCandidate??((this.state.scene+1)%scenes.length),true)},delay);
 };
 hold=(held:boolean)=>{this.hover=held;if(held)this.explicitPlay=false;this.reschedule()};
 togglePlayback=()=>{const paused=!this.state.paused;this.explicitPlay=!paused;if(paused){this.serial++;this.automatic=false;}this.setState({paused,loading:paused?null:this.state.loading},this.reschedule)};
 warm=(scene:number)=>{const next=(scene+1)%scenes.length;if(!this.state.requested.includes(next))this.setState(s=>({requested:[...s.requested,next]}));};
 setScene=(scene:number,automatic=false):Promise<void>=>{
  if(scene<0||scene>=scenes.length||automatic&&!this.canPlay())return Promise.resolve();
  window.clearTimeout(this.timer);this.timer=undefined;
  const token=++this.serial;this.automatic=automatic;
  if(!automatic)this.explicitPlay=false;
  if(scene===this.state.scene){this.setState({paused:automatic?this.state.paused:true,loading:null,playing:false,status:''},this.reschedule);return Promise.resolve();}
  return new Promise<void>(finish=>this.setState(s=>({requested:s.requested.includes(scene)?s.requested:[...s.requested,scene],paused:automatic?s.paused:true,loading:scene,playing:false,status:''}),async()=>{
   const ready=await decodeHeroFrame(()=>this.alive&&token===this.serial?this.hero?.querySelector<HTMLImageElement>('[data-slide="'+scene+'"] img')||null:null);
   if(!this.alive||token!==this.serial){finish();return;}
   this.automatic=false;
   if(ready){this.first=false;this.nextCandidate=null;this.setState({scene,loading:null,status:''},()=>{this.warm(scene);this.reschedule();finish()});}
   else{this.nextCandidate=(scene+1)%scenes.length;this.warm(scene);this.setState({loading:null,status:'Bu görsel açılamadı. Mevcut görüntüyü koruduk. Başka bir görsel seçebilirsiniz.'},()=>{this.reschedule();finish()});}
  }));
 };
 render(){const a=this.props,s=this.state,scene=scenes[s.scene];return <div className="v6-home">
 <section className="v6-hero v232-carousel" ref={el=>this.hero=el} aria-label="Elif Tasarım açılış seçkisi" aria-roledescription="slayt gösterisi"  onFocusCapture={()=>{this.focus=true;this.explicitPlay=false;this.reschedule()}} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node)){this.focus=false;this.reschedule()}}}>{scenes.map((sc,i)=><div className={'v6-hero-scene v232-scene'+(i===s.scene?' is-active':'')} key={sc.image} aria-hidden={i!==s.scene} data-slide={i}>{s.requested.includes(i)&&<VImage asset={sc.image} alt={sc.alt} eager priority={i===0?'high':'low'} full sizes="100vw"/>}</div>)}<div className="v6-hero-shade"/><div className="wrap v6-hero-inner"><Eyebrow>İSTANBUL / EL YAPIMI MOBİLYA ATÖLYESİ</Eyebrow><h1>Zamana değer<br/>{" "}<em>katan mobilyalar.</em></h1><p>İstanbul’daki aile atölyemizden, yaşam alanınıza.<br/>İhtiyacınızı doğrudan Yunus Usta ile konuşun.</p><div className="v6-hero-actions" onMouseEnter={()=>this.hold(true)} onMouseLeave={()=>this.hold(false)}><ButtonLink to="/projeler" navigate={a.navigate}>Bitirdiğimiz işleri keşfedin</ButtonLink><TextLink to="/modelini-getir" navigate={a.navigate} light>Kendi modelinizi getirin</TextLink></div></div><div className="wrap v6-hero-bottom v234-bottom"><div className="v234-controls" onMouseEnter={()=>this.hold(true)} onMouseLeave={()=>this.hold(false)} data-carousel-state={s.loading!==null?'loading':s.playing?'playing':'paused'}>
 <div className="v234-controls-heading"><span>5 mekânı keşfedin</span><span className="v234-current-scene">{String(s.scene+1).padStart(2,'0')} / 05 · {scene.label}</span></div>
 <div className="v234-control-row"><button type="button" className="v234-arrow v234-previous" aria-label="Önceki görsel" onClick={()=>this.setScene((s.scene+scenes.length-1)%scenes.length)}><Icon size={19}/></button>
 <div className="v6-scene-controls" role="group" aria-label="Açılış sahneleri">{scenes.map((sc,i)=><button key={sc.image} type="button" onClick={()=>this.setScene(i)} aria-pressed={s.scene===i} aria-label={String(i+1).padStart(2,'0')+' '+sc.label+' sahnesi'}><span>{String(i+1).padStart(2,'0')}</span><i/><span className="scene-word">{sc.label}</span></button>)}</div>
 <button type="button" className="v234-arrow v234-next" aria-label="Sonraki görsel" onClick={()=>this.setScene((s.scene+1)%scenes.length)}><Icon size={19}/></button>
 <button type="button" className="v232-pause" aria-label={s.paused?'Otomatik geçişi başlat':'Otomatik geçişi durdur'} aria-pressed={s.paused} onClick={this.togglePlayback}>{s.paused?'Oynat':'Duraklat'}</button></div>
 <div className="v234-progress" aria-hidden="true" data-running={s.playing?'true':'false'}><span key={s.epoch} style={{animationDuration:(this.first?HERO_FIRST_DELAY:HERO_INTERVAL)+'ms'}}/></div>
 {s.loading!==null&&<span className="v234-loading" role="status">Görsel hazırlanıyor…</span>}{s.status&&<span className="v234-loading" role="status">{s.status}</span>}
 </div><span className="v6-hero-caption">{scene.caption}</span><button className="hero-down" aria-label="Bitirdiğimiz işlere kaydır" onClick={()=>document.getElementById('bitirdigimiz-isler')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant' as ScrollBehavior:'smooth'})}><Icon name="down"/></button></div><span className="hero-source">{scene.kind==='concept'?'KONSEPT MODEL':'GERÇEK ÇALIŞMA FOTOĞRAFI / ATÖLYE ARŞİVİ'}</span></section>
 <section id="bitirdigimiz-isler" className="wrap v6-section home-works"><div className="v6-heading"><div><Eyebrow>01 / ATÖLYEDEN YAŞAMA</Eyebrow><h2>Bitirdiğimiz işlerden<br/><em>seçkiler.</em></h2></div><div><p>Yunus Usta’nın gerçek çalışmalarını inceleyin.<br/>İç düzen, kapak ve birleşim ayrıntılarına yakından bakın.</p><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div></div><div className="work-grid">{featuredWorks.map((id,i)=><WorkCard key={id} work={works.find(w=>w.id===id)!} actions={a} featured index={i}/>)}</div></section>

 <section className="home-yunus"><div className="home-yunus-image"><VImage asset="work-joinery" alt="Ahşap kamelya çalışmasından gerçek çatı ve birleşim ayrıntıları" sizes="(max-width: 800px) 100vw, 60vw"/><span>UYGULAMA ARŞİVİNDEN BİR AYRINTI</span></div><div className="home-yunus-copy"><Eyebrow>YUNUS USTA’NIN HİKÂYESİ</Eyebrow><h2>Babadan gelen özen.<br/><em>Her işte aynı niyet.</em></h2><p>“Yaptığım her ürünü sanki kendi evimde kullanacakmış gibi bir özenle yapmaya çalışıyorum. Bu önemli, biz babamızdan böyle gördük.”<br/>Yunus Usta</p><p>Bu özen, mobilyanın görünüşü kadar evde nasıl kullanılacağını da düşünmek demek. Neyi saklayacağınızı, alanınıza hangi ölçünün uyacağını ve beğendiğiniz ayrıntıları birlikte konuşarak başlayalım.</p><TextLink to="/hakkimizda" navigate={a.navigate} light>Hikâyemizi keşfedin</TextLink><div className="yunus-notes"><span>Aile atölyesi</span><span>Ölçüye özel</span><span>Üretim & uygulama</span></div></div></section>
 <section className="wrap v6-section home-inspiration" id="ilham-seckisi"><div className="v6-heading"><div><Eyebrow>02 / İLHAM SEÇKİSİ</Eyebrow><h2>İlham alabileceğiniz<br/><em>modeller.</em></h2></div><div><p>Bir sehpanın formu, kahve köşesinin rafları, antrenin düzeni. Konseptlerde beğendiğiniz ayrıntıyı seçin, kendi alanınıza nasıl uyarlanabileceğini konuşalım.</p><TextLink to="/ilham-modelleri" navigate={a.navigate}>Konseptleri ve Pinterest seçkisini keşfedin</TextLink></div></div><div className="concept-grid three">{homeConcepts.map(c=><ConceptCard key={c.id} c={c} navigate={a.navigate} actions={a}/>)}</div><p className="home-inspiration-note">Tasarım fikirleridir. Bitmiş atölye işleri yukarıdaki çalışma seçkisinde yer alır.</p></section><section className="v6-process"><div className="wrap"><div className="v6-heading"><div><Eyebrow>03 / FİKİRDEN UYGULAMAYA</Eyebrow><h2>Birlikte <em>nasıl ilerleriz?</em></h2></div><p>Bir fotoğrafla başlayabilirsiniz. Kullanımı, ölçüyü ve teklif kapsamını adım adım birlikte netleştirelim.</p></div><div className="process-steps">{[['Fikrinizi dinleriz.','Bir fotoğraf, Pinterest bağlantısı veya çizim paylaşın. Neyi sevdiğinizi ve mobilyayı nasıl kullanacağınızı Yunus Usta’ya anlatın.'],['Ayrıntıları netleştiririz.','Alan ölçüsü, iç düzen, malzeme ve donanımı konuşuruz. Fiyatı belirleyen seçimlerle teklifin neleri kapsayacağını birlikte netleştiririz.'],['Üretimi planlarız.','Son ölçü, tasarım ve kapsam üzerinde anlaştıktan sonra üretim planını konuşuruz. Süreyi seçilen işe göre belirleriz.'],['Yerini birlikte düşünürüz.','Taşıma, teslim ve gerekiyorsa yerinde uygulamayı baştan konuşuruz. Bu işlerin hangilerinin teklife dahil olacağını netleştiririz.']].map(([title,text],i)=><article key={title}><span className="process-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}<TextLink to="/hizmet-ve-teklif" navigate={a.navigate}>Teklif kapsamını birlikte netleştirelim</TextLink></div></div></section>
 <section className="wrap v11-studio-invitation" id="uc-boyutlu-studyo"><div><Eyebrow>3D STÜDYO / ÖLÇÜNÜZE GÖRE</Eyebrow><h2>Bir masa.<br/><em>Size göre yeni bir düzen.</em></h2><p>Masanın ölçülerini ve yüksekliğini değiştirin. Çekmeceyi, döner yan yüzeyi ve kitaplıkları deneyerek çalışırken neye yer ayıracağınızı düşünün.</p><ButtonLink to="/tasarim-masasi" navigate={a.navigate}>3D stüdyoyu keşfet</ButtonLink><small>Görsel bir konsepttir. İmalat ve mekanizma uygunluğu atölye görüşmesinde netleşir.</small></div><Link className="v11-studio-poster" to="/tasarim-masasi" navigate={a.navigate}><Photo name="devir-atolye-v23.webp" alt="Çalışma masası modelinin iki kitaplıklı çalışma ortamı, gerçek Three.js sahnesinden konsept görünümü" ratio="3/2"/><span className="v11-poster-action"><Icon name="grid"/>Keşfet. Döndür. Birlikte düşün.</span><SourceTag kind="concept"/></Link></section>
 <section className="v6-final-cta"><div className="wrap"><Eyebrow>SİZİN FİKRİNİZ. BİZİM USTALIĞIMIZ.</Eyebrow><h2>Kendi modelinizi getirin.<br/><em>Üzerinde birlikte çalışalım.</em></h2><ButtonLink to="/modelini-getir" navigate={a.navigate}>Fikrimi paylaşayım</ButtonLink><p>Bir fotoğraf, Pinterest bağlantısı ya da çizim yeterli. Beğendiğiniz ayrıntıyı ve değiştirmek istediğiniz şeyi anlatın. Alanınıza göre birlikte düşünelim.</p><TextLink to="/iletisim" navigate={a.navigate} light>Doğrudan Yunus Usta ile görüşün</TextLink></div></section>
 </div>}
}
