import {BedCollection} from './BedCollection';
import {ServiceGuide} from '../components/ServiceGuide';
import {serviceContent} from '../lib/service-content';
import {ScopeNotes,CategoryDecision,categorySupport} from './V7Pages';
import {ResilientImage} from '../components/ResilientImage';
import {pinLookup,pinReferenceUrl} from '../lib/pinterest';
import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Dialog,Accordion,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,workCategories,concepts,inspirationConcepts,pinterestReferences,visiblePinterestReferences,workPhotoEvidence,workDisplayStage,prioritizeWorks,categoryName,modelHref,type Work} from '../lib/portfolio';
import {inspirationTarget,targetElementId} from '../lib/selections';
import {searchKey,publicHref} from '../lib/domain';

const projectStudies:Record<string,{focus:string;observations:string[];questions:string[]}>={
 'sade-kose-mutfak':{focus:'Köşe planında günlük akış.',observations:['L biçimindeki tezgâh, iki duvar boyunca çalışma ve depolama alanını birleştiriyor.','Açık renkli kapaklar ile koyu cihaz yüzeyleri aynı yerleşimde görülüyor.','Alt dolaplar, üst depolama ve cihaz boşlukları birlikte düşünülmüş bir düzen oluşturuyor.'],questions:['Mevcut tesisat ve cihaz yerleri korunacak mı?','Tezgâhta hangi işleri daha sık yapıyorsunuz?','Kapak, çekmece ve erişim öncelikleriniz neler?']},
 'kemerli-kahve-kosesi':{focus:'Servis, sergileme ve saklama bir arada.',observations:['Kemerli orta bölüm, açık rafları ve servis yüzeyini bir odak noktasında topluyor.','İki yandaki cam kapaklı bölümler, sergileme ile kapalı saklamayı aynı kompozisyonda birleştiriyor.','Raf aydınlatması ve alt depolama, fotoğraftaki kahve köşesinin belirgin ayrıntıları.'],questions:['Makinenizin en, derinlik ve kapağı açıldığındaki yüksekliği nedir?','Fincanlar, kahve malzemeleri ve küçük cihazlar için ne kadar yer gerekiyor?','Priz, havalandırma veya su bağlantısı için özel ihtiyaç var mı?']},
 'isikli-tv-unitesi':{focus:'Ekran duvarını bir bütüne dönüştürmek.',observations:['TV paneli, yan raflar ve alttaki depolama tek bir duvar düzeninde bir araya geliyor.','Açık raf ile kapalı hacimlerin birlikte kullanımı, görünen ve saklanan eşyalar arasında ayrım sağlıyor.','Dolaylı aydınlatma, panel ve rafların çevresinde ayrı bir ışık katmanı oluşturuyor.'],questions:['Ekranın boyutu, ağırlığı ve duvarın yapısı nedir?','Prizler, kablolar ve kullanılacak cihazlar nerede duracak?','Kitap, oyun konsolu ve diğer eşyalar için açık veya kapalı alan mı gerekiyor?']}
};
function ProjectStudy({work:w,navigate}:{work:Work;navigate:(p:string)=>void}){const study=projectStudies[w.id],preparation=!study&&serviceContent[w.category]?.preparation,c=study||{focus:w.subtitle,observations:w.features,questions:preparation||['Bu mobilya hangi alanda ve nasıl kullanılacak?','Mevcut alanın yaklaşık ölçüsü ve engelleri neler?','Bu modelde hangi ayrıntıyı korumak, hangisini değiştirmek istersiniz?']};return <section className="wrap v11-case-study"><div><Eyebrow>FOTOĞRAFTAN KARARINIZA</Eyebrow><h2>{c.focus}</h2><p>{w.description}</p><p className="field-hint">Bu işte beğendiğiniz ayrıntıyı seçin. Kendi alanınızda nasıl kullanılacağını birlikte konuşalım.</p></div><div className="v11-case-columns"><article><span className="eyebrow">BU UYGULAMADA GÖRÜNENLER</span><h3>Nasıl bir çözüm?</h3>{c.observations.map(t=><p key={t}>{t}</p>)}</article><article><span className="eyebrow">SİZİN ALANINIZ İÇİN</span><h3>{preparation?'İlk görüşme için hazırlayın.':'İlk görüşmede konuşalım.'}</h3><ol>{c.questions.map(t=><li key={t}>{t}</li>)}</ol><p>Yaklaşık ölçü veya mekân fotoğrafıyla başlanabilir. Üretim ölçüsü ayrıca teyit edilir.</p></article></div><details className="v11-case-verification"><summary>Malzeme, kapsam ve fotoğraf bilgisi</summary><p>Bu fotoğraf Yunus Usta’nın paylaştığı iş arşivindendir. Yeni projenizde gövde, kapak, yüzey ve donanımı ayrı ayrı seçebiliriz. Cihaz, tezgâh, aydınlatma, nakliye ve montajdan hangilerinin teklife dahil olduğunu görüşmede netleştirelim.</p></details><nav className="case-next-links" aria-label="Projeden sonraki adım"><TextLink to={'/projeler?alan='+w.category} navigate={navigate}>Bu alanı keşfedin</TextLink><TextLink to="/malzemeler" navigate={navigate}>Malzeme kararları</TextLink><TextLink to={modelHref('',w.category,w.subtitle+' benzeri bir çalışma istiyorum.')} navigate={navigate}>Kendi alanım için konuşalım</TextLink></nav></section>}
export class Projects extends Component<PageProps&{query?:string},{category:string;search:string;stage:string}>{
 constructor(p:any){super(p);const q=new URLSearchParams(p.query||'');this.state={category:workCategories.some(c=>c.id===q.get('alan'))?q.get('alan')!:'all',search:q.get('ara')||'',stage:q.get('durum')==='process'?'process':'work'}}
 update=(key:'category'|'search'|'stage',value:string)=>this.setState(previous=>{const next={...previous,[key]:value};if(key==='stage'&&next.category!=='all'&&!works.some(w=>w.category===next.category&&workDisplayStage(w)===value))next.category='all';return next;},()=>{const s=this.state,q=new URLSearchParams();if(s.category!=='all')q.set('alan',s.category);if(s.search)q.set('ara',s.search);if(s.stage!=='work')q.set('durum',s.stage);history.replaceState({...history.state},'',publicHref('/projeler'+(q.size?'?'+q:'')))});
 render(){const a=this.props,s=this.state,list=prioritizeWorks(works.filter(w=>(s.category==='all'||w.category===s.category)&&workDisplayStage(w)===s.stage&&searchKey(w.title+' '+w.subtitle+' '+categoryName(w.category)).includes(searchKey(s.search))));return <>
 <header className="v6-page-head wrap discovery-head"><Eyebrow>ELİF / YUNUS USTA’NIN YAPTIĞI İŞLER</Eyebrow><div><h1>{s.stage==='process'?<>Uygulama<br/><em>aşamaları.</em></>:<>Bitirdiğimiz işlerden<br/><em>seçkiler.</em></>}</h1><p>Bu bölümde Yunus Usta’nın yaptığı mobilyaları, gerçek çalışma fotoğraflarıyla görüyorsunuz. Kurulum sırasında çekilen kareler, Uygulama Aşamaları bölümünde ayrı yer alır.</p></div></header>
 <section className="wrap portfolio-section"><div className="portfolio-toolbar"><div className="view-segments" role="group" aria-label="Proje durumu"><button onClick={()=>this.update('stage','work')} aria-pressed={s.stage==='work'}>Bitirdiğimiz İşler</button><button onClick={()=>this.update('stage','process')} aria-pressed={s.stage==='process'}>Uygulama Aşamaları</button></div><label className="portfolio-search"><Icon name="search"/><input type="search" value={s.search} maxLength={100} onInput={e=>this.update('search',e.currentTarget.value)} placeholder="Bir çalışma arayın" aria-label="Projelerde ara"/></label></div>
 <div className="filter-chips" role="group" aria-label="Proje kategorisi">{[{id:'all',name:'Tüm alanlar'},...workCategories.filter(c=>works.some(w=>w.category===c.id&&workDisplayStage(w)===s.stage))].map(c=><button key={c.id} onClick={()=>this.update('category',c.id)} aria-pressed={s.category===c.id}>{c.name}</button>)}</div>
 <div className="result-line" aria-live="polite"><span>{list.length} çalışma</span><span>Gerçek fotoğraflar, atölyenin paylaştığı arşivden.</span></div>
 {list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="v6-empty"><Icon name="search" size={34}/><h2>Bu seçimde henüz bir çalışma yok.</h2><p>Kategorinin ilham fikirlerini inceleyebilir veya kendi modelinizle başlayabilirsiniz.</p><button className="button button-outline" onClick={()=>this.setState({category:'all',search:'',stage:'work'},()=>history.replaceState({...history.state},'',publicHref('/projeler')))}>Filtreleri temizle <Icon/></button>{s.category!=='all'&&<TextLink to={'/ilham-modelleri?alan='+s.category} navigate={a.navigate}>Bu alanın ilham modellerini inceleyin</TextLink>}<TextLink to={modelHref('',s.category==='all'?'ozel-tasarim':s.category)} navigate={a.navigate}>Kendi modelimle başlayayım</TextLink></div>}
 </section><ModelCallout navigate={a.navigate} compact/></>}
}
export class WorkDetail extends Component<PageProps&{work:Work},{photo:number;zoom:boolean}>{
 state={photo:0,zoom:false};move=(delta:number)=>this.setState(s=>({photo:(s.photo+delta+this.props.work.images.length)%this.props.work.images.length}));
 render(){const a=this.props,w=a.work,saved=a.favorites.includes('work:'+w.id),photo=workPhotoEvidence(w,this.state.photo),others=prioritizeWorks(works.filter(p=>p.category===w.category&&p.id!==w.id&&workDisplayStage(p)==='work')).slice(0,3);return <>
 <div className="wrap v6-crumb"><Link to={workDisplayStage(w)==='process'?'/projeler?durum=process':'/projeler'} navigate={a.navigate}>{workDisplayStage(w)==='process'?'Uygulama Aşamaları':'Bitirdiğimiz işler'}</Link><span>/</span><Link to={'/projeler?alan='+w.category} navigate={a.navigate}>{categoryName(w.category)}</Link></div>
 <section className="wrap work-detail"><div className="work-detail-media"><button className="work-main-photo" onClick={()=>this.setState({zoom:true})} aria-label="Proje fotoğrafını büyüt"><VImage asset={w.images[this.state.photo]} alt={w.subtitle+'. '+photo.caption} eager full/><span><Icon name="plus"/>Fotoğrafı incele</span></button>{w.images.length>1&&<div className="work-thumbnails">{w.images.map((im,i)=><button key={im} onClick={()=>this.setState({photo:i})} aria-label={'Fotoğraf '+(i+1)} aria-pressed={i===this.state.photo}><VImage asset={im} alt="" sizes="100px"/></button>)}</div>}<p className="photo-credit" aria-live="polite">{this.state.photo+1} / {w.images.length}. {photo.caption}</p></div>
 <div className="work-detail-copy"><SourceTag kind={photo.kind}/><Eyebrow>{categoryName(w.category)}</Eyebrow><h1>{w.title}</h1><p className="work-lead">{w.description}</p><dl className="work-facts"><div><dt>Çalışma</dt><dd>{w.subtitle}</dd></div><div><dt>Yaklaşım</dt><dd>Ölçü ve ihtiyaca göre değerlendirme</dd></div><div><dt>Malzeme & ölçü</dt><dd>Yeni teklifinizde birlikte netleştirilir</dd></div></dl><div className="work-features">{w.features.map(f=><span key={f}><Icon name="check" size={16}/>{f}</span>)}</div><div className="action-row"><ButtonLink to={modelHref('',w.category,w.subtitle+' benzeri bir çalışma istiyorum.')} navigate={a.navigate}>Benzerini birlikte düşünelim</ButtonLink><button type="button" className="v7-save-text" aria-label={(saved?'İlham dosyanızda. Kaydı kaldır. ':'İlham dosyama ekle. ')+w.subtitle} aria-pressed={saved} onClick={()=>a.favorite('work:'+w.id)}><Icon name="heart" size={18}/>{saved?'İlham dosyanızda':'İlham dosyama ekle'}</button></div><p className="fineprint">Alanınızın ölçüsü, iç düzen, yüzey ve donanım seçimleri yeni projenizin kapsamını belirler. Beğendiğiniz ayrıntıyı Yunus Usta’ya göstererek başlayabilirsiniz.</p></div>
 </section><ProjectStudy work={w} navigate={a.navigate}/><div className="wrap"><ScopeNotes category={w.category}/></div>{others.length>0&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>AYNI ALANDAN</Eyebrow><h2>Biraz daha <em>keşfedin.</em></h2></div><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div><div className="work-grid">{others.map((p,i)=><WorkCard key={p.id} work={p} actions={a} index={i}/>)}</div></section>}
 <ModelCallout navigate={a.navigate} compact/>
 {this.state.zoom&&<Dialog title={w.subtitle} onClose={()=>this.setState({zoom:false})} onKeyDown={e=>{if(w.images.length>1&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();this.move(e.key==='ArrowRight'?1:-1)}}}><div className="v6-lightbox"><VImage asset={w.images[this.state.photo]} alt={w.subtitle+' büyük görünüm'} eager full sizes="95vw"/>{w.images.length>1&&<div><button className="icon-button" aria-label="Önceki fotoğraf" onClick={()=>this.move(-1)}><span className="reverse-arrow"><Icon/></span></button><span>{this.state.photo+1} / {w.images.length}</span><button className="icon-button" aria-label="Sonraki fotoğraf" onClick={()=>this.move(1)}><Icon/></button></div>}<p>{photo.caption} {this.state.photo+1} / {w.images.length}</p></div></Dialog>}
 </>}
}
const conceptQuestions:Record<string,string[]>={
 'sehpa':['Koltuk ile sehpa arasında nasıl bir geçiş alanı gerekiyor?','Tek parça mı, gerektiğinde ayrılan yüzeyler mi?'],
 'kahve-kosesi':['Makineniz ve kapağı açıldığında gereken boşluk ne kadar?','Neleri sergilemek, neleri kapalı saklamak istersiniz?'],
 'vestiyer':['Oturmak, ayakkabı koymak ve asmak için ne kadar yer gerekiyor?','Giriş kapısı ile dolap kapakları rahat açılabiliyor mu?'],
 'tv-unitesi':['Ekran, priz ve kablolar nerede duracak?','Açık raf ile kapalı depolama arasında nasıl bir denge istersiniz?'],
 'mutfak':['Cihaz ve tesisat yerleri korunacak mı?','Hazırlık yüzeyi ile depolamada önceliğiniz ne?'],
 'gardrop':['Askı, raf ve çekmece ihtiyacınız nasıl dağılıyor?','Kapak açılımı ve geçiş için ne kadar alan var?'],
 'pergola':['Alanın yaklaşık açıklığı ve zemini nasıl?','Gölge, oturma düzeni ve hava koşulları için beklentiniz ne?'],
 'ozel-tasarim':['Günlük kullanımda kaç kişilik bir alan gerekiyor?','Beğendiğiniz biçimde neyi korumak istersiniz?']
};
export class ConceptCard extends Component<{c:typeof concepts[number];navigate:(p:string)=>void;actions?:PageProps},{preview:boolean}>{
 state={preview:false};
 render(){const {c,navigate,actions}=this.props,bed=c.category==='baza-yatak',id='concept:'+c.id,inquiry=modelHref('',c.category,c.subtitle+' üzerine konuşmak istiyorum.',id),saved=!!actions?.favorites.includes(id);
 const destination=bed?'/kategoriler/baza-yatak?model='+encodeURIComponent(c.id):inquiry;
 const save=()=>actions&&<button type="button" className="v7-save-text" aria-label={(saved?'İlham dosyasından çıkar. ':'İlham dosyama ekle. ')+c.subtitle} aria-pressed={saved} onClick={()=>actions.favorite(id)}><Icon name="heart" size={18}/>{saved?'İlham dosyanızda':'İlham dosyama ekle'}</button>;
 return <><article className={'concept-card'+(bed?' concept-card-bed':'')} id={targetElementId(id)} tabIndex={-1} data-concept={c.id} data-category={c.category}>
 <Link to={destination} navigate={bed?navigate:()=>this.setState({preview:true})} className="concept-image" aria-label={bed?c.title+' açık ve kapalı görünümlerini incele':c.subtitle+' ayrıntılarını incele'} aria-haspopup={bed?undefined:'dialog'}><VImage asset={c.image} alt={c.subtitle+', konsept model'} sizes="(max-width: 680px) 90vw, (max-width: 1100px) 45vw, 30vw"/><SourceTag kind="concept"/><span className="concept-open"><Icon name="diagonal"/></span></Link>
 <div className="concept-caption"><span>{categoryName(c.category)}</span><h3>{c.title}</h3><TextLink to={inquiry} navigate={navigate}>Bu fikirle başlayalım</TextLink>{save()}</div></article>
 {this.state.preview&&<Dialog title={c.subtitle} onClose={()=>this.setState({preview:false})}><div className="concept-preview"><div className="concept-preview-media"><VImage asset={c.image} alt={c.subtitle+', büyük konsept görünümü'} full eager sizes="(max-width: 800px) 90vw, 55vw"/></div><div className="concept-preview-copy"><SourceTag kind="concept"/><h3>{c.title}</h3><p>Bu fikri kendi alanınıza göre düşünürken:</p><ul>{(conceptQuestions[c.category]||[]).map(q=><li key={q}>{q}</li>)}</ul><ButtonLink to={inquiry} navigate={p=>{this.setState({preview:false});navigate(p)}}>Bu fikirle başlayalım</ButtonLink>{save()}<p className="concept-preview-note">Temsili tasarım görselidir. Tamamlanmış atölye işi değildir. Ölçü, malzeme ve uygulanabilirlik birlikte değerlendirilir.</p><TextLink to={'/ilham-modelleri?alan='+c.category} navigate={p=>{this.setState({preview:false});navigate(p)}}>Bu alanı keşfedin</TextLink></div></div></Dialog>}
 </>}
}
export function Categories(a:PageProps&{slug?:string;query?:string}){
 if(a.slug==='baza-yatak')return <BedCollection {...a}/>;
 const cat=workCategories.find(c=>c.id===a.slug);
 if(cat){const list=prioritizeWorks(works.filter(w=>w.category===cat.id&&workDisplayStage(w)==='work')),ideas=concepts.filter(c=>c.category===cat.id);return <>
 <section className="category-hero"><VImage asset={categorySupport[cat.id]?.asset||cat.image} alt={cat.name+(categorySupport[cat.id]?' atölye fotoğrafı':' için temsili tasarım sahnesi')} eager sizes="100vw"/><div className="category-shade"/><div className="wrap"><Link className="v6-backlink" to="/kategoriler" navigate={a.navigate}>Kategoriler <Icon size={16}/></Link><Eyebrow>ÖLÇÜNÜZE, ALANINIZA, SİZE</Eyebrow><h1>{cat.name}</h1><p>{cat.line}</p></div><SourceTag kind={categorySupport[cat.id]?'work':'concept'}/></section>
 <nav className="wrap category-browse-nav" aria-label="Kategori içeriği"><a href="#category-works">Atölye işleri</a>{ideas.length>0&&<a href="#category-ideas">Konsept fikirler</a>}<a href="#category-guide">Ölçü ve kullanım rehberi</a></nav><section className="wrap v6-section" id="category-works"><div className="v6-heading"><div><Eyebrow>ATÖLYEDEN</Eyebrow><h2>{cat.short} için<br/><em>düşündüklerimiz.</em></h2></div><p>{cat.detail}</p></div>{list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="category-no-work"><p>Bu kategoride paylaşılmış bir bitmiş iş fotoğrafı henüz yok. Aşağıdaki konseptleri başlangıç noktası olarak inceleyebilirsiniz.</p><TextLink to={modelHref('',cat.id)} navigate={a.navigate}>Kendi fikrimle başlayayım</TextLink></div>}</section>
 {ideas.length>0&&<section className="concept-band" id="category-ideas"><div className="wrap"><div className="v6-heading"><div><Eyebrow>TEMSİLİ TASARIM SEÇKİSİ</Eyebrow><h2>Bir başlangıç <em>fikri.</em></h2></div><p>Bu görseller konsept modeldir. Atölyenin tamamladığı işler değildir. Üretilebilirlik ve ayrıntılar birlikte değerlendirilir.</p></div><div className="concept-grid">{ideas.map(c=><ConceptCard key={c.id} c={c} navigate={a.navigate} actions={a}/>)}</div></div></section>}<div id="category-guide"><CategoryDecision category={cat.id} navigate={a.navigate}/><ServiceGuide category={cat.id} navigate={a.navigate}/></div><ModelCallout navigate={a.navigate}/></>}
 return <><header className="v6-page-head wrap"><Eyebrow>ELİF / YAŞAM ALANLARI</Eyebrow><div><h1>Evin her köşesine.<br/><em>Size göre.</em></h1><p>Mutfaktan bir fincan kahveye ayrılan köşeye. Hazır bir ölçüye sığmak yerine, alanınızdan ve ihtiyacınızdan başlayalım.</p></div></header><section className="wrap v6-section categories-index"><div className="category-grid">{workCategories.map((c,i)=><Link key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate} className="category-tile"><div><VImage asset={categorySupport[c.id]?.asset||c.image} alt={c.name+(categorySupport[c.id]?' atölye arşivi':' konsepti')} sizes="(max-width: 680px) 90vw, 30vw"/><SourceTag kind={categorySupport[c.id]?'work':'concept'}/></div><span className="category-number">{String(i+1).padStart(2,'0')}</span><h2>{c.name}</h2><p>{c.line}</p><Icon name="diagonal"/></Link>)}</div><div className="category-index-more"><TextLink to="/ilham-modelleri" navigate={a.navigate}>Tüm ilham modellerini keşfedin</TextLink><p>Farklı alanlar için konseptler ve kaynağı korunan Pinterest seçkileri.</p></div></section><ModelCallout navigate={a.navigate}/></>
}
export class Inspiration extends Component<PageProps&{query?:string},{category:string;pinCategory:string;expanded:boolean;preview:string}>{
 state={category:'all',pinCategory:'all',expanded:false,preview:''};
 componentDidMount(){this.focusTarget()}
 componentDidUpdate(previous:PageProps&{query?:string}){if(previous.query!==this.props.query)this.focusTarget()}
 focusTarget=()=>{
  const query=new URLSearchParams(this.props.query||'');const target=inspirationTarget(query.get('hedef'));if(!target){this.setState({category:workCategories.some(c=>c.id===query.get('alan'))?query.get('alan')!:'all'});return;}
  const pin=target.kind==='reference'?pinterestReferences.find(p=>'pin:'+p.id===target.id):null;
  this.setState({category:target.kind==='concept'?target.category:'all',pinCategory:'all',expanded:!!pin&&pin.group!=='atelier'},()=>{
   requestAnimationFrame(()=>requestAnimationFrame(()=>{const el=document.getElementById(targetElementId(target.id));if(el){el.classList.add('v11-target');el.focus({preventScroll:true});el.scrollIntoView({block:'center',behavior:'instant' as ScrollBehavior});}}));
  });
 };
 pinCard=(p:typeof pinterestReferences[number])=>{
  const a=this.props,meta=pinLookup[p.id],title=meta?.label||p.title;
  return <article className="pin-card pin-curated-card" key={p.id} id={targetElementId('pin:'+p.id)} tabIndex={-1} data-pin={p.id}>
   {meta?.image?<button type="button" className="pin-visual" aria-label={title+' görselini büyüt'} aria-haspopup="dialog" onClick={()=>this.setState({preview:p.id})}><ResilientImage src={meta.image} alt={title+'. Pinterest dış referansı.'} loading="lazy" decoding="async" referrerPolicy="no-referrer"/><span className="pin-zoom"><Icon name="plus" size={16}/> İncele</span></button>:<a className="pin-source-fallback" href={pinReferenceUrl(p.id)} target="_blank" rel="noopener noreferrer">Modeli Pinterest kaynağında inceleyin <Icon name="diagonal"/></a>}
   <div className="pin-card-copy"><span className="eyebrow pin-source-label">{p.group==='atelier'?'USTANIN SEÇKİSİ':'PINTEREST SEÇKİSİ'} / DIŞ REFERANS</span><h3>{title}</h3>
   {meta?.note&&<p className="pin-design-note">{meta.note}</p>}{meta?.credit&&<p className="pin-credit">{meta.credit}</p>}{meta?.aiLabel&&<p className="pin-ai-note">Kaynakta yapay zekâ ile değiştirildi olarak etiketlenmiş.</p>}
   <button className="v7-save-text" aria-label={(a.favorites.includes('pin:'+p.id)?'İlham dosyanızda. Kaydı kaldır. ':'İlham dosyama ekle. ')+title} aria-pressed={a.favorites.includes('pin:'+p.id)} onClick={()=>a.favorite('pin:'+p.id)}><Icon name="heart" size={18}/>{a.favorites.includes('pin:'+p.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button>
   <div className="pin-card-actions"><a href={pinReferenceUrl(p.id)} target="_blank" rel="noopener noreferrer" className="text-link">Pinterest'te incele <Icon name="diagonal" size={17}/></a><TextLink to={modelHref(pinReferenceUrl(p.id),p.category)} navigate={a.navigate}>Bu fikir üzerine çalışalım</TextLink></div></div>
  </article>;
 };
 render(){const a=this.props,s=this.state,items=inspirationConcepts(s.category),atelier=pinterestReferences.filter(p=>p.group==='atelier'),first=atelier.filter(p=>s.pinCategory==='all'||p.category===s.pinCategory),rest=pinterestReferences.filter(p=>p.group!=='atelier'),preview=pinterestReferences.find(p=>p.id===s.preview),meta=preview?pinLookup[preview.id]:undefined;return <>
 <header className="v6-page-head wrap discovery-head inspiration-heading"><Eyebrow>ELİF / İLHAM DEFTERİ</Eyebrow><div><h1>İlham alabileceğiniz<br/><em>modeller.</em></h1><p>Bir kapak çizgisi, bir kahve köşesi, iyi düşünülmüş bir raf. Beğendiğiniz ayrıntıyla başlayın, kendi alanınız için birlikte şekillendirelim.</p></div><div className="inspiration-entry-actions"><ButtonLink to="/modelini-getir" navigate={a.navigate}>Kendi modelimi getireyim</ButtonLink><nav className="inspiration-jump-links" aria-label="İlham seçkileri"><a href="#konsept-seckisi">Konsept fikirler</a><a href="#pinterest-seckileri">Pinterest seçkileri</a></nav></div></header>
 <section className="wrap v6-section inspiration-concepts" id="konsept-seckisi"><div className="v6-heading"><div><h2>Konsept <em>fikirler.</em></h2></div><p>Görsele dokunup ayrıntıları inceleyin. Konseptler tamamlanmış atölye işi değildir.</p></div><div className="filter-chips" role="group" aria-label="İlham kategorisi">{[{id:'all',name:'Tüm alanlar'},...workCategories].map(c=><button key={c.id} aria-pressed={c.id===s.category} onClick={()=>this.setState({category:c.id})}>{c.name}</button>)}</div><p className="inspiration-result" role="status" aria-live="polite">{s.category==='all'?items.length+' alan, '+items.length+' başlangıç fikri. Diğer modeller kategori içinde.':categoryName(s.category)+' için '+items.length+' konsept model.'}</p><div className="concept-grid">{items.map(c=><ConceptCard c={c} key={c.id} navigate={a.navigate} actions={a}/>)}</div>{s.category==='baza-yatak'&&<div className="inspiration-category-link"><TextLink to="/kategoriler/baza-yatak" navigate={a.navigate}>Baza koleksiyonunun açık ve kapalı görünümlerini inceleyin</TextLink></div>}</section>
 <section className="pinterest-section" id="pinterest-seckileri"><div className="wrap"><div className="v6-heading"><div><Eyebrow>YUNUS USTA'NIN İLHAM DEFTERİ</Eyebrow><h2>Pinterest'ten<br/><em>ustanın seçtikleri.</em></h2></div><p>Ustanın beğendiği modeller ve üzerinde birlikte düşünebileceğimiz ayrıntılar. Bunlar dış kaynaklardan ilham örnekleri. Yaptığımız işleri Bitirdiğimiz İşler bölümünde bulabilirsiniz.</p></div>
 <div className="filter-chips pin-filters" role="group" aria-label="Pinterest kategorisi">{[{id:'all',name:'Tüm seçimler'},...workCategories.filter(c=>atelier.some(p=>p.category===c.id))].map(c=><button key={c.id} aria-pressed={c.id===s.pinCategory} onClick={()=>this.setState({pinCategory:c.id})}>{c.name}</button>)}</div>
 <p className="pin-count" role="status" aria-live="polite">Ustanın seçkisinden {first.length} model. Görsele dokunarak büyütebilirsiniz.</p>
 <div className="pin-grid pin-selection-grid">{first.map(this.pinCard)}</div>
 {rest.length>0&&<details className="pin-more" open={s.expanded} onToggle={e=>{if(e.currentTarget.open!==this.state.expanded)this.setState({expanded:e.currentTarget.open})}}><summary aria-controls="pin-expanded-list">{s.expanded?'Diğer Pinterest fikirlerini daralt':'Birlikte keşfettiğimiz '+rest.length+' fikir daha'} <Icon name="plus" size={18}/></summary><div className="pin-grid" id="pin-expanded-list">{rest.map(this.pinCard)}</div></details>}
 <p className="pin-note" id="pinterest-disclosure">Görseller Pinterest'in görsel sunucusundan otomatik görüntülenir. Kaynakları kartlarda yer alır. Görsel açılmazsa Pinterest bağlantısını kullanabilirsiniz. <Link to="/gizlilik" navigate={a.navigate}>Dış servis bilgisi</Link></p>
 </div></section><ModelCallout navigate={a.navigate}/>
 {preview&&meta&&<Dialog title={meta.label} onClose={()=>this.setState({preview:''})}><div className="concept-preview pin-preview"><div className="concept-preview-media">{meta.image&&<ResilientImage src={meta.image} alt={meta.label+'. Pinterest dış referansı.'} referrerPolicy="no-referrer"/>}{meta.image&&<a className="text-link pin-full-image" href={meta.image} target="_blank" rel="noopener noreferrer">Görseli tam boy aç <Icon name="diagonal"/></a>}</div><div className="concept-preview-copy"><SourceTag kind="reference"/><h3>{meta.label}</h3><p>{meta.note||'Beğendiğiniz ayrıntıyı kendi alanınız için birlikte değerlendirelim.'}</p><p>Bu modelde neyi koruyalım, neyi değiştirelim?</p><ul>{(conceptQuestions[preview.category]||conceptQuestions['ozel-tasarim']).map(q=><li key={q}>{q}</li>)}</ul><ButtonLink to={modelHref(pinReferenceUrl(preview.id),preview.category)} navigate={p=>{this.setState({preview:''});a.navigate(p)}}>Bu fikir üzerine çalışalım</ButtonLink><p className="concept-preview-note">Pinterest'ten bir ilham örneğidir. Atölyemizin tamamladığı bir iş değildir. Ölçü, malzeme ve uygulanabilirliği kendi projeniz için görüşelim.</p>{meta.aiLabel&&<p className="pin-ai-note">Kaynakta yapay zekâ ile değiştirildi olarak etiketlenmiş.</p>}<a className="text-link" href={pinReferenceUrl(preview.id)} target="_blank" rel="noopener noreferrer">Pinterest kaynağını aç <Icon name="diagonal"/></a></div></div></Dialog>}
 </>}
}
export function AboutAtelier(a:PageProps&{atelier?:boolean}){return <>
 <header className="v6-page-head wrap" data-atelier-view={a.atelier?'process':'story'}><Eyebrow>{a.atelier?'ELİF / TEZGÂHTAN MEKÂNA':'ELİF / AİLEDEN GELEN USTALIK'}</Eyebrow><div><h1>{a.atelier?<>Bir fikrin<br/><em>şekil aldığı yer.</em></>:<>Bir meslekten fazlası.<br/><em>Bir aile mirası.</em></>}</h1><p>{a.atelier?'Paylaşılan uygulama kareleri üzerinden, yerleşimden montaj ayrıntısına. İşin yalnız son görünümüne değil, oluşma aşamalarına da bakalım.':"Yunus Usta'nın babasından öğrendiği marangozluk, bugün farklı yaşam alanlarında devam ediyor. Hazır bir kalıp değil, ihtiyaca göre düşünülmüş bir çalışma."}</p></div></header>
 <section className="atelier-documentary"><div className="atelier-documentary-image"><VImage asset="work-joinery" alt="Atölyenin ahşap kamelya uygulamasındaki çatı birleşimi ayrıntısı" eager sizes="70vw"/><SourceTag kind="process"/></div><div><Eyebrow>{a.atelier?'ARŞİVDEN BİR UYGULAMA AYRINTISI':"YUNUS USTA'NIN ELİNDEN ÇIKANLAR"}</Eyebrow><h2>{a.atelier?<>Görünen yüzeyin<br/><em>arkasındaki düzen.</em></>:<>Kendi evine<br/><em>yapar gibi.</em></>}</h2>
 {a.atelier?<><p>Bu kare, ahşap kamelyanın çatı altı birleşimlerini gösteriyor. Diğer uygulama fotoğraflarında dolap yerleşimi, koruyucu filmler ve kurulum ayrıntıları görülebilir.</p><p>Bir mobilyanın iyi görünmesi kadar, yerine oturması ve rahat kullanılması da önemlidir. Kendi projenizde ölçüyü, malzemeyi, bağlantıları ve montaj kapsamını birlikte netleştiririz.</p><TextLink to="/hakkimizda" navigate={a.navigate}>Aile hikâyemizi keşfedin</TextLink></>:<><blockquote className="atelier-quote"><p>“Yaptığım her ürünü sanki kendi evimde kullanacakmış gibi bir özenle yapmaya çalışıyorum. Bu önemli, biz babamızdan böyle gördük.”</p><cite>Yunus Usta</cite></blockquote><p>Yunus Usta, yaptığı her parçaya kendi evinde kullanacakmış gibi özen gösterir. Bir dolabın nasıl açılacağını, bir rafın ne taşıyacağını, bir köşenin günlük yaşamda nasıl kullanılacağını birlikte konuşarak başlarız.</p><p>Mesleğin aileden gelen bilgisini, sizin alanınızın ihtiyacıyla buluştururuz. Bir çizim hazırlamanız şart değil. Beğendiğiniz ayrıntıyı ve neyi değiştirmek istediğinizi doğrudan Yunus Usta ile konuşabilirsiniz.</p><TextLink to="/atolye" navigate={a.navigate}>Atölye sürecini inceleyin</TextLink></>}
 </div></section>
 <section className="wrap atelier-values">{(a.atelier?[
 ['Ölçüyü konuşmak.','Yaklaşık ölçü ve mekân fotoğrafı başlangıçtır. İmalata esas ölçüler, uygulama öncesinde ayrıca netleştirilir.'],
 ['Ayrıntıyı ayırmak.','Gövde, yüzey, kapak ve donanım farklı kararlardır. Görselde beğendiğiniz ayrıntının nasıl uygulanacağını görüşmede sorun.'],
 ['Kapsamı netleştirmek.','Nakliye, yerinde montaj ve varsa diğer işler aynı şey değildir. Hangi işin kimin sorumluluğunda olduğu teklifte belirlenir.']
 ]:[
 ['Aile atölyesi.','Nesilden nesile aktarılan meslek bilgisi. Doğrudan ustayla konuşarak ilerleyen bir süreç.'],
 ['Ölçüye özel.','Alanınızın ihtiyacından başlar, kullanım biçiminize göre şekillendiririz.'],
 ['Birlikte karar.','Hazır bir modele bağlı kalmak yerine, neyi korumak ve neyi değiştirmek istediğinizi konuşuruz.']
 ]).map(([title,text],i)=><div key={title}><span>0{i+1}</span><h2>{title}</h2><p>{text}</p></div>)}</section>
 {a.atelier&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>UYGULAMA ARŞİVİ</Eyebrow><h2>Uygulama fotoğrafları.<br/><em>İşin içinden.</em></h2></div><p>Bu kareler uygulama aşamasını gösterir. Bitmiş projelerin tanıtım çekimleri olarak sunulmaz.</p></div><div className="work-grid">{works.filter(w=>workDisplayStage(w)==='process').map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div><TextLink to="/projeler?durum=process" navigate={a.navigate}>Uygulama arşivini açın</TextLink></section>}
 <div className="wrap address-note"><Icon name="pin" size={28}/><div><h2>İstanbul'da, yeni atölyemize hazırlanıyoruz.</h2><p>Yeni atölye adresi netleştiğinde burada paylaşılacak. Ziyaret öncesinde Yunus Usta ile görüşerek adresi ve uygunluğu teyit edin. Projenizi bir fikir ve yaklaşık ölçüyle hazırlamaya başlayabilirsiniz.</p></div></div><ModelCallout navigate={a.navigate}/></>}
