import {BedCollection} from './BedCollection';
import {ServiceGuide} from '../components/ServiceGuide';
import {ScopeNotes,CategoryDecision,categorySupport} from './V7Pages';
import {PinterestPreview} from '../components/PinterestPreview';
import {pinLookup} from '../lib/pinterest';
import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Dialog,Accordion,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,workCategories,concepts,inspirationConcepts,pinterestReferences,visiblePinterestReferences,workPhotoEvidence,categoryName,modelHref,type Work} from '../lib/portfolio';
import {inspirationTarget,targetElementId} from '../lib/selections';
import {searchKey,publicHref} from '../lib/domain';

const projectStudies:Record<string,{focus:string;observations:string[];questions:string[]}>={
 'sade-kose-mutfak':{focus:'Köşe planında günlük akış.',observations:['L biçimindeki tezgâh, iki duvar boyunca çalışma ve depolama alanını birleştiriyor.','Açık renkli kapaklar ile koyu cihaz yüzeyleri aynı yerleşimde görülüyor.','Alt dolaplar, üst depolama ve cihaz boşlukları birlikte düşünülmüş bir düzen oluşturuyor.'],questions:['Mevcut tesisat ve cihaz yerleri korunacak mı?','Tezgâhta hangi işleri daha sık yapıyorsunuz?','Kapak, çekmece ve erişim öncelikleriniz neler?']},
 'kemerli-kahve-kosesi':{focus:'Servis, sergileme ve saklama bir arada.',observations:['Kemerli orta bölüm, açık rafları ve servis yüzeyini bir odak noktasında topluyor.','İki yandaki cam kapaklı bölümler, sergileme ile kapalı saklamayı aynı kompozisyonda birleştiriyor.','Raf aydınlatması ve alt depolama, fotoğraftaki kahve köşesinin belirgin ayrıntıları.'],questions:['Makinenizin en, derinlik ve kapağı açıldığındaki yüksekliği nedir?','Fincanlar, kahve malzemeleri ve küçük cihazlar için ne kadar yer gerekiyor?','Priz, havalandırma veya su bağlantısı için özel ihtiyaç var mı?']},
 'isikli-tv-unitesi':{focus:'Ekran duvarını bir bütüne dönüştürmek.',observations:['TV paneli, yan raflar ve alttaki depolama tek bir duvar düzeninde bir araya geliyor.','Açık raf ile kapalı hacimlerin birlikte kullanımı, görünen ve saklanan eşyalar arasında ayrım sağlıyor.','Dolaylı aydınlatma, panel ve rafların çevresinde ayrı bir ışık katmanı oluşturuyor.'],questions:['Ekranın boyutu, ağırlığı ve duvarın yapısı nedir?','Prizler, kablolar ve kullanılacak cihazlar nerede duracak?','Kitap, oyun konsolu ve diğer eşyalar için açık veya kapalı alan mı gerekiyor?']}
};
function ProjectStudy({work:w,navigate}:{work:Work;navigate:(p:string)=>void}){const c=projectStudies[w.id]||{focus:w.subtitle,observations:w.features,questions:['Bu mobilya hangi alanda ve nasıl kullanılacak?','Mevcut alanın yaklaşık ölçüsü ve engelleri neler?','Açık raf, kapalı depolama ve yüzey seçimi için öncelikleriniz neler?']};return <section className="wrap v11-case-study"><div><Eyebrow>FOTOĞRAFTAN KARARINIZA</Eyebrow><h2>{c.focus}</h2><p>{w.description}</p><p className="field-hint">Fotoğrafta görülen düzen üzerinden düşünelim. Müşteri röportajı veya teknik şartname değildir.</p></div><div className="v11-case-columns"><article><span className="eyebrow">BU UYGULAMADA GÖRÜNENLER</span><h3>Nasıl bir çözüm?</h3>{c.observations.map(t=><p key={t}>{t}</p>)}</article><article><span className="eyebrow">SİZİN ALANINIZ İÇİN</span><h3>İlk görüşmede konuşalım.</h3><ol>{c.questions.map(t=><li key={t}>{t}</li>)}</ol><p>Yaklaşık ölçü veya mekân fotoğrafıyla başlanabilir. Üretim ölçüsü ayrıca teyit edilir.</p></article></div><details className="v11-case-verification"><summary>Malzeme, kapsam ve fotoğraf bilgisi</summary><p>Görsel atölyenin paylaşılan arşivinden gelir. Bu çalışmanın özgün ölçüsü, malzeme markası, donanım kodu, teslim tarihi ve müşteri adresi doğrulanmış kayıt olarak elimizde bulunmuyor. Fotoğraftan türetilerek yazılmaz. Yeni iş için mobilya, cihaz, tezgâh, aydınlatma, nakliye ve montaj kapsamları teklifte ayrı görüşülür.</p></details><nav className="case-next-links" aria-label="Projeden sonraki adım"><TextLink to={'/kategoriler/'+w.category} navigate={navigate}>Bu alanı keşfedin</TextLink><TextLink to="/malzemeler" navigate={navigate}>Malzeme kararları</TextLink><TextLink to={modelHref('',w.category,w.subtitle+' benzeri bir çalışma istiyorum.')} navigate={navigate}>Kendi alanım için konuşalım</TextLink></nav></section>}
export class Projects extends Component<PageProps&{query?:string},{category:string;search:string;stage:string}>{
 constructor(p:any){super(p);const q=new URLSearchParams(p.query||'');this.state={category:workCategories.some(c=>c.id===q.get('alan'))?q.get('alan')!:'all',search:q.get('ara')||'',stage:q.get('durum')==='process'?'process':'work'}}
 update=(key:string,value:string)=>this.setState({[key]:value} as any,()=>{const s=this.state,q=new URLSearchParams();if(s.category!=='all')q.set('alan',s.category);if(s.search)q.set('ara',s.search);if(s.stage!=='work')q.set('durum',s.stage);history.replaceState({...history.state},'',publicHref('/projeler'+(q.size?'?'+q:'')))});
 render(){const a=this.props,s=this.state,list=works.filter(w=>(s.category==='all'||w.category===s.category)&&w.status===s.stage&&searchKey(w.title+' '+w.subtitle+' '+categoryName(w.category)).includes(searchKey(s.search)));return <>
 <header className="v6-page-head wrap"><Eyebrow>ELİF / UYGULAMA ARŞİVİ</Eyebrow><div><h1>Söz değil.<br/><em>İşin kendisi.</em></h1><p>Atölyeden çıkıp yaşam alanlarına yerleşen çalışmalar. Fotoğrafların arkasında, ölçüsünden son ayrıntısına kadar düşünülmüş bir emek var.</p></div></header>
 <section className="wrap portfolio-section"><div className="portfolio-toolbar"><div className="view-segments" role="group" aria-label="Proje durumu"><button onClick={()=>this.update('stage','work')} aria-pressed={s.stage==='work'}>Bitirdiğimiz İşler</button><button onClick={()=>this.update('stage','process')} aria-pressed={s.stage==='process'}>Uygulama Aşamaları</button></div><label className="portfolio-search"><Icon name="search"/><input type="search" value={s.search} maxLength={100} onInput={e=>this.update('search',e.currentTarget.value)} placeholder="Bir çalışma arayın" aria-label="Projelerde ara"/></label></div>
 <div className="filter-chips" role="group" aria-label="Proje kategorisi">{[{id:'all',name:'Tüm alanlar'},...workCategories].map(c=><button key={c.id} onClick={()=>this.update('category',c.id)} aria-pressed={s.category===c.id}>{c.name}</button>)}</div>
 <div className="result-line" aria-live="polite"><span>{list.length} çalışma</span><span>Gerçek fotoğraflar, atölyenin paylaştığı arşivden.</span></div>
 {list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="v6-empty"><Icon name="search" size={34}/><h2>Bu seçimde henüz bir çalışma yok.</h2><p>Kategorinin ilham fikirlerini inceleyebilir veya kendi modelinizle başlayabilirsiniz.</p><button className="button button-outline" onClick={()=>this.setState({category:'all',search:'',stage:'work'},()=>history.replaceState({...history.state},'',publicHref('/projeler')))}>Filtreleri temizle <Icon/></button>{s.category!=='all'&&<TextLink to={'/kategoriler/'+s.category} navigate={a.navigate}>Bu alanın ilham modellerini inceleyin</TextLink>}<TextLink to={modelHref('',s.category==='all'?'ozel-tasarim':s.category)} navigate={a.navigate}>Kendi modelimle başlayayım</TextLink></div>}
 </section><ModelCallout navigate={a.navigate} compact/></>}
}
export class WorkDetail extends Component<PageProps&{work:Work},{photo:number;zoom:boolean}>{
 state={photo:0,zoom:false};move=(delta:number)=>this.setState(s=>({photo:(s.photo+delta+this.props.work.images.length)%this.props.work.images.length}));
 render(){const a=this.props,w=a.work,photo=workPhotoEvidence(w,this.state.photo),others=works.filter(p=>p.category===w.category&&p.id!==w.id&&p.status==='work').slice(0,3);return <>
 <div className="wrap v6-crumb"><Link to={w.status==='process'?'/projeler?durum=process':'/projeler'} navigate={a.navigate}>{w.status==='process'?'Uygulama Aşamaları':'Çalışma arşivi'}</Link><span>/</span><Link to={'/kategoriler/'+w.category} navigate={a.navigate}>{categoryName(w.category)}</Link></div>
 <section className="wrap work-detail"><div className="work-detail-media"><button className="work-main-photo" onClick={()=>this.setState({zoom:true})} aria-label="Proje fotoğrafını büyüt"><VImage asset={w.images[this.state.photo]} alt={w.subtitle+'. '+photo.caption} eager full/><span><Icon name="plus"/>Fotoğrafı incele</span></button>{w.images.length>1&&<div className="work-thumbnails">{w.images.map((im,i)=><button key={im} onClick={()=>this.setState({photo:i})} aria-label={'Fotoğraf '+(i+1)} aria-pressed={i===this.state.photo}><VImage asset={im} alt="" sizes="100px"/></button>)}</div>}<p className="photo-credit" aria-live="polite">{this.state.photo+1} / {w.images.length}. {photo.caption}</p></div>
 <div className="work-detail-copy"><SourceTag kind={photo.kind}/><Eyebrow>{categoryName(w.category)}</Eyebrow><h1>{w.title}</h1><p className="work-lead">{w.description}</p><dl className="work-facts"><div><dt>Çalışma</dt><dd>{w.subtitle}</dd></div><div><dt>Yaklaşım</dt><dd>Ölçü ve ihtiyaca göre değerlendirme</dd></div><div><dt>Malzeme & ölçü</dt><dd>Yeni teklifinizde birlikte netleştirilir</dd></div></dl><div className="work-features">{w.features.map(f=><span key={f}><Icon name="check" size={16}/>{f}</span>)}</div><ButtonLink to={modelHref('',w.category,w.subtitle+' benzeri bir çalışma istiyorum.')} navigate={a.navigate}>Benzerini birlikte düşünelim</ButtonLink><p className="fineprint">Her mekân farklıdır. Fotoğraf, yeni projeniz için kesin ölçü, malzeme, fiyat veya aynı sonucu elde etme taahhüdü değildir.</p></div>
 </section><ProjectStudy work={w} navigate={a.navigate}/><div className="wrap"><ScopeNotes category={w.category}/></div>{others.length>0&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>AYNI ALANDAN</Eyebrow><h2>Biraz daha <em>keşfedin.</em></h2></div><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div><div className="work-grid">{others.map((p,i)=><WorkCard key={p.id} work={p} actions={a} index={i}/>)}</div></section>}
 <ModelCallout navigate={a.navigate} compact/>
 {this.state.zoom&&<Dialog title={w.subtitle} onClose={()=>this.setState({zoom:false})}><div className="v6-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')this.move(1);if(e.key==='ArrowLeft')this.move(-1)}}><VImage asset={w.images[this.state.photo]} alt={w.subtitle+' büyük görünüm'} eager full sizes="95vw"/>{w.images.length>1&&<div><button className="icon-button" aria-label="Önceki fotoğraf" onClick={()=>this.move(-1)}><span className="reverse-arrow"><Icon/></span></button><span>{this.state.photo+1} / {w.images.length}</span><button className="icon-button" aria-label="Sonraki fotoğraf" onClick={()=>this.move(1)}><Icon/></button></div>}<p>{photo.caption} {this.state.photo+1} / {w.images.length}</p></div></Dialog>}
 </>}
}
const conceptQuestions:Record<string,string[]>={
 'sehpa':['Koltuk ile sehpa arasında nasıl bir geçiş alanı gerekiyor?','Tek parça mı, gerektiğinde ayrılan yüzeyler mi?'],
 'kahve-kosesi':['Makineniz ve kapağı açıldığında gereken boşluk ne kadar?','Neleri sergilemek, neleri kapalı saklamak istersiniz?'],
 'vestiyer':['Oturmak, ayakkabı koymak ve asmak için ne kadar yer gerekiyor?','Giriş kapısı ile dolap kapakları rahat açılabiliyor mu?'],
 'tv-unitesi':['Ekran, priz ve kablolar nerede duracak?','Açık raf ile kapalı depolama arasında nasıl bir denge istersiniz?'],
 'mutfak':['Cihaz ve tesisat yerleri korunacak mı?','Hazırlık yüzeyi ile depolamada önceliğiniz ne?'],
 'gardrop':['Askı, raf ve çekmece ihtiyacınız nasıl dağılıyor?','Kapak açılımı ve geçiş için ne kadar alan var?'],
 'pergola':['Alanın yaklaşık açıklığı ve zemini nasıl?','Gölge, oturma düzeni ve hava koşulları için beklentiniz ne?'],
 'ozel-tasarim':['Günlük kullanımda kaç kişilik bir alan gerekiyor?','Beğendiğiniz biçimde neyi korumak istersiniz?']
};
export class ConceptCard extends Component<{c:typeof concepts[number];navigate:(p:string)=>void;actions?:PageProps},{preview:boolean}>{
 state={preview:false};
 render(){const {c,navigate,actions}=this.props,bed=c.category==='baza-yatak',id='concept:'+c.id,inquiry=modelHref('',c.category,c.subtitle+' üzerine konuşmak istiyorum.',id),saved=!!actions?.favorites.includes(id);
 const destination=bed?'/kategoriler/baza-yatak?model='+encodeURIComponent(c.id):inquiry;
 const save=()=>actions&&<button type="button" className="v7-save-text" aria-label={(saved?'İlham dosyasından çıkar. ':'İlham dosyama ekle. ')+c.subtitle} aria-pressed={saved} onClick={()=>actions.favorite(id)}><Icon name="heart" size={18}/>{saved?'İlham dosyanızda':'İlham dosyama ekle'}</button>;
 return <><article className={'concept-card'+(bed?' concept-card-bed':'')} id={targetElementId(id)} tabIndex={-1} data-concept={c.id} data-category={c.category}>
 <Link to={destination} navigate={bed?navigate:()=>this.setState({preview:true})} className="concept-image" aria-label={bed?c.title+' açık ve kapalı görünümlerini incele':c.subtitle+' ayrıntılarını incele'} aria-haspopup={bed?undefined:'dialog'}><VImage asset={c.image} alt={c.subtitle+', konsept model'} sizes="(max-width: 680px) 90vw, (max-width: 1100px) 45vw, 30vw"/><SourceTag kind="concept"/><span className="concept-open"><Icon name="diagonal"/></span></Link>
 <div className="concept-caption"><span>{categoryName(c.category)}</span><h3>{c.title}</h3><TextLink to={inquiry} navigate={navigate}>Bu fikirle başlayalım</TextLink>{save()}</div></article>
 {this.state.preview&&<Dialog title={c.subtitle} onClose={()=>this.setState({preview:false})}><div className="concept-preview"><div className="concept-preview-media"><VImage asset={c.image} alt={c.subtitle+', büyük konsept görünümü'} full eager sizes="(max-width: 800px) 90vw, 55vw"/></div><div className="concept-preview-copy"><SourceTag kind="concept"/><h3>{c.title}</h3><p>Bu fikri kendi alanınıza göre düşünürken:</p><ul>{(conceptQuestions[c.category]||[]).map(q=><li key={q}>{q}</li>)}</ul><ButtonLink to={inquiry} navigate={p=>{this.setState({preview:false});navigate(p)}}>Bu fikirle başlayalım</ButtonLink>{save()}<p className="concept-preview-note">Temsili tasarım görselidir. Tamamlanmış atölye işi değildir. Ölçü, malzeme ve uygulanabilirlik birlikte değerlendirilir.</p><TextLink to={'/kategoriler/'+c.category} navigate={p=>{this.setState({preview:false});navigate(p)}}>Bu alanı keşfedin</TextLink></div></div></Dialog>}
 </>}
}
export function Categories(a:PageProps&{slug?:string;query?:string}){
 if(a.slug==='baza-yatak')return <BedCollection {...a}/>;
 const cat=workCategories.find(c=>c.id===a.slug);
 if(cat){const list=works.filter(w=>w.category===cat.id&&w.status==='work'),ideas=concepts.filter(c=>c.category===cat.id);return <>
 <section className="category-hero"><VImage asset={categorySupport[cat.id]?.asset||cat.image} alt={cat.name+(categorySupport[cat.id]?' atölye fotoğrafı':' için temsili tasarım sahnesi')} eager sizes="100vw"/><div className="category-shade"/><div className="wrap"><Link className="v6-backlink" to="/kategoriler" navigate={a.navigate}>Kategoriler <Icon size={16}/></Link><Eyebrow>ÖLÇÜNÜZE, ALANINIZA, SİZE</Eyebrow><h1>{cat.name}</h1><p>{cat.line}</p></div><SourceTag kind={categorySupport[cat.id]?'work':'concept'}/></section>
 <nav className="wrap category-browse-nav" aria-label="Kategori içeriği"><a href="#category-works">Atölye işleri</a>{ideas.length>0&&<a href="#category-ideas">Konsept fikirler</a>}<a href="#category-guide">Ölçü ve kullanım rehberi</a></nav><section className="wrap v6-section" id="category-works"><div className="v6-heading"><div><Eyebrow>ATÖLYEDEN</Eyebrow><h2>{cat.short} için<br/><em>düşündüklerimiz.</em></h2></div><p>{cat.detail}</p></div>{list.length?<div className="work-grid">{list.map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div>:<div className="category-no-work"><p>Bu kategoride paylaşılmış bir bitmiş iş fotoğrafı henüz yok. Aşağıdaki konseptleri başlangıç noktası olarak inceleyebilirsiniz.</p><TextLink to={modelHref('',cat.id)} navigate={a.navigate}>Kendi fikrimle başlayayım</TextLink></div>}</section>
 {ideas.length>0&&<section className="concept-band" id="category-ideas"><div className="wrap"><div className="v6-heading"><div><Eyebrow>TEMSİLİ TASARIM SEÇKİSİ</Eyebrow><h2>Bir başlangıç <em>fikri.</em></h2></div><p>Bu görseller konsept modeldir. Atölyenin tamamladığı işler değildir. Üretilebilirlik ve ayrıntılar birlikte değerlendirilir.</p></div><div className="concept-grid">{ideas.map(c=><ConceptCard key={c.id} c={c} navigate={a.navigate} actions={a}/>)}</div></div></section>}<div id="category-guide"><CategoryDecision category={cat.id} navigate={a.navigate}/><ServiceGuide category={cat.id} navigate={a.navigate}/></div><ModelCallout navigate={a.navigate}/></>}
 return <><header className="v6-page-head wrap"><Eyebrow>ELİF / YAŞAM ALANLARI</Eyebrow><div><h1>Evin her köşesine.<br/><em>Size göre.</em></h1><p>Mutfaktan bir fincan kahveye ayrılan köşeye. Hazır bir ölçüye sığmak yerine, alanınızdan ve ihtiyacınızdan başlayalım.</p></div></header><section className="wrap v6-section categories-index"><div className="category-grid">{workCategories.map((c,i)=><Link key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate} className="category-tile"><div><VImage asset={categorySupport[c.id]?.asset||c.image} alt={c.name+(categorySupport[c.id]?' atölye arşivi':' konsepti')} sizes="(max-width: 680px) 90vw, 30vw"/><SourceTag kind={categorySupport[c.id]?'work':'concept'}/></div><span className="category-number">{String(i+1).padStart(2,'0')}</span><h2>{c.name}</h2><p>{c.line}</p><Icon name="diagonal"/></Link>)}</div><div className="category-index-more"><TextLink to="/ilham-modelleri" navigate={a.navigate}>Tüm ilham modellerini keşfedin</TextLink><p>Farklı alanlar için konseptler ve kaynağı korunan Pinterest seçkileri.</p></div></section><ModelCallout navigate={a.navigate}/></>
}
export class Inspiration extends Component<PageProps&{query?:string},{category:string;group:string;expanded:boolean}>{
 state={category:'all',group:'atelier',expanded:false};
 componentDidMount(){this.focusTarget()}
 componentDidUpdate(previous:PageProps&{query?:string}){if(previous.query!==this.props.query)this.focusTarget()}
 focusTarget=()=>{
  const target=inspirationTarget(new URLSearchParams(this.props.query||'').get('hedef'));if(!target)return;
  const pin=target.kind==='reference'?pinterestReferences.find(p=>'pin:'+p.id===target.id):null;
  this.setState({category:target.kind==='concept'?target.category:'all',group:pin?.group||'atelier',expanded:!!pin},()=>{
   requestAnimationFrame(()=>requestAnimationFrame(()=>{const el=document.getElementById(targetElementId(target.id));if(el){el.classList.add('v11-target');el.focus({preventScroll:true});el.scrollIntoView({block:'center',behavior:'instant' as ScrollBehavior});}}));
  });
 };
 pinCard=(p:typeof pinterestReferences[number])=>{
  const a=this.props,title=pinLookup[p.id]?.label||p.title;
  return <article className="pin-card" key={p.id} id={targetElementId('pin:'+p.id)} tabIndex={-1} data-pin={p.id}>
   <span className="eyebrow pin-source-label">PINTEREST / DIŞ REFERANS</span><h3>{title}</h3>
   <PinterestPreview pin={p.id} disclosureId="pinterest-disclosure"/>
   <button className="v7-save-text" aria-label={(a.favorites.includes('pin:'+p.id)?'İlham dosyanızda. Kaydı kaldır. ':'İlham dosyama ekle. ')+title} aria-pressed={a.favorites.includes('pin:'+p.id)} onClick={()=>a.favorite('pin:'+p.id)}><Icon name="heart" size={18}/>{a.favorites.includes('pin:'+p.id)?'İlham dosyanızda':'İlham dosyama ekle'}</button>
   <div className="pin-card-actions"><a href={'https://pin.it/'+p.id} target="_blank" rel="noopener noreferrer" className="text-link">Pinterest'te incele <Icon name="diagonal" size={17}/></a><TextLink to={modelHref('https://pin.it/'+p.id,p.category)} navigate={a.navigate}>Bu modelle başlayalım</TextLink></div>
  </article>;
 };
 render(){const a=this.props,s=this.state,items=inspirationConcepts(s.category),first=visiblePinterestReferences(s.group),rest=visiblePinterestReferences(s.group,true).slice(4),total=first.length+rest.length;return <>
 <header className="v6-page-head wrap discovery-head inspiration-heading"><Eyebrow>ELİF / İLHAM DEFTERİ</Eyebrow><div><h1>Bir yerde gördünüz.<br/><em>Aklınızda kaldı.</em></h1><p>Beğendiğiniz ayrıntıyı seçin. Kendi alanınıza göre birlikte düşünelim.</p></div><div className="inspiration-entry-actions"><ButtonLink to="/modelini-getir" navigate={a.navigate}>Kendi modelimi getireyim</ButtonLink><nav className="inspiration-jump-links" aria-label="İlham seçkileri"><a href="#pinterest-seckileri">Pinterest seçkileri</a></nav></div></header>
 <section className="wrap v6-section inspiration-concepts" id="konsept-seckisi"><div className="v6-heading"><div><h2>Alanınıza göre <em>bir fikir.</em></h2></div><p>Görsele dokunup ayrıntıları inceleyin. Konseptler tamamlanmış atölye işi değildir.</p></div><div className="filter-chips" role="group" aria-label="İlham kategorisi">{[{id:'all',name:'Tüm alanlar'},...workCategories].map(c=><button key={c.id} aria-pressed={c.id===s.category} onClick={()=>this.setState({category:c.id})}>{c.name}</button>)}</div><p className="inspiration-result" role="status" aria-live="polite">{s.category==='all'?items.length+' alan, '+items.length+' başlangıç fikri. Diğer modeller kategori içinde.':categoryName(s.category)+' için '+items.length+' konsept model.'}</p><div className="concept-grid">{items.map(c=><ConceptCard c={c} key={c.id} navigate={a.navigate} actions={a}/>)}</div>{s.category==='baza-yatak'&&<div className="inspiration-category-link"><TextLink to="/kategoriler/baza-yatak" navigate={a.navigate}>Baza koleksiyonunun açık ve kapalı görünümlerini inceleyin</TextLink></div>}</section>
 <section className="pinterest-section" id="pinterest-seckileri"><div className="wrap"><div className="v6-heading"><div><Eyebrow>KAYNAĞINDAN KEŞFEDİN</Eyebrow><h2>Pinterest'ten<br/><em>kaydettiğimiz fikirler.</em></h2></div><p>Kaynağını inceleyin, ilham dosyanıza ekleyin veya beğendiğiniz bağlantıyla görüşmeye başlayın.</p></div>
 <p className="pin-consent-note" id="pinterest-disclosure"><strong>Görseller yalnız siz yüklemeyi seçtiğinizde açılır.</strong> Pinterest'e bağlanıldığında IP ve tarayıcı bilgileri aktarılabilir, dış servis çerez kullanabilir. Bunlar tamamlanmış Elif projeleri değildir.</p>
 <div className="pin-toolbar"><div className="view-segments pin-segments" role="group" aria-label="Pinterest seçkisi"><button aria-pressed={s.group==='atelier'} onClick={()=>this.setState({group:'atelier',expanded:false})}>Ustanın seçtikleri</button><button aria-pressed={s.group==='shared'} onClick={()=>this.setState({group:'shared',expanded:false})}>Birlikte önerilenler</button></div><span className="pin-count" aria-live="polite">{s.expanded?total:first.length} / {total} referans</span></div>
 <div className="pin-grid">{first.map(this.pinCard)}</div>
 {rest.length>0&&<details className="pin-more" key={s.group} open={s.expanded} onToggle={e=>{if(e.currentTarget.open!==this.state.expanded)this.setState({expanded:e.currentTarget.open})}}><summary aria-controls="pin-expanded-list">{s.expanded?'Ek referansları daralt':'Diğer '+rest.length+' referansı göster'} <Icon name="plus" size={18}/></summary><div className="pin-grid" id="pin-expanded-list">{rest.map(this.pinCard)}</div></details>}
 <noscript><div className="pin-noscript"><h3>Birlikte önerilenlerin kaynakları</h3>{pinterestReferences.filter(p=>p.group==='shared').map(p=><p key={p.id}><a href={pinLookup[p.id]?.canonical||'https://pin.it/'+p.id} target="_blank" rel="noopener noreferrer">{pinLookup[p.id]?.label||p.title}</a></p>)}</div></noscript>
 <p className="pin-note">Kaynaklar ilgili üreticilerine aittir. Bağlantılar değişebilir veya giriş gerektirebilir. Önizleme formunuza bilgi aktarmaz. Görsel açılmazsa Pinterest bağlantısını kullanabilirsiniz.</p>
 </div></section><ModelCallout navigate={a.navigate}/></>}
}
export function AboutAtelier(a:PageProps&{atelier?:boolean}){return <>
 <header className="v6-page-head wrap" data-atelier-view={a.atelier?'process':'story'}><Eyebrow>{a.atelier?'ELİF / TEZGÂHTAN MEKÂNA':'ELİF / AİLEDEN GELEN USTALIK'}</Eyebrow><div><h1>{a.atelier?<>Bir fikrin<br/><em>şekil aldığı yer.</em></>:<>Bir meslekten fazlası.<br/><em>Bir aile mirası.</em></>}</h1><p>{a.atelier?'Paylaşılan uygulama kareleri üzerinden, yerleşimden montaj ayrıntısına. İşin yalnız son görünümüne değil, oluşma aşamalarına da bakalım.':"Yunus Usta'nın babasından öğrendiği marangozluk, bugün farklı yaşam alanlarında devam ediyor. Hazır bir kalıp değil, ihtiyaca göre düşünülmüş bir çalışma."}</p></div></header>
 <section className="atelier-documentary"><div className="atelier-documentary-image"><VImage asset="work-joinery" alt="Atölyenin ahşap kamelya uygulamasındaki çatı birleşimi ayrıntısı" eager sizes="70vw"/><SourceTag kind="process"/></div><div><Eyebrow>{a.atelier?'ARŞİVDEN BİR UYGULAMA AYRINTISI':"YUNUS USTA'NIN ELİNDEN ÇIKANLAR"}</Eyebrow><h2>{a.atelier?<>Görünen yüzeyin<br/><em>arkasındaki düzen.</em></>:<>Ölçüsünde dikkat.<br/><em>Ayrıntısında emek.</em></>}</h2>
 {a.atelier?<><p>Bu kare, ahşap kamelyanın çatı altı birleşimlerini gösteriyor. Diğer uygulama fotoğraflarında dolap yerleşimi, koruyucu filmler ve kurulum ayrıntıları görülebilir.</p><p>Fotoğraflar sürecin belirli anlarıdır. Tamamlanma tarihi, teknik uygunluk veya teslim onayı yerine geçmez. Kendi projenizde ölçü, malzeme, bağlantı ve montaj kapsamını ayrı ayrı konuşabiliriz.</p><TextLink to="/hakkimizda" navigate={a.navigate}>Aile hikâyemizi keşfedin</TextLink></>:<><p>Bir dolabın nasıl açıldığını, bir rafın ne taşıyacağını, bir köşenin günlük yaşamda nasıl kullanılacağını birlikte konuşarak başlarız.</p><p>Mesleğin aileden gelen bilgisini, sizin alanınızın ihtiyacıyla buluştururuz. Bir çizim hazırlamanız şart değil. Beğendiğiniz ayrıntıyı ve neyi değiştirmek istediğinizi doğrudan Yunus Usta ile konuşabilirsiniz.</p><TextLink to="/atolye" navigate={a.navigate}>Atölye sürecini inceleyin</TextLink></>}
 </div></section>
 <section className="wrap atelier-values">{(a.atelier?[
 ['Ölçüyü konuşmak.','Yaklaşık ölçü ve mekân fotoğrafı başlangıçtır. İmalata esas ölçüler, uygulama öncesinde ayrıca netleştirilir.'],
 ['Ayrıntıyı ayırmak.','Gövde, yüzey, kapak ve donanım farklı kararlardır. Görselde beğendiğiniz ayrıntının nasıl uygulanacağını görüşmede sorun.'],
 ['Kapsamı netleştirmek.','Nakliye, yerinde montaj ve varsa diğer işler aynı şey değildir. Hangi işin kimin sorumluluğunda olduğu teklifte belirlenir.']
 ]:[
 ['Aile atölyesi.','Nesilden nesile aktarılan meslek bilgisi. Doğrudan ustayla konuşarak ilerleyen bir süreç.'],
 ['Ölçüye özel.','Alanınızın ihtiyacından başlar, kullanım biçiminize göre şekillendiririz.'],
 ['Birlikte karar.','Hazır bir modele bağlı kalmak yerine, neyi korumak ve neyi değiştirmek istediğinizi konuşuruz.']
 ]).map(([title,text],i)=><div key={title}><span>0{i+1}</span><h2>{title}</h2><p>{text}</p></div>)}</section>
 {a.atelier&&<section className="wrap v6-section"><div className="v6-heading"><div><Eyebrow>UYGULAMA ARŞİVİ</Eyebrow><h2>Uygulama fotoğrafları.<br/><em>İşin içinden.</em></h2></div><p>Bu kareler uygulama aşamasını gösterir. Bitmiş projelerin tanıtım çekimleri olarak sunulmaz.</p></div><div className="work-grid">{works.filter(w=>w.status==='process').map((w,i)=><WorkCard key={w.id} work={w} actions={a} index={i}/>)}</div><TextLink to="/projeler?durum=process" navigate={a.navigate}>Uygulama arşivini açın</TextLink></section>}
 <div className="wrap address-note"><Icon name="pin" size={28}/><div><h2>İstanbul'da, yeni atölyemize hazırlanıyoruz.</h2><p>Yeni atölye adresi netleştiğinde burada paylaşılacak. Ziyaret öncesinde Yunus Usta ile görüşerek adresi ve uygunluğu teyit edin. Projenizi bir fikir ve yaklaşık ölçüyle hazırlamaya başlayabilirsiniz.</p></div></div><ModelCallout navigate={a.navigate}/></>}
