import {createElement,Fragment} from 'react';
import {Eyebrow,ButtonLink,TextLink,Icon,type PageProps} from '../components/ui';
import {VImage,SourceTag} from '../components/PortfolioUI';
import {works} from '../lib/portfolio';
export function ServiceGuide(a:PageProps){const completed=works.filter(w=>w.status==='work'),categories=new Set(completed.map(w=>w.category)).size;return <>
 <header className="v6-page-head wrap"><Eyebrow>ELİF / HİZMET VE TEKLİF REHBERİ</Eyebrow><div><h1>Güzel bir iş,<br/><em>açık bir anlaşmayla başlar.</em></h1><p>Bir modelin fotoğrafından, size ait bir mobilyaya. Ölçüyü, malzemeyi ve kapsamı aynı açıklıkla konuşalım.</p></div></header>
 <section className="wrap v21-guide-hero"><div><VImage asset="r13" alt="Elif Tasarım atölye arşivindeki mutfak uygulaması" eager sizes="(max-width: 800px) 92vw, 52vw"/><SourceTag kind="work"/></div><div><Eyebrow>ÖNCE NEYE İHTİYACINIZ VAR?</Eyebrow><h2>Bir bütçeden önce,<br/><em>bir öncelik.</em></h2><p>Daha fazla depolama, rahat bir çalışma alanı veya evinize uyan bir ölçü. Önceliğinizi ve varsa bütçe beklentinizi ilk görüşmede paylaşın.</p><p>Burada doğrulanmış fiyat listesi bulunmuyor. Aynı görünüm, farklı gövde, kapak, donanım ve uygulama kararlarıyla farklı bir kapsama dönüşebilir.</p><ButtonLink to="/modelini-getir" navigate={a.navigate}>Fikrimi ve önceliklerimi hazırlayayım</ButtonLink></div></section>
 <section className="wrap v21-guide-section"><Eyebrow>TEKLİFLERİ AYNI KAPSAMDA KARŞILAŞTIRIN</Eyebrow><h2>Fiyatın arkasındaki<br/><em>altı karar.</em></h2><div className="v21-scope-grid">{[
 ['Ölçü ve yerleşim','En, derinlik ve yükseklik yanında kapak, çekmece ve geçiş alanını da konuşun. İlk ölçü, üretim için onaylanmış son ölçü değildir.'],
 ['Gövde ve kapak','Ahşap türü, masif veya kaplama yaklaşımı, levha ve kapak yapısı ayrı kalemlerdir. Yalnız fotoğrafın rengine bakarak aynı malzemeyi varsaymayın.'],
 ['Yüzey ve numune','Matlık, renk ve doku için gerçek numuneyi isteyin. Ekrandaki tonun üretim onayı olmadığını akılda tutun.'],
 ['Donanım ve ayrıntı','Ray, menteşe, kulp, aydınlatma ve hareketli mekanizmanın kapsamını ayrı sorun. Marka ve model ancak doğrulanınca teklifin parçası olur.'],
 ['Taşıma ve montaj','İlçe, kat, asansör ve erişim durumunu paylaşın. Söküm, nakliye, taşıma, montaj ve elektrik işlerinin dahil olup olmadığını yazılı netleştirin.'],
 ['Takvim ve onay','Çizim, son ölçü, revizyon, ödeme planı ve teslim beklentisi birlikte netleşsin. Taslak görüşme, üretim talimatı veya kesin sipariş değildir.']
 ].map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="wrap v21-guide-terms"><div><Eyebrow>İSTANBUL / PROJENİZE GÖRE</Eyebrow><h2>Gelmeden önce,<br/><em>konuşalım.</em></h2><p>Yeni atölye adresi ve ziyaret saatleri kesinleşmedi. Yunus Usta ile görüşmeden yola çıkmayın. İlçenizi belirterek keşif, nakliye ve montaj uygunluğunu sorun.</p><TextLink to="/iletisim" navigate={a.navigate}>Doğrudan iletişim</TextLink></div><div><h3>Yazılı olarak netleştirilecekler</h3><ul><li>Üretilecek parçalar, malzeme ve donanım kapsamı.</li><li>Keşif gerekliliği ve varsa ücreti.</li><li>Fiyat, kapora ve ödeme aşamaları.</li><li>Değişiklik, iptal ve teslim koşulları.</li><li>Bakım talimatı, garanti ve teslim sonrası destek kapsamı.</li></ul><p className="field-hint">Bu sayfa genel görüşme hazırlığıdır. İşletmenin onaylı sözleşmesinin veya yasal haklarınızın yerine geçmez. Ücretsiz keşif, kesin fiyat veya garanti süresi vaat edilmez.</p></div></section>
 <section className="wrap v21-proof"><Icon name="hand" size={28}/><div><h2>İşi, fotoğrafından ve ayrıntısından tanıyın.</h2><p>Paylaşılan arşivde {completed.length} tamamlanmış çalışma kaydı, {categories} kullanım kategorisinde incelenebilir. Bu sayı işletmenin toplam iş adedi değil, yalnız sitedeki seçkidir. Uygulama fotoğrafları ve konsept modeller ayrı etiketlidir.</p></div><ButtonLink to="/projeler" navigate={a.navigate} secondary>Gerçek işleri incele</ButtonLink></section>
 <section className="wrap v21-help-links"><TextLink to="/sikca-sorulan-sorular" navigate={a.navigate}>Sıkça sorulan sorular</TextLink><TextLink to="/rehber/olcu-alma" navigate={a.navigate}>Ölçü hazırlığı</TextLink><TextLink to="/rehber/malzeme-secimi" navigate={a.navigate}>Malzeme seçimi</TextLink><TextLink to="/rehber/bakim" navigate={a.navigate}>Bakım notları</TextLink></section>
 </>}
