const {test}=require('node:test');const assert=require('node:assert/strict');
const d=require('../preview/domain.cjs');
test('Türkçe ölçü 120,5 cm',()=>assert.deepEqual(d.parseDimension('120,5','cm'),{ok:true,mm:1205}));
test('İngilizce ondalık ölçü',()=>assert.deepEqual(d.parseDimension('120.5','cm'),{ok:true,mm:1205}));
test('mm ölçeği',()=>assert.deepEqual(d.parseDimension('1205','mm'),{ok:true,mm:1205}));
test('Belirsiz ayraç reddedilir',()=>assert.equal(d.parseDimension('1.200,5','cm').ok,false));
test('Sıfır ölçü reddedilir',()=>assert.equal(d.parseDimension('0','cm').ok,false));
test('Negatif ölçü reddedilir',()=>assert.equal(d.parseDimension('-3','cm').ok,false));
test('Kesirli milimetre yuvarlanmaz',()=>assert.equal(d.parseDimension('1.25','mm').ok,false));
test('Sınır aşımı',()=>assert.equal(d.parseDimension('99999','cm').ok,false));
test('Ondalık para dönüşümü',()=>assert.equal(d.majorToMinor('19.99'),1999));
test('Kuruş dönüşümü',()=>assert.equal(d.majorToMinor('0.01'),1));
test('Yanlış fiyat sessiz yuvarlanmaz',()=>assert.throws(()=>d.majorToMinor('19.999')));
test('Negatif fiyat ret',()=>assert.throws(()=>d.majorToMinor('-1')));
test('Türkçe arama',()=>assert.equal(d.searchKey('İSTANBUL CEVİZ'),d.searchKey('istanbul ceviz')));
test('Adet en fazla 100',()=>assert.equal(d.validQuantity(101),false));
test('Kesirli adet ret',()=>assert.equal(d.validQuantity(2.1),false));
test('Doğru adet',()=>assert.equal(d.validQuantity(100),true));
test('Görsel olmayan dosya ret',()=>assert.equal(d.validateFile({type:'image/svg+xml',size:400}).ok,false));
test('Büyük dosya ret',()=>assert.equal(d.validateFile({type:'image/png',size:11*1024*1024}).ok,false));
test('Geçerli dosya kabul',()=>assert.equal(d.validateFile({type:'image/png',size:2000}).ok,true));
test('Sepet anahtarları varyantı ayırır',()=>assert.notEqual(d.cartKey('masa','Ceviz','180 cm'),d.cartKey('masa','Meşe','180 cm')));
test('Toplam yalnız güvenli pozitif adet',()=>assert.throws(()=>d.lineTotal(1000,-1)));
test('Sepet kuruş toplamı',()=>assert.equal(d.lineTotal(1999,3),5997));
test('Özel ölçü boş olabilir',()=>assert.deepEqual(d.validateQuoteStep(1,{unknown:true}),{}));
test('Bilinen ölçü eksik olamaz',()=>assert.ok(Object.keys(d.validateQuoteStep(1,{unknown:false,width:'',depth:'',height:'',unit:'cm'})).length));
test('İletişim demo dahi geçerli olmalı',()=>assert.ok(Object.keys(d.validateQuoteStep(5,{name:'A',email:'yanlis',phone:''})).length));
test('Taslak kişisel veriyi tutmaz',()=>assert.equal(d.safeDraft({kind:'Masa',name:'Örnek',phone:'123',email:'x',note:'kişisel',width:'120'}).name,undefined));
test('Bozulmuş taslak nesnesi DOM verisi olamaz',()=>assert.deepEqual(d.safeDraft({kind:{malicious:true},width:['1'],unit:'meter',unknown:'false'}),{}));
test('Geçerli taslak alanları korunur',()=>assert.deepEqual(d.safeDraft({kind:'Masa',width:'120',unit:'cm',unknown:false,email:'private@example.com'}),{kind:'Masa',width:'120',unit:'cm',unknown:false}));
test('Depolama engelliyse yazma güvenle başarısız',()=>assert.equal(d.writeLocal('blocked',{}),false));
test('Depolama engelliyse yedek değer',()=>assert.deepEqual(d.readLocal('blocked',[]),[]));
test('Süreli yerel kaydın yazma/okuma döngüsü',()=>{const entries=new Map();global.localStorage={setItem:(k,v)=>entries.set(k,v),getItem:k=>entries.get(k),removeItem:k=>entries.delete(k)};assert.equal(d.writeLocal('a',{ok:true},7),true);assert.deepEqual(d.readLocal('a',null),{ok:true});const r=JSON.parse(entries.get('elif-v2:a'));r.expires=0;entries.set('elif-v2:a',JSON.stringify(r));assert.equal(d.readLocal('a',null),null);delete global.localStorage;});
test('Bozuk kayıt JSON arayüzü yıkmaz',()=>{global.localStorage={getItem:()=>'{',removeItem:()=>{}};assert.deepEqual(d.readLocal('bad',[]),[]);delete global.localStorage;});
test('Bilinmeyen ölçü birimi reddedilir',()=>assert.equal(d.parseDimension('12','meter').ok,false));
test('Geçersiz süreli depolama kaydı kullanılmaz',()=>{global.localStorage={getItem:()=>JSON.stringify({expires:'never',value:'bad'}),removeItem:()=>{}};assert.equal(d.readLocal('bad',null),null);delete global.localStorage;});
// V5 regressions written before implementation.
test('V5 price display preserves kuruş',()=>assert.ok(d.money(1999).includes('19,99')));
test('V5 whitespace search normalizes',()=>assert.equal(d.searchKey('  ÇALIŞMA   MASASI '),'calisma masasi'));
test('V5 blank contact is rejected',()=>assert.ok(Object.keys(d.validateQuoteStep(5,{name:'Örnek',email:'',phone:'          '})).length));
test('V5 punctuation is not a telephone',()=>assert.ok(Object.keys(d.validateQuoteStep(5,{name:'Örnek',email:'',phone:'((((()))))'})).length));
test('V5 cm to mm preserves size',()=>assert.deepEqual(d.convertDimensions({width:'180',depth:'80',height:'75',unit:'cm'},'mm'),{ok:true,values:{width:'1800',depth:'800',height:'750',unit:'mm'}}));
test('V5 decimal unit conversion is exact',()=>assert.deepEqual(d.convertDimensions({width:'1205',depth:'800',height:'',unit:'mm'},'cm'),{ok:true,values:{width:'120.5',depth:'80',height:'',unit:'cm'}}));
test('V5 invalid unit conversion fails without reinterpretation',()=>assert.equal(d.convertDimensions({width:'1.200,5',depth:'80',height:'75',unit:'cm'},'mm').ok,false));
test('V5 empty dimensions stay empty when units change',()=>assert.deepEqual(d.convertDimensions({width:'',depth:'',height:'',unit:'cm'},'mm'),{ok:true,values:{width:'',depth:'',height:'',unit:'mm'}}));
