const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
class TestComponent{constructor(props){this.props=props;this.state={}}setState(change){this.state={...this.state,...(typeof change==='function'?change(this.state):change)}}}
function load(file){const cache={};function req(f){f=path.resolve(f);if(cache[f])return cache[f].exports;const m={exports:{}};cache[f]=m;const js=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,jsxFactory:'createElement',jsxFragmentFactory:'Fragment'}}).outputText;new Function('module','exports','require',js)(m,m.exports,id=>{if(id==='react')return {createElement:(type,props,...children)=>({type,props:{...props,children}}),Fragment:({children})=>children,Component:TestComponent};if(id.startsWith('.')){const base=path.resolve(path.dirname(f),id);return req(fs.existsSync(base+'.ts')?base+'.ts':base+'.tsx')}return require(id)});return m.exports}return req(file)}
function walk(node,fn){if(!node)return;if(Array.isArray(node))return node.forEach(x=>walk(x,fn));if(typeof node==='object'){fn(node);walk(node.props?.children,fn)}}

test('navigation has exactly one studio destination, not a separate Devir item',()=>{const p=load('src/lib/portfolio.ts');assert.equal(p.mainNavigation.filter(([url])=>url==='/tasarim-masasi').length,1);assert.equal(p.mainNavigation.some(([url,label])=>url==='/devir-01'||/devir/i.test(label)),false)});
test('old product route is not canonical and search points only to the studio',()=>{const r=load('src/lib/routes.ts'),s=load('src/lib/selections.ts');assert.ok(!r.v7Routes.includes('/devir-01'));assert.equal(r.pageTitle('/tasarim-masasi'),'3D Stüdyo | Elif Tasarım');assert.equal(s.searchEntries('devir').some(x=>x.path==='/devir-01'),false);assert.ok(s.searchEntries('devir').some(x=>x.path==='/tasarim-masasi'))});
test('all 26 unique supplied archive photos are actually reachable through project galleries',()=>{const p=load('src/lib/portfolio.ts'),ids=new Set(p.works.flatMap(w=>w.images));for(let i=1;i<=26;i++)assert.ok(ids.has('r'+String(i).padStart(2,'0')),'missing source photo '+i);assert.equal(ids.size,43)});
test('new views enrich the same real projects, not fictitious extra commissions',()=>{const p=load('src/lib/portfolio.ts');assert.deepEqual(new Set(p.works.find(w=>w.id==='ahsap-bahce-kamelyasi').images),new Set(['r19','r23','r16','r17','r20']));assert.ok(p.works.find(w=>w.id==='mutfak-kurulum-asamasi').images.includes('r11'));assert.equal(p.works.find(w=>w.images.includes('r03')).status,'process')});
test('studio presets preserve view, dimensions and material',()=>{const {studioPresets}=load('src/lib/studio-presets.ts');assert.equal(studioPresets.length,3);assert.deepEqual(studioPresets.map(x=>[x.width,x.depth,x.height,x.material,x.angle]),[[160,75,80,'mese',0],[180,80,80,'ceviz',90],[200,85,110,'koyu',180]])});
test('request readiness never claims optional photographs or measurements exist',()=>{const {projectReadiness}=load('src/lib/project-readiness.ts'),{emptyProject}=load('src/lib/project.ts');const rows=projectReadiness(emptyProject(),0);assert.equal(rows.find(x=>x.id==='photos').ready,false);assert.equal(rows.find(x=>x.id==='measure').ready,false);assert.ok(rows.find(x=>x.id==='summary').ready);assert.doesNotMatch(JSON.stringify(rows),/gönderildi|isteğiniz alındı|Ölçüler kaydedildi/i)});
test('legacy product document is a query-preserving studio redirect, not duplicate product content',()=>{const s=fs.readFileSync('dist/devir-01/index.html','utf8');assert.match(s,/tasarim-masasi/);assert.match(s,/location\.search/);assert.doesNotMatch(s,/v20-product-hero|v20-devir/)});
test('all live internal links avoid the retired product route',()=>{const m=JSON.parse(fs.readFileSync('dist/release-v23.json','utf8'));for(const r of m.routes){const f='dist'+(r==='/'?'':r)+'/index.html';const html=fs.readFileSync(f,'utf8');assert.doesNotMatch(html,/href=["'](?:\/elif-tasarim)?\/devir-01(?:\/|[?#"'])/,r)}});
