const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file){const cache={};function req(f){f=path.resolve(f);if(cache[f])return cache[f].exports;const m={exports:{}};cache[f]=m;const js=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,jsxFactory:'createElement',jsxFragmentFactory:'Fragment'}}).outputText;new Function('module','exports','require',js)(m,m.exports,id=>{if(id==='react')return{createElement:(type,props,...children)=>({type,props:{...props,children}}),Fragment:'fragment',Component:class{constructor(props){this.props=props;}setState(x,cb){this.state={...this.state,...(typeof x==='function'?x(this.state):x)};cb?.()}}};if(id.startsWith('.')){const b=path.resolve(path.dirname(f),id);return req(fs.existsSync(b+'.ts')?b+'.ts':b+'.tsx')}return require(id)});return m.exports;}return req(file);}
function walk(n,fn){if(!n)return;if(Array.isArray(n))return n.forEach(v=>walk(v,fn));if(typeof n==='object'){fn(n);walk(n.props?.children,fn)}}
test('SEO titles describe actual service while the home slogan stays intact',()=>{const r=load('src/lib/routes.ts');assert.equal(r.pageTitle('/'),'İstanbul Özel Ölçü Mobilya Atölyesi | Elif Tasarım');assert.match(r.pageTitle('/kategoriler/kahve-kosesi'),/Kahve Köşesi Dolabı/);assert.match(r.pageTitle('/rehber/bakim'),/Ahşap Mobilya Bakımı/);assert.ok(fs.readFileSync('src/pages/Home.tsx','utf8').includes('Zamana değer'));});
test('only the first hero frame is high priority, all others are subordinate',()=>{const {VImage}=load('src/components/PortfolioUI.tsx');assert.equal(VImage({asset:'concept-hero',alt:'x',eager:true,priority:'low'}).props.fetchPriority,'low');const {Home}=load('src/pages/Home.tsx');const h=new Home({});const frames=[];walk(h.render(),n=>{if(n.props?.['data-slide']!==undefined)frames.push(n)});assert.equal(frames.length,5);let high=0;for(const f of frames)walk(f,n=>{if(n.type===undefined)return;if(n.type.name==='VImage'&&n.props.priority==='high')high++});assert.equal(high,1);assert.ok(frames.some(f=>!f.props.children.some(c=>c&&c.type?.name==='VImage')));});
test('robots policy uses explicit publication approval, never private helper or unknown routes',()=>{const r=load('src/lib/routes.ts');assert.equal(r.pageRobots('/',false),'noindex,nofollow');assert.equal(r.pageRobots('/',true),'index,follow');for(const p of ['/modelini-getir','/arama','/calisma-dosyam','/unknown','/devir-01'])assert.equal(r.pageRobots(p,true),'noindex,nofollow');assert.ok(r.seoApprovedRoutes.every(p=>r.v7Routes.includes(p)));});
test('three service briefs use existing real projects and remain nontechnical preparation',()=>{const d=load('src/lib/service-content.ts').serviceContent,p=load('src/lib/portfolio.ts');assert.deepEqual(Object.keys(d).sort(),['kahve-kosesi','mutfak','tv-unitesi']);for(const [cat,v]of Object.entries(d)){assert.equal(v.sections.length,4);assert.equal(v.preparation.length,4);const w=p.works.find(w=>w.id===v.project);assert.ok(w&&w.category===cat&&w.status==='work');assert.ok(v.note.includes('Üretim'));}});
test('static and client head share metadata policy',()=>{const build=fs.readFileSync('tools/build-v25.cjs','utf8'),app=fs.readFileSync('src/App.tsx','utf8');assert.ok(build.includes('og:site_name'));assert.ok(build.includes('data-indexable'));assert.ok(build.includes('pageRobots(route,indexable&&!offline)'));assert.ok(app.includes("setMeta('robots',pageRobots("));});
test('pausing cancels a pending decoded slide instead of switching after pause',async()=>{const beforeWindow=global.window,beforeDocument=global.document;global.window={clearInterval(){},setInterval(){return 1},clearTimeout(){},setTimeout(){return 1}};global.document={hidden:false};try{const {Home}=load('src/pages/Home.tsx');const h=new Home({});h.alive=true;let resolve;h.hero={querySelector:()=>({complete:true,currentSrc:'mock.webp',naturalWidth:1200,decode:()=>new Promise(r=>resolve=r)})};h.setScene(1,true);h.state.paused=true;h.reschedule();resolve();await Promise.resolve();await Promise.resolve();assert.equal(h.state.scene,0);}finally{global.window=beforeWindow;global.document=beforeDocument;}});
