import {createElement,Fragment,Component} from 'react';
import {Icon,Link,Eyebrow,image,type PageProps} from './ui';
import {defaultStudio,normalizeStudio,studioFromQuery,studioQuery,studioSummary,studioMaterials,type StudioConfig} from '../lib/desk-v8';
import {projectStore} from '../lib/project';
import {downloadText,publicHref} from '../lib/domain';

type Props={query?:string;compact?:boolean;navigate:PageProps['navigate'];notify:PageProps['notify']};
type State={config:StudioConfig;status:'poster'|'loading'|'ready'|'unavailable'|'lost';tab:'motion'|'size';dimensions:boolean;view:string;light:string;share:boolean;rotating:boolean;environment:'atelier'|'product';shelves:boolean;shelfLights:boolean;styling:boolean};
let runtimePromise:Promise<any>|null=null;
function loadRuntime():Promise<any>{const w=window as any;if(w.ElifDesk3D)return Promise.resolve(w.ElifDesk3D);if(runtimePromise)return runtimePromise;runtimePromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.type='module';script.src=(w.__ELIF_BASE__||'/elif-tasarim')+'/three/desk-scene.mjs';script.onload=()=>w.ElifDesk3D?resolve(w.ElifDesk3D):reject(Error('3D initialization failed'));script.onerror=()=>{runtimePromise=null;script.remove();reject(Error('3D runtime unavailable'))};document.head.appendChild(script)});return runtimePromise;}
export class DeskExperience extends Component<Props,State>{
 private host:HTMLDivElement|null=null;private root:HTMLElement|null=null;private engine:any=null;private alive=true;
 constructor(p:Props){super(p);this.state={config:p.query?studioFromQuery(p.query):{...defaultStudio},status:'poster',tab:'motion',dimensions:false,view:'perspective',light:'day',share:false,rotating:false,environment:'atelier',shelves:true,shelfLights:true,styling:true}}
 componentDidMount(){if(!this.props.compact)this.start();}
 componentWillUnmount(){this.alive=false;this.engine?.dispose();this.engine=null;}
 start=async()=>{if(this.state.status==='loading'||this.engine)return;this.setState({status:'loading'});try{const runtime=await loadRuntime();if(!this.alive||!this.host)return;this.engine=runtime.createDeskScene(this.host,this.state.config,{status:(status:any)=>{if(this.alive)this.setState({status})}});this.engine.environment({mode:this.state.environment,shelves:this.state.shelves,lights:this.state.shelfLights,props:this.state.styling});this.engine.light(this.state.light);this.setState({status:'ready'});}catch{if(this.alive)this.setState({status:'unavailable'})}};
 change=(patch:Partial<StudioConfig>)=>{const config=normalizeStudio({...this.state.config,...patch});this.setState({config},()=>this.engine?.update(config));};
 setView=(view:string)=>{this.setState({view});this.engine?.setView(view)};
 handoff=()=>{const s=this.state.config,d=projectStore.get();projectStore.patch({category:'ozel-tasarim',width:String(s.width),depth:String(s.depth),height:String(s.height),unit:'cm',unknown:false,dimensions:`${s.width} × ${s.depth} × ${s.height} cm`,material:studioMaterials[s.material].name,details:studioSummary(s),note:d.note||'Devir 01 çekmeceli, döner yan tablalı çalışma masası konseptini alanıma göre birlikte değerlendirmek istiyorum.'});this.props.navigate('/modelini-getir');};
 atmosphere=(patch:Partial<State>)=>{this.setState(patch as any,()=>this.engine?.environment({mode:this.state.environment,shelves:this.state.shelves,lights:this.state.shelfLights,props:this.state.styling}));};
 fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await this.root?.querySelector('.v8-showroom')?.requestFullscreen();}catch{this.props.notify('Bu cihazda tam ekran açılamadı. Stüdyoyu normal görünümde kullanabilirsiniz.')}};
 snapshot=()=>{if(!this.engine)return;try{const url=this.engine.snapshot(1920,1280),a=document.createElement('a');a.href=url;a.download='Elif-Devir-01-Konsept-Model.png';a.click();this.props.notify('Görüntü hazırlandı. Konsept modeldir, teknik imalat çizimi değildir.')}catch{this.props.notify('Görüntü bu cihazda kaydedilemedi. Ölçü özetinizi indirebilirsiniz.')}};
 shareURL=()=>{const w=typeof window!=='undefined'?window as any:{};return (w.__ELIF_SITE_URL__||'https://onourimpram.github.io/elif-tasarim').replace(/\/$/,'')+'/tasarim-masasi/?'+studioQuery(this.state.config)};
 field=(key:'width'|'depth'|'height'|'angle',label:string,min:number,max:number,unit='cm')=>{const v=this.state.config[key];return <div className="v8-field" key={key}><div><label htmlFor={'v8-'+(this.props.compact?'home-':'full-')+key}>{label}</label><span><input type="number" inputMode="numeric" value={v} min={min} max={max} step="1" aria-label={label+', sayı girişi'} onChange={e=>{const raw=e.currentTarget.value;if(/^\d+$/.test(raw)&&+raw>=min&&+raw<=max)this.change({[key]:+raw});else e.currentTarget.value=String(v)}}/>{unit}</span></div><input id={'v8-'+(this.props.compact?'home-':'full-')+key} type="range" aria-label={label} min={min} max={max} value={v} step="1" onInput={e=>this.change({[key]:+e.currentTarget.value})}/><div className="v8-bounds"><span>{min} {unit}</span><span>{max} {unit}</span></div></div>};
 render(){const {config:c,status,tab,dimensions,view,light}=this.state,p=this.props,ready=status==='ready';return <div ref={e=>this.root=e} className={'v8-experience v9-experience '+(p.compact?'v8-compact':'v8-full')} data-studio={p.compact?'home':'full'} data-three-status={status}>
 <div className="v8-story"><Eyebrow>{p.compact?'05 / YAŞAYAN TASARIM MASASI':'ELİF TASARIM / DEVİR 01'}</Eyebrow>{p.compact?<h2>Çalışma alanınız,<br/><em>sizinle değişsin.</em></h2>:<h1>Kendi çalışma<br/>alanınızı <em>tasarlayın.</em></h1>}<p className="v8-lede">İki yanda raflar, elinizin altında çekmeceler. Işığı, ahşabı ve hareketi birlikte düşünün. Size ait bir çalışma alanı, ölçülerinizle şekillensin.</p>
 <div className="v8-design-note"><span className="v8-series-number">01</span><div><strong>DEVİR</strong><span>YÜKSEKLİK AYARLI ÇALIŞMA MASASI</span></div><span className="v8-concept-label">Konsept model</span></div>
 <div className="v8-control-tabs" role="tablist" aria-label="Tasarım kontrol grubu">{[['motion','Hareketi keşfet'],['size','Ölçünü belirle']].map(([id,name])=><button type="button" role="tab" key={id} aria-selected={tab===id} onClick={()=>this.setState({tab:id as any})}>{name}</button>)}</div>
 <div className="v8-controls" role="tabpanel" aria-label={tab==='motion'?'Hareket kontrolleri':'Ölçü kontrolleri'}>
 {tab==='motion'?<>{this.field('height','Çalışma yüksekliği',80,125)}{this.field('angle','Yan tabla açısı',0,360,'°')}<div className="v8-presets" aria-label="Masa yerleşimleri">{[['Toplu',0],['L düzen',90],['Açık',180]].map(([label,a])=><button type="button" key={label as string} aria-pressed={c.angle===a} onClick={()=>this.change({angle:a as number})}>{label}</button>)}</div><div className="v8-toggle-row"><button type="button" aria-pressed={c.drawers} onClick={()=>this.change({drawers:!c.drawers})}><Icon name="plus" size={16}/>{c.drawers?'Çekmeceleri kapat':'Çekmeceleri aç'}</button><button type="button" aria-pressed={c.door} onClick={()=>this.change({door:!c.door})}><Icon name="grid" size={16}/>{c.door?'Dolabı kapat':'Dolabı aç'}</button></div></>:<>{this.field('width','Masa eni',120,220)}{this.field('depth','Masa derinliği',65,95)}<p className="v8-control-note">Bu aralıklar görsel keşif içindir. Gerçek ölçü ve mekanizma, üretim öncesi birlikte netleştirilir.</p></>}
 </div>
 <div className="v8-materials"><span>YÜZEY FİKRİ</span><div role="group" aria-label="Ahşap yüzey seçenekleri">{Object.entries(studioMaterials).map(([id,m])=><button type="button" key={id} aria-pressed={c.material===id} aria-label={m.name} onClick={()=>this.change({material:id as StudioConfig['material']})}><i className={'v8-swatch v8-'+id} style={{backgroundColor:m.color}}/><span>{m.name}</span></button>)}</div></div>
 <div className="v9-atmosphere"><span className="v9-control-kicker">MEKÂNIN ATMOSFERİ</span><div className="v9-mode-tabs" role="group" aria-label="Stüdyo görünümü"><button type="button" aria-pressed={this.state.environment==='atelier'} onClick={()=>this.atmosphere({environment:'atelier'})}>Mekân içinde</button><button type="button" aria-pressed={this.state.environment==='product'} onClick={()=>this.atmosphere({environment:'product'})}>Yalın ürün</button></div><div className="v9-atmosphere-options"><button type="button" aria-pressed={this.state.shelves} onClick={()=>this.atmosphere({shelves:!this.state.shelves})}><Icon name="grid" size={16}/><span>Çift taraflı raflar</span><i aria-hidden="true"/></button><button type="button" aria-pressed={this.state.shelfLights} onClick={()=>this.atmosphere({shelfLights:!this.state.shelfLights})}><Icon name="plus" size={16}/><span>Raf aydınlatması</span><i aria-hidden="true"/></button><button type="button" aria-pressed={this.state.styling} onClick={()=>this.atmosphere({styling:!this.state.styling})}><Icon name="leaf" size={16}/><span>Yaşam ayrıntıları</span><i aria-hidden="true"/></button></div><small>Raflar ve aksesuarlar mekân önerisidir. Masa kapsamı ayrıca belirlenir.</small></div>
 <div className="v8-primary-action">{p.compact?<Link className="button" to={'/tasarim-masasi?'+studioQuery(c)} navigate={p.navigate}>Stüdyoda devam et <Icon/></Link>:<button type="button" className="button" onClick={this.handoff}>Bu tasarımı Yusuf Usta ile konuş <Icon/></button>}<span>Ölçü, malzeme ve hareket alanını birlikte değerlendirelim.</span></div>
 </div>
 <div className="v8-showroom"><div className="v8-viewer-top"><div><span className="v8-live-dot"/><span>{ready?'CANLI 3D STÜDYO':'İNTERAKTİF TASARIM STÜDYOSU'}</span></div><span>ATELIER / DEVİR 01</span></div>
 <div className="v8-canvas-wrap"><div className="v8-canvas-host" ref={e=>this.host=e}/>{!ready&&<div className="v8-poster"><img src={image('devir-poster.webp')} alt="Çekmeceli ana tabla, dolap ve döner yan yüzeyli Devir 01 konsept çalışma masası"/><div className="v8-poster-action">{status==='poster'?<button type="button" aria-label="3D deneyimi başlat" onClick={this.start}><span className="v8-cube" aria-hidden="true">◇</span>3D deneyimi başlat <Icon size={18}/></button>:status==='loading'?<p role="status">Malzemeler ve ışık hazırlanıyor.</p>:<><p role="status">{status==='lost'?'3D görüntü bağlantısı kesildi.':'Bu cihazda 3D görünüm açılamadı.'}</p><small>Ölçü ve malzeme seçiminiz korunur. Tasarım özetiyle devam edebilirsiniz.</small></>}</div></div>}
 <div className="v8-view-tabs" role="group" aria-label="Kamera açıları">{[['perspective','Perspektif'],['front','Önden'],['left','Soldan'],['right','Sağdan'],['top','Üstten']].map(([id,name])=><button type="button" key={id} disabled={!ready} aria-pressed={view===id} onClick={()=>this.setView(id)}>{name}</button>)}</div>
 <div className="v8-view-tools"><button type="button" disabled={!ready} aria-label="Stüdyoyu tam ekran aç" onClick={this.fullscreen}><Icon name="expand"/></button><button type="button" disabled={!ready} aria-label="Yakınlaştır" onClick={()=>this.engine?.zoom(.88)}><Icon name="plus"/></button><button type="button" disabled={!ready} aria-label="Uzaklaştır" onClick={()=>this.engine?.zoom(1.12)}><Icon name="minus"/></button><button type="button" disabled={!ready} aria-label="Görünümü sıfırla" onClick={()=>this.setView('perspective')}>↺</button><button type="button" disabled={!ready} aria-label="Ölçü çizgilerini göster" aria-pressed={dimensions} onClick={()=>this.setState({dimensions:!dimensions},()=>this.engine?.dimensions(this.state.dimensions))}><Icon name="ruler"/></button></div>
 <span className="v8-canvas-hint">{ready?'Sürükleyerek döndürün. Klavyede ok tuşlarını kullanın.':'Gerçek zamanlı üç boyutlu model'}</span><span className="v8-scene-label">Konsept model</span>
 </div>
 <div className="v8-viewer-bottom"><div><span>SEÇTİĞİNİZ ÖLÇÜ</span><strong>{c.width} <i>×</i> {c.depth} <i>×</i> {c.height}<small> cm</small></strong></div><div className="v8-light-options" role="group" aria-label="Stüdyo ışığı"><button type="button" aria-pressed={light==='day'} onClick={()=>this.setState({light:'day'},()=>this.engine?.light('day'))}>Gün ışığı</button><button type="button" aria-pressed={light==='evening'} onClick={()=>this.setState({light:'evening'},()=>this.engine?.light('evening'))}>Akşam</button></div><button type="button" disabled={!ready} className="v8-export" onClick={this.snapshot}><Icon name="download" size={19}/><span>Görünümü kaydet</span></button></div>
 <div className="v8-experience-foot"><span><Icon name="ruler" size={16}/>Ölçüye göre değişen geometri</span><span><Icon name="grid" size={16}/>Çift raflı mekân kurgusu</span><span>Three.js / WebGL</span></div>
 {!p.compact&&<><div className="v8-export-row"><button className="text-link" type="button" onClick={()=>downloadText('Elif-Devir-01-Tasarim.txt',studioSummary(c))}>Ölçü özetini indir <Icon name="download" size={17}/></button><button className="text-link" type="button" aria-expanded={this.state.share} onClick={()=>this.setState({share:!this.state.share})}>Tasarım bağlantısı <Icon name="diagonal" size={17}/></button><button type="button" className="text-link" disabled={!ready} aria-pressed={this.state.rotating} onClick={()=>this.setState({rotating:!this.state.rotating},()=>this.engine?.rotate(this.state.rotating))}>{this.state.rotating?'Dönüşü durdur':'Yavaşça döndür'} <Icon name="clock" size={17}/></button></div>{this.state.share&&<label className="v8-share-field">Yalnız model seçeneklerinizi içeren bağlantı<input aria-label="Paylaşılabilir 3D tasarım bağlantısı" readOnly value={this.shareURL()} onFocus={e=>e.currentTarget.select()}/><small>Kişisel not veya iletişim bilgisi içermez.</small></label>}</>}
 <p className="v8-engineering-note">Konsept modeldir. Nihai mekanizma, yük kapasitesi, hareket açıklığı ve üretim ölçüleri atölye onayı gerektirir. Bu sahne teknik imalat çizimi veya güvenlik testi değildir.</p>
 </div></div>}
}
