const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file){const cache={};function req(f){f=path.resolve(f);if(cache[f])return cache[f].exports;const m={exports:{}};cache[f]=m;const js=ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,jsxFactory:'createElement',jsxFragmentFactory:'Fragment'}}).outputText;new Function('module','exports','require',js)(m,m.exports,id=>{if(id==='react')return{createElement:(type,props,...children)=>({type,props:{...props,children}}),Fragment:'fragment',Component:class{constructor(props){this.props=props;}setState(x,cb){this.state={...this.state,...(typeof x==='function'?x(this.state):x)};cb?.()}}};if(id.startsWith('.')){const b=path.resolve(path.dirname(f),id);return req(fs.existsSync(b+'.ts')?b+'.ts':b+'.tsx')}return require(id)});return m.exports;}return req(file);}
function walk(n,fn){if(!n)return;if(Array.isArray(n))return n.forEach(v=>walk(v,fn));if(typeof n==='object'){fn(n);walk(n.props?.children,fn)}}
function env(fn){const w=global.window,d=global.document;let seq=0;const timers=new Map();global.window={setTimeout(f,ms){timers.set(++seq,{f,ms,kind:'timeout'});return seq},clearTimeout(id){timers.delete(id)},setInterval(f,ms){timers.set(++seq,{f,ms,kind:'interval'});return seq},clearInterval(id){timers.delete(id)}};global.document={hidden:false};const h=new(load('src/pages/Home.tsx').Home)({});h.alive=true;h.motion={matches:false};h.visible=true;return Promise.resolve().then(()=>fn(h,timers)).finally(()=>{global.window=w;global.document=d})}
test('first reveal starts at 2.2s, later reveals at 3.2s, without repeating interval races',()=>env((h,t)=>{h.reschedule();assert.equal(t.size,1);assert.equal([...t.values()][0].ms,2200);assert.equal([...t.values()][0].kind,'timeout');h.hasAdvanced=true;h.reschedule();assert.equal(t.size,1);assert.equal([...t.values()][0].ms,3200)}));
test('stationary text or background mouse hover cannot silently stop the full-screen hero',()=>{const h=new(load('src/pages/Home.tsx').Home)({});let hero;walk(h.render(),n=>{if(n.type==='section'&&n.props.className?.includes('v232-carousel'))hero=n});assert.ok(hero);assert.equal(hero.props.onMouseEnter,undefined);assert.equal(hero.props.onPointerEnter,undefined)});
test('five named scene buttons, a position counter and explicit previous/next controls are discoverable',()=>{const h=new(load('src/pages/Home.tsx').Home)({});let prev,next,counter,choices=[];walk(h.render(),n=>{if(n.props?.['aria-label']==='Önceki mekân')prev=n;if(n.props?.['aria-label']==='Sonraki mekân')next=n;if(n.props?.className==='hero-sequence-position')counter=n;if(n.type==='button'&&/sahnesi$/.test(n.props?.['aria-label']||''))choices.push(n)});assert.ok(prev&&next&&counter);assert.equal(choices.length,5);assert.match(JSON.stringify(counter),/05/)});
test('keyboard focus keeps autoplay paused until the user explicitly restarts it',()=>env((h,t)=>{let hero;walk(h.render(),n=>{if(n.type==='section'&&n.props.className?.includes('v232-carousel'))hero=n});hero.props.onFocusCapture({target:{matches:()=>true}});assert.equal(h.state.paused,true);assert.equal(t.size,0);hero.props.onBlurCapture({currentTarget:{contains:()=>false},relatedTarget:null});assert.equal(t.size,0)}));
test('reduced motion, hidden document and offscreen scene keep autoplay stopped',()=>env((h,t)=>{h.motion.matches=true;h.reschedule();assert.equal(t.size,0);h.motion.matches=false;global.document.hidden=true;h.reschedule();assert.equal(t.size,0);global.document.hidden=false;h.visible=false;h.reschedule();assert.equal(t.size,0)}));
test('pausing invalidates decoded images waiting to replace the current slide',()=>env(async(h,t)=>{let resolve;h.hero={querySelector:()=>({naturalWidth:1200,decode:()=>new Promise(r=>resolve=r)})};h.setScene(1);h.state.paused=true;h.reschedule();resolve();await Promise.resolve();await Promise.resolve();assert.equal(h.state.scene,0)}));
test('manual next and previous wrap through the same five images without changing routes',()=>env(async(h,t)=>{h.hero={querySelector:()=>({naturalWidth:1200,decode:()=>Promise.resolve()})};await h.setScene(4);await h.setScene((h.state.scene+1)%5);assert.equal(h.state.scene,0);await h.setScene((h.state.scene+4)%5);assert.equal(h.state.scene,4)}));
