import {createElement,Fragment,Component} from 'react';
import {Icon,Link,Eyebrow,ButtonLink,type PageProps} from '../components/ui';
import {VImage,SourceTag} from '../components/PortfolioUI';
import {workCategories,categoryName} from '../lib/portfolio';
import {normalizeReference,modelInputError,modelSummary,type ModelRequest} from '../lib/model-request';
import {downloadText,validateFile} from '../lib/domain';
type ModelFile={name:string;url:string;file:File};
export class BringModel extends Component<PageProps&{query?:string},{step:number;v:ModelRequest;files:ModelFile[];error:string;loading:boolean}>{
 private alive=true;
 constructor(p:PageProps&{query?:string}){super(p);const q=new URLSearchParams(p.query||''),category=q.get('kategori')||'ozel-tasarim';this.state={step:0,v:{category:workCategories.some(c=>c.id===category)?category:'ozel-tasarim',url:normalizeReference(q.get('ref')||'')||'',note:(q.get('fikir')||'').slice(0,1600),dimensions:'',district:'',timing:'Birlikte planlayalım',interpretation:'Alanıma göre birlikte yorumlayalım'},files:[],error:'',loading:false}}
 componentWillUnmount(){this.alive=false;this.state.files.forEach(f=>URL.revokeObjectURL(f.url))}
 set=(key:keyof ModelRequest,value:string)=>this.setState(s=>({v:{...s.v,[key]:value},error:''}));
 go=(step:number)=>{if(step>0){const error=modelInputError({...this.state.v,files:this.state.files});if(error){this.setState({error});return}}this.setState({step,error:''},()=>document.getElementById('model-step-title')?.focus({preventScroll:true}))};
 async add(list:FileList|null){if(!list)return;const files=Array.from(list);if(files.length+this.state.files.length>5){this.setState({error:'En fazla 5 görsel ekleyebilirsiniz.'});return}this.setState({loading:true,error:''});const accepted:ModelFile[]=[];let error='';for(const file of files){const validation=validateFile(file);if(!validation.ok){error=validation.error||'Bu dosya desteklenmiyor.';continue}try{const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const signature=(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)||(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)||(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP');if(!signature){error='Dosya uzantısı değil, gerçek görsel içeriği gerekli.';continue}const b=await createImageBitmap(file);const tooLarge=b.width*b.height>40000000;b.close();if(tooLarge){error='40 megapikselden küçük bir görsel seçin.';continue}accepted.push({name:file.name,file,url:URL.createObjectURL(file)})}catch{error='Görsel okunamadı. JPG, PNG veya WebP deneyin.'}}if(this.alive)this.setState(s=>({files:[...s.files,...accepted],loading:false,error}));else accepted.forEach(f=>URL.revokeObjectURL(f.url))}
 text=()=>modelSummary({...this.state.v,category:categoryName(this.state.v.category)},this.state.files.map(f=>f.name));
 render(){const a=this.props,{v,files,step}=this.state;return <>
 <header className="v6-page-head wrap model-head"><Eyebrow>ELİF / SİZİN FİKRİNİZ</Eyebrow><div><h1>Kendi modelinizi getirin.<br/><em>Birlikte üretelim.</em></h1><p>Pinterest bağlantınızı, bir fotoğrafı veya küçük bir çizimi ekleyin. Aynısını söz vermek yerine, size uygun olanı birlikte düşünelim.</p></div></header>
 <section className="wrap model-request"><aside className="model-aside"><div><VImage asset="concept-model" alt="Mobilya fikirleri, çizimler ve numunelerden oluşan yapay zekâ konsepti" eager sizes="(max-width: 800px) 90vw, 34vw"/><SourceTag kind="concept"/></div><h2>Her fikir,<br/><em>konuşmaya değer.</em></h2><p>Modelin biçimini, kullanım amacını, malzeme ve ölçü seçeneklerini Yusuf Usta ile değerlendirebiliriz.</p><ol><li><span>01</span>Bir model veya fikir</li><li><span>02</span>Size göre ayrıntılar</li><li><span>03</span>Bir arada proje özeti</li></ol><p className="fineprint">Bu araç özetinizi cihazınızda hazırlar. Otomatik gönderim veya sipariş oluşturmaz. Görseller yalnız bu açık sayfada kalır.</p></aside>
 <div className="model-form"><nav className="model-stepper" aria-label="Model paylaşım adımları">{['Modeliniz','Ayrıntılar','Özet'].map((title,i)=><button key={title} type="button" aria-current={step===i?'step':undefined} disabled={i>step} onClick={()=>this.go(i)}><span>{String(i+1).padStart(2,'0')}</span>{title}</button>)}</nav><div className="model-form-inner"><Eyebrow>ADIM {step+1} / 3</Eyebrow><h2 id="model-step-title" tabIndex={-1}>{['Neyi beğendiniz?','Sizin için nasıl olsun?','Fikriniz artık bir arada.'][step]}</h2>
 <form noValidate onSubmit={e=>{e.preventDefault();if(step<2)this.go(step+1)}}>
 {step===0&&<><label className="form-field" htmlFor="model-url"><span>Pinterest veya model bağlantısı</span><input id="model-url" type="url" value={v.url} maxLength={2000} autoComplete="off" onInput={e=>this.set('url',e.currentTarget.value)} placeholder="https://pin.it/…" aria-describedby="model-url-help"/></label><p className="field-hint" id="model-url-help">Pinterest, bir tasarım sayfası veya kendi modelinizin HTTPS bağlantısı. Bağlantının içeriği otomatik okunmaz.</p><div className="or-divider"><span>ya da bir görsel ekleyin</span></div><label className="model-dropzone"><Icon name="upload" size={30}/><strong>{this.state.loading?'Görseller kontrol ediliyor…':'Fotoğraf veya çiziminizi seçin'}</strong><span>JPG, PNG, WebP. En fazla 5 dosya, her biri 10 MB.</span><input aria-label="Model görsellerini seç" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={this.state.loading} onChange={e=>{this.add(e.currentTarget.files);e.currentTarget.value=''}}/></label>{files.length>0&&<div className="model-uploads">{files.map((f,i)=><div key={f.url}><img src={f.url} alt={f.name}/><span>{f.name}</span><button type="button" aria-label={f.name+' görselini kaldır'} onClick={()=>{URL.revokeObjectURL(f.url);this.setState({files:files.filter((_,j)=>j!==i)})}}><Icon name="close" size={16}/></button></div>)}</div>}<label className="form-field spaced" htmlFor="model-note"><span>Modelde neyi sevdiniz?</span><textarea id="model-note" rows={4} value={v.note} maxLength={1600} onInput={e=>this.set('note',e.currentTarget.value)} placeholder="Örneğin, yuvarlak köşelerini sevdim. Daha küçük bir ölçü ve açık ton istiyorum."/></label><p className="field-hint">Henüz görseliniz yoksa fikrinizi yazmanız da yeterli.</p></>}
 {step===1&&<><label className="form-field">Ürün veya uygulama türü<select aria-label="Model kategorisi" value={v.category} onChange={e=>this.set('category',e.currentTarget.value)}>{workCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-field">Yaklaşık ölçü, biliyorsanız<input value={v.dimensions} maxLength={160} onInput={e=>this.set('dimensions',e.currentTarget.value)} placeholder="Örneğin, en 180 cm, derinlik 45 cm"/></label><p className="field-hint">Kesin ölçünüz yoksa boş bırakın. Bu aşamada üretim ölçüsü gerekmiyor.</p><div className="form-row"><label className="form-field">Uygulama ili veya ilçesi<input value={v.district} maxLength={100} onInput={e=>this.set('district',e.currentTarget.value)} placeholder="İstanbul, Kadıköy gibi"/></label><label className="form-field">Zaman beklentiniz<input value={v.timing} maxLength={160} onInput={e=>this.set('timing',e.currentTarget.value)}/></label></div><label className="form-field">Nasıl yorumlayalım?<select value={v.interpretation} aria-label="Tasarım yaklaşımı" onChange={e=>this.set('interpretation',e.currentTarget.value)}><option>Alanıma göre birlikte yorumlayalım</option><option>Benzer bir form, farklı ölçü ve malzeme</option><option>Yalnız bir ayrıntısından ilham alalım</option></select></label><div className="model-advice"><Icon name="ruler"/><p>Malzeme, donanım, mekanizma ve uygulanabilirlik görüşmede netleşir. Seçilen model, otomatik üretim onayı veya birebir kopya taahhüdü değildir.</p></div></>}
 {step===2&&<><p className="model-summary-intro">Özetinizi gözden geçirip cihazınıza kaydedebilir veya WhatsApp'ta seçtiğiniz kişiye paylaşabilirsiniz.</p><dl className="model-summary"><div><dt>İhtiyaç</dt><dd>{categoryName(v.category)}</dd></div><div><dt>Model</dt><dd>{v.url?<a href={normalizeReference(v.url)||undefined} target="_blank" rel="noopener noreferrer">Kaynak bağlantısını aç <Icon name="diagonal" size={15}/></a>:'Açıklama veya görsel ile'}</dd></div><div><dt>Ölçü</dt><dd>{v.dimensions||'Birlikte belirlenecek'}</dd></div><div><dt>Yaklaşım</dt><dd>{v.interpretation}</dd></div><div><dt>Görseller</dt><dd>{files.length} dosya, yalnız bu sayfada</dd></div></dl>{v.note&&<blockquote className="model-quote">{v.note}</blockquote>}<div className="model-export"><button type="button" className="button" onClick={()=>downloadText('Elif_Tasarim_Model_Ozeti.txt',this.text())}>Proje özetimi indir <Icon name="download"/></button><a className="button button-outline" href={'https://wa.me/?text='+encodeURIComponent(this.text())} target="_blank" rel="noopener noreferrer">WhatsApp'ta paylaş <Icon name="diagonal"/></a></div><div className="model-sharing-note"><Icon name="info"/><p><strong>Henüz atölyeye gönderilmedi.</strong> WhatsApp açıldığında alıcıyı siz seçersiniz. İşletmenin doğrulanmış numarası bu sürümde tanımlı değil. Görselleri görüşmeye ayrıca ekleyin.</p></div></>}
 {this.state.error&&<p className="model-error" role="alert">{this.state.error}</p>}
 <div className="model-actions">{step>0?<button type="button" className="back-button" onClick={()=>this.go(step-1)}><span className="reverse-arrow"><Icon/></span>{step===2?'Bilgileri düzenle':'Geri'}</button>:<span className="field-hint">Önce bir fikirle başlayalım.</span>}{step<2&&<button type="submit" className="button" disabled={this.state.loading}>Devam et <Icon/></button>}</div></form>
 </div></div></section><div className="wrap model-more"><p>Ölçü ve malzemeyi daha ayrıntılı çalışmak isterseniz.</p><ButtonLink to="/teklif-al" navigate={a.navigate} secondary>Özel ölçü stüdyosunu aç</ButtonLink></div></>}
}
