import {createElement,Fragment,Component} from 'react';
import {Link,Icon,ButtonLink,TextLink,Eyebrow,Accordion,type PageProps} from '../components/ui';
import {VImage,WorkCard,SourceTag,ModelCallout} from '../components/PortfolioUI';
import {works,featuredWorks,workCategories,concepts} from '../lib/portfolio';
import {ConceptCard} from './Portfolio';
import {TableDrawing} from './DesignDesk';
import {defaultDesk,deskQuery,type Desk} from '../lib/desk';
const scenes=[{image:'concept-hero',caption:'Bir masanın etrafında.',label:'Yaşam'},{image:'concept-mutfak',caption:'Evin kalbinde.',label:'Mutfak'},{image:'concept-kahve',caption:'Kendinize küçük bir köşe.',label:'Kahve'}];
export class Home extends Component<PageProps,{scene:number;desk:Desk;chapter:number}>{
 state={scene:0,desk:{...defaultDesk},chapter:0};
 render(){const a=this.props,s=this.state,scene=scenes[s.scene];return <div className="v6-home">
 <section className="v6-hero" aria-label="Elif Tasarım açılış seçkisi"><div className="v6-hero-scene" key={scene.image}><VImage asset={scene.image} alt={scene.caption+' Yapay zekâ ile hazırlanmış temsili mobilya sahnesi.'} eager full sizes="100vw"/></div><div className="v6-hero-shade"/><div className="wrap v6-hero-inner"><Eyebrow>İSTANBUL / EL YAPIMI MOBİLYA ATÖLYESİ</Eyebrow><h1>Zamana değer<br/>{" "}<em>katan mobilyalar.</em></h1><p>Usta ellerden, sizin yaşam alanınıza.<br/>Ölçünüze, ihtiyacınıza ve hikâyenize göre.</p><div className="v6-hero-actions"><ButtonLink to="/projeler" navigate={a.navigate}>Bitirdiğimiz işleri keşfedin</ButtonLink><TextLink to="/modelini-getir" navigate={a.navigate} light>Kendi modelinizi getirin</TextLink></div></div><div className="wrap v6-hero-bottom"><div className="v6-scene-controls" role="group" aria-label="Açılış sahneleri">{scenes.map((sc,i)=><button key={sc.image} onClick={()=>this.setState({scene:i})} aria-pressed={s.scene===i} aria-label={sc.label+' sahnesi'}><span>{String(i+1).padStart(2,'0')}</span><i/><span className="scene-word">{sc.label}</span></button>)}</div><span className="v6-hero-caption">{scene.caption}</span><button className="hero-down" aria-label="Bitirdiğimiz işlere kaydır" onClick={()=>document.getElementById('bitirdigimiz-isler')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant' as ScrollBehavior:'smooth'})}><Icon name="down"/></button></div><span className="hero-source">TEMSİLİ TASARIM SAHNESİ / YAPAY ZEKÂ KONSEPTİ</span></section>
 <section id="bitirdigimiz-isler" className="wrap v6-section home-works"><div className="v6-heading"><div><Eyebrow>01 / ATÖLYEDEN YAŞAMA</Eyebrow><h2>Bitirdiğimiz işlerden<br/><em>seçkiler.</em></h2></div><div><p>Gerçek mekânlar, gerçek çalışmalar.<br/>Yusuf Usta'nın paylaştığı uygulama arşivinden.</p><TextLink to="/projeler" navigate={a.navigate}>Tüm çalışmalar</TextLink></div></div><div className="work-grid">{featuredWorks.map((id,i)=><WorkCard key={id} work={works.find(w=>w.id===id)!} actions={a} featured index={i}/>)}</div></section>
 <section className="home-yusuf"><div className="home-yusuf-image"><VImage asset="work-joinery" alt="Ahşap kamelya çalışmasından gerçek çatı ve birleşim ayrıntıları" sizes="(max-width: 800px) 100vw, 60vw"/><span>UYGULAMA ARŞİVİNDEN BİR AYRINTI</span></div><div className="home-yusuf-copy"><Eyebrow>YUSUF USTA'NIN ELİNDEN ÇIKANLAR</Eyebrow><h2>Bir meslekten fazlası.<br/><em>Bir aile mirası.</em></h2><p>Babasından öğrendiği marangozluk, Yusuf Usta'nın elinde bugünün yaşam alanlarına uyarlanıyor. Her iş, bir ihtiyacı dinlemekle başlıyor.</p><p>Ölçüyü birlikte düşünmek, malzemeyi doğru seçmek ve atölyedeki emeği yerinde uygulamayla tamamlamak. Bizim için işin özü bu.</p><TextLink to="/hakkimizda" navigate={a.navigate} light>Hikâyemizi keşfedin</TextLink><div className="yusuf-notes"><span>Aile atölyesi</span><span>Ölçüye özel</span><span>Üretim & uygulama</span></div></div></section>
 <section className="wrap v6-section home-categories"><div className="v6-heading"><div><Eyebrow>02 / YAŞAMIN HER ALANI</Eyebrow><h2>Eviniz gibi,<br/><em>size özel.</em></h2></div><TextLink to="/kategoriler" navigate={a.navigate}>Tüm kategoriler</TextLink></div><div className="category-editorial">{[workCategories[0],workCategories[4],workCategories[5]].map((c,i)=><Link className={'editorial-tile tile-'+i} key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate}><VImage asset={c.image} alt={c.name+' için temsili tasarım fikri'} sizes={i===0?'(max-width: 700px) 90vw, 55vw':'(max-width: 700px) 90vw, 32vw'}/><div><span>0{i+1} / KONSEPT SEÇKİSİ</span><h3>{c.name}</h3><p>{c.line}</p><Icon name="diagonal" size={25}/></div></Link>)}</div><div className="category-links">{workCategories.filter(c=>!['mutfak','kahve-kosesi','sehpa'].includes(c.id)).map(c=><Link key={c.id} to={'/kategoriler/'+c.id} navigate={a.navigate}>{c.name}<Icon name="diagonal" size={17}/></Link>)}<Link to="/ilham-modelleri" navigate={a.navigate}>İlham Modelleri <Icon name="diagonal" size={17}/></Link></div></section>
 <ModelCallout navigate={a.navigate}/>
 <section className="wrap v6-section home-inspiration"><div className="v6-heading"><div><Eyebrow>03 / İLHAM DEFTERİ</Eyebrow><h2>Aklınızda bir fikir.<br/><em>Önünüzde yeni olasılıklar.</em></h2></div><div><p>Seçilmiş konseptler ve Pinterest'ten kaydettiğimiz modeller. Tamamlanmış işler değil, birlikte konuşmak için başlangıç noktaları.</p><TextLink to="/ilham-modelleri" navigate={a.navigate}>İlham defterini açın</TextLink></div></div><div className="concept-grid three">{concepts.slice(0,3).map(c=><ConceptCard key={c.id} c={c} navigate={a.navigate}/>)}</div></section>
 <section className="v6-process"><div className="wrap"><div className="v6-heading"><div><Eyebrow>04 / FİKİRDEN UYGULAMAYA</Eyebrow><h2>Birlikte <em>nasıl ilerleriz?</em></h2></div><p>Acele bir seçim değil, iyi düşünülmüş bir parça. Her aşamada ihtiyacınızı ve kullanımınızı merkeze alırız.</p></div><div className="process-steps">{[['Fikrinizi dinleriz.','Bir Pinterest bağlantısı, fotoğraf veya kendi çiziminiz. Önce nasıl kullanacağınızı konuşuruz.'],['Ölçüyü netleştiririz.','Malzeme, renk, donanım ve alanın ölçülerini birlikte değerlendiririz. Teklif bu ayrıntılarla şekillenir.'],['Atölyede şekillenir.','Üzerinde anlaşılan tasarım, ölçü ve malzemeyle üretim planlanır.'],['Yerini bulur.','Teslim ve gerekiyorsa yerinde uygulama, projenin koşullarına göre birlikte düzenlenir.']].map(([title,text],i)=><article key={title}><span className="process-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="wrap v6-section home-desk"><div><Eyebrow>05 / DİJİTAL TASARIM MASASI</Eyebrow><h2>Bir ölçüyle<br/><em>başlayalım mı?</em></h2><p>Masanızın enini değiştirin. Fikrin ilk çizgisini görün. Daha sonra derinlik, yükseklik ve malzemeyi tasarım masasında birlikte düşünün.</p><label className="home-desk-control"><span>MASA ENİ <output>{s.desk.width} cm</output></span><input type="range" min="100" max="240" step="1" aria-label="Ana sayfa masa eni" value={s.desk.width} onInput={e=>this.setState({desk:{...s.desk,width:Number(e.currentTarget.value)}})}/></label><ButtonLink to={'/tasarim-masasi?'+deskQuery(s.desk)} navigate={a.navigate}>Tasarım masasında devam et</ButtonLink><small>Şematik fikir aracıdır. Teknik üretim çizimi değildir.</small></div><div className="home-desk-drawing"><span>ELİF / ÇALIŞMA NO. 01</span><TableDrawing desk={s.desk} id="v6-home-desk" compact/><div><span>{s.desk.width} × {s.desk.depth} × {s.desk.height} cm</span><span>ÖLÇÜNÜZE GÖRE</span></div></div></section>
 <section className="wrap v6-section home-faq"><div><Eyebrow>AKLINIZDA KALMASIN</Eyebrow><h2>Birlikte<br/><em>netleştirelim.</em></h2><TextLink to="/iletisim" navigate={a.navigate}>İletişim</TextLink></div><Accordion items={[["Pinterest'te beğendiğim bir modeli getirebilir miyim?",'Evet. Bağlantıyı, fotoğrafı veya çiziminizi paylaşabilirsiniz. Modelin kullanımını, ölçülerini ve malzemesini birlikte değerlendirip size uygun özgün bir yaklaşım üzerinde konuşuruz. Her model için üretilebilirlik ayrıca teyit edilir.'],['Kesin ölçülerimi bilmiyorum. Başlayabilir miyim?','Elbette. İlk aşamada yaklaşık ölçü veya mekân fotoğrafı yeterli olabilir. Üretimden önce ölçüler ve yerleşim ayrıca netleştirilir.'],['Konsept görseller sizin tamamladığınız işler mi?','Hayır. Bitirdiğimiz İşler bölümünde atölyenin paylaştığı fotoğraflar bulunur. Yapay zekâ konseptleri ve Pinterest bağlantıları ayrı etiketlerle ilham amacıyla gösterilir.'],['Yeni atölye adresi nerede?','İstanbul’daki yeni atölye adresi netleştiğinde burada paylaşılacak. Ziyaret bilgileri adresle birlikte duyurulacak. Proje fikrinizi model paylaşım alanında hazırlayabilirsiniz.']]}/></section>
 <section className="v6-final-cta"><div className="wrap"><Eyebrow>SİZİN FİKRİNİZ. BİZİM USTALIĞIMIZ.</Eyebrow><h2>Aklınızdaki modeli gönderin.<br/><em>Birlikte yorumlayalım.</em></h2><ButtonLink to="/modelini-getir" navigate={a.navigate}>Fikrimi paylaşayım</ButtonLink><p>Bir fotoğraf, bir bağlantı ya da yalnızca bir fikir.</p></div></section>
 </div>}
}
