const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const cache={};function load(p){p=path.resolve(p);if(cache[p])return cache[p].exports;const m={exports:{}};cache[p]=m;const code=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('module','exports','require',code)(m,m.exports,id=>id.startsWith('.')?load(path.resolve(path.dirname(p),id)+'.ts'):require(id));return m.exports;}
const project=load('src/lib/project.ts');
test('report V21 project changes are observable and replacement resets reference authority',()=>{const s=project.createProjectStore();let changes=0;const off=s.subscribe(()=>changes++);s.patch({note:'Gerçek kişisel not'});const d=s.get();s.adoptReference('a',{category:'mutfak',note:'Mutfak'});s.restore(d);assert.equal(s.get().note,'Gerçek kişisel not');assert.equal(s.get().sourceRef,null);s.adoptReference('a',{category:'mutfak',note:'Mutfak'});assert.equal(s.get().category,'mutfak');assert.ok(changes>=4);off();});
test('report V21 recovery file roundtrips authored fields, measurements and model without images',()=>{const r=load('src/lib/draft-recovery.ts');const s=project.createProjectStore();s.patch({note:'Mutfak için açık ton istiyorum',district:'İstanbul',width:'180',depth:'65',height:'90',unknown:false});const text=r.encodeDraft(s.get(),1000);const d=r.decodeDraft(text);assert.equal(d.note,s.get().note);assert.equal(d.district,'İstanbul');assert.equal(d.width,'180');assert.ok(!text.includes('data:image'));assert.ok(!text.includes('blob:'));assert.equal(d.revision,0);});
test('report V21 recovery rejects foreign schemas, unsafe URL and oversized records without mutating',()=>{const r=load('src/lib/draft-recovery.ts');assert.throws(()=>r.decodeDraft('{}'));assert.throws(()=>r.decodeDraft('x'.repeat(r.MAX_BACKUP_BYTES+1)));const raw=JSON.parse(r.encodeDraft(project.emptyProject(),1000));raw.project.url='javascript:alert(1)';assert.throws(()=>r.decodeDraft(JSON.stringify(raw)));raw.project.url='';raw.project.note={bad:true};assert.throws(()=>r.decodeDraft(JSON.stringify(raw)));});
test('report V21 local record expires and erase affects only its own key',()=>{const r=load('src/lib/draft-recovery.ts'),map=new Map([['other-app','keep']]),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const b=r.createDraftBackup(storage);assert.equal(b.read(1000).kind,'empty');assert.equal(map.size,1);assert.equal(b.save(project.emptyProject(),1000).ok,true);assert.equal(b.read(1001).kind,'ready');assert.equal(b.read(1000+r.BACKUP_TTL_MS+1).kind,'expired');assert.equal(map.get('other-app'),'keep');assert.equal(b.erase(),true);});
test('report V21 denied storage never claims a successful save',()=>{const r=load('src/lib/draft-recovery.ts'),b=r.createDraftBackup({getItem(){throw Error('blocked')},setItem(){throw Error('quota')},removeItem(){throw Error('blocked')}});assert.equal(b.read().kind,'unavailable');assert.equal(b.save(project.emptyProject()).ok,false);});
test('report V21 email composer exposes missing recipient and preserves full summary separately',()=>{const c=load('src/lib/contact-options.ts'),t='Not, ölçü ve kapsam.\n'+('ş'.repeat(10000));const e=c.emailDraft(t);assert.equal(e.recipient,'');assert.equal(e.needsAttachment,true);assert.ok(e.href.startsWith('mailto:?'));assert.equal(e.fullText,t);const x=c.emailDraft('Merhaba','atolye@example.com');assert.equal(x.recipient,'atolye@example.com');assert.throws(()=>c.emailDraft('x','evil@example.com\r\nBcc: x@y.com'));assert.equal(c.smsUrl(),'sms:+905308797169');});
test('report V21 contact profile never fabricates business proof',()=>{const p=load('src/lib/site-profile.ts').getSiteProfile();assert.equal(p.email,null);assert.equal(p.address,null);assert.equal(p.hours,null);assert.deepEqual(p.social,[]);});
test('report V21 expanded FAQs and guide are available without invented terms',()=>{const d=load('src/lib/data.ts');assert.ok(d.faqs.length>=10);assert.ok(d.faqs.some(([q])=>/kapora/i.test(q)));assert.ok(d.faqs.some(([q])=>/WhatsApp/i.test(q)));assert.ok(!d.faqs.some(([,a])=>a.includes('ürün adları, ölçüler ve fiyatlar tasarım örneğidir')));const r=load('src/lib/routes.ts');assert.ok(r.v7Routes.includes('/hizmet-ve-teklif'));assert.notEqual(r.pageShareImage('/rehber/bakim'),r.pageShareImage('/proje/mutfak-ada'));});
test('report V21 schema contains truthful business node without fabricated location or review',()=>{const r=load('src/lib/routes.ts');const s=r.pageSchema('/iletisim','https://onourimpram.github.io/elif-tasarim');assert.equal(s.publisher['@type'],'Organization');assert.equal(s.publisher.telephone,'+905308797169');assert.ok(!s.publisher.address);assert.ok(!s.publisher.aggregateRating);assert.equal(s.breadcrumb['@type'],'BreadcrumbList');});
