/* One source pipeline for HTML snapshots, hashed runtime and offline preview. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),ts=require(process.env.TYPESCRIPT_PATH||'typescript');
const root=process.cwd(),out=path.join(root,'dist'),modules={};const sum=b=>crypto.createHash('sha256').update(b).digest('hex');
function collect(dir){for(const n of fs.readdirSync(dir).sort()){const p=path.join(dir,n);if(fs.statSync(p).isDirectory())collect(p);else if(/\.tsx?$/.test(n)){const id=path.relative(root,p).replaceAll('\\','/').replace(/\.tsx?$/,''),r=ts.transpileModule(fs.readFileSync(p,'utf8'),{fileName:p,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,jsxFactory:'createElement',jsxFragmentFactory:'Fragment',esModuleInterop:true,removeComments:true}});if(r.diagnostics?.some(d=>d.category===ts.DiagnosticCategory.Error))throw Error('TypeScript syntax error in '+id);modules[id]=r.outputText;}}}collect('src');
modules.react=ts.transpileModule(fs.readFileSync('tools/preview-runtime.mjs','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;modules['react-dom/client']='exports.createRoot=(root)=>({render:(node)=>require("react").render(node,root)});';
function resolve(id,from){if(!id.startsWith('.'))return id;return path.posix.normalize(path.posix.join(path.posix.dirname(from),id)).replace(/\.tsx?$/,'')}
const used=new Set();function visit(id){if(used.has(id))return;if(!modules[id])throw Error('Missing '+id);used.add(id);for(const m of modules[id].matchAll(/require\(["']([^"']+)["']\)/g))visit(resolve(m[1],id))}visit('src/main');
const table='{'+[...used].sort().map(id=>JSON.stringify(id)+':function(module,exports,require){\n'+modules[id]+'\n}').join(',\n')+'}';
const loader='const modules='+table+';const cache={};function resolve(id,from){if(!id.startsWith("."))return id;const a=from.split("/");a.pop();for(const part of id.split("/")){if(part==="..")a.pop();else if(part!==".")a.push(part)}return a.join("/").replace(/\\.tsx?$/,"")}function load(id,from=""){id=resolve(id,from);if(cache[id])return cache[id].exports;if(!modules[id])throw Error("Missing module "+id);const m={exports:{}};cache[id]=m;modules[id](m,m.exports,x=>load(x,id));return m.exports}';
const license='/*! '+fs.readFileSync('tools/PREACT_LICENSE.txt','utf8')+' */\n';
const js=license+'(function(){"use strict";'+loader+'load("src/main");})();';
const css=['src/styles.css','src/v5.css','src/v6.css','src/v7.css','src/v8.css','src/v9.css','src/v10.css','src/v11.css'].map(p=>fs.readFileSync(p,'utf8')).join('\n');
let base=(process.env.BASE_PATH??'/elif-tasarim').replace(/\/$/,'');if(!/^\/[a-z0-9/-]*$/.test(base)&&base!=='')throw Error('BASE_PATH must be a plain path');
const site=process.env.SITE_URL||'https://onourimpram.github.io'+base;const canonical=new URL(site);if(canonical.protocol!=='https:'||canonical.search||canonical.hash||canonical.username||canonical.password)throw Error('SITE_URL must be an HTTPS public origin/path');
const indexable=process.env.INDEXABLE==='1';if(indexable&&(canonical.hostname.endsWith('github.io')||!process.env.SITE_URL||process.env.COMMERCIAL_CONTENT_APPROVED!=='1'))throw Error('Commercial indexing needs a non-GitHub URL and explicit content approval');
const assetNames=fs.readdirSync('public/assets').sort();const amap=Object.fromEntries(assetNames.map(n=>[n,base+'/assets/'+n]));
amap['office.webp']=base+'/assets/office-v8.webp';amap['joinery.webp']=base+'/assets/joinery-v8.webp';
const config='window.__ELIF_PREVIEW__=false;window.__ELIF_BASE__='+JSON.stringify(base)+';window.__ELIF_SITE_URL__='+JSON.stringify(site.replace(/\/$/,''))+';window.__ELIF_INITIAL__=document.documentElement.dataset.route||"/";window.__ELIF_ASSETS__='+JSON.stringify(amap)+';';
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public/assets',out+'/assets',{recursive:true});fs.cpSync('public/three',out+'/three',{recursive:true});
const jname='app.'+sum(js).slice(0,12)+'.js',cname='styles.'+sum(css).slice(0,12)+'.css',bname='config.'+sum(config).slice(0,12)+'.js';for(const [n,text] of [[jname,js],[cname,css],[bname,config]])fs.writeFileSync(out+'/'+n,text);
const context={console,URL,URLSearchParams,TextEncoder,TextDecoder,Blob,setTimeout,clearTimeout,window:{__ELIF_PREVIEW__:false,__ELIF_BASE__:base,__ELIF_SITE_URL__:site,__ELIF_ASSETS__:amap},localStorage:{getItem:()=>null},globalThis:{}};vm.createContext(context);vm.runInContext(loader+'globalThis.load=load;',context,{timeout:10000});const load=context.globalThis.load;const {v7Routes,pageTitle,pageDescription,pageShareImage,pageSchema}=load('src/lib/routes'),App=load('src/App').default;
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const attrNames={className:'class',htmlFor:'for',tabIndex:'tabindex',srcSet:'srcset',fetchPriority:'fetchpriority',crossOrigin:'crossorigin',strokeWidth:'stroke-width',strokeLinecap:'stroke-linecap',strokeLinejoin:'stroke-linejoin',fillRule:'fill-rule',clipPath:'clip-path',stopColor:'stop-color',stopOpacity:'stop-opacity'};
const voids=new Set(['img','input','meta','link','br','hr','area','base','col','embed','param','source','track','wbr']);
function render(node){if(node==null||typeof node==='boolean')return '';if(Array.isArray(node))return node.map(render).join('');if(typeof node!=='object')return esc(node);const {type:t,props:p={}}=node;if(typeof t==='function'){if(t.prototype?.render){const c=new t(p,{});return render(c.render(p,c.state,{}))}return render(t(p))}if(!t)return esc(p);let attrs='';for(let [k,v] of Object.entries(p)){if(k==='children'||k==='key'||k==='ref'||k==='dangerouslySetInnerHTML'||/^on[A-Z]/.test(k)||v==null||typeof v==='function')continue;if(k==='style'&&typeof v==='object')v=Object.entries(v).map(([name,val])=>name.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())+':'+val+(typeof val==='number'&&val!==0&&!/opacity|zIndex|flex|order|aspectRatio|lineHeight/.test(name)?'px':'')).join(';');if(v===false&&!k.startsWith('aria-'))continue;const name=attrNames[k]||k;attrs+=typeof v==='boolean'&&!k.startsWith('aria-')?' '+name:' '+name+'="'+esc(v)+'"'}if(['button','input','textarea','select'].includes(t)&&!attrs.includes(' disabled'))attrs+=' disabled';const children=p.dangerouslySetInnerHTML?String(p.dangerouslySetInnerHTML.__html):render(p.children);return '<'+t+attrs+'>'+(!voids.has(t)?children+'</'+t+'>':'')}
const routeList=[...v7Routes].sort();function content(route){load('src/lib/project').projectStore.clear();const a=new App({initialPath:route},{});return render(a.render())}
const abs=route=>site.replace(/\/$/,'')+(route==='/'?'/':route+'/');
function documentFor(route,markup,offline=false){const title=pageTitle(route),description=pageDescription(route),schema=pageSchema(route,site);return '<!doctype html><html lang="tr" data-route="'+esc(route)+'"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="'+(indexable&&!offline?'index,follow':'noindex,nofollow')+'"><meta name="elif-release" content="v11-coherent-project"><meta name="referrer" content="no-referrer"><title>'+esc(title)+'</title><meta name="description" content="'+esc(description)+'"><meta name="theme-color" content="#654a32"><link rel="canonical" href="'+esc(abs(route))+'"><meta property="og:type" content="website"><meta property="og:locale" content="tr_TR"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+esc(abs(route))+'"><meta property="og:image" content="'+esc(site.replace(/\/$/,'')+'/assets/'+pageShareImage(route))+'"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="'+base+'/assets/favicon.png"><link rel="stylesheet" href="'+base+'/'+cname+'"><script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script><script defer src="'+base+'/'+bname+'"></script><script defer src="'+base+'/'+jname+'"></script></head><body><noscript><div class="v7-no-js">Görselleri ve sayfaları JavaScript olmadan inceleyebilirsiniz. Etkileşimli model formu için JavaScript gerekir. Yunus Usta ile <a href="tel:+905308797169">+90 530 879 71 69</a> üzerinden görüşebilirsiniz.</div></noscript><div id="static-content">'+markup+'</div><div id="app"></div></body></html>'}
for(const route of [...routeList,'/404']){const markup=content(route),html=documentFor(route,markup),dir=route==='/'?out:path.join(out,route.slice(1));if(route==='/404'){fs.writeFileSync(out+'/404.html',html);continue}fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/index.html',html)}
const aliases={'urunler':'kategoriler','sepet':'modelini-getir','odeme':'modelini-getir','atolye-demolari':'atolye','atolyemiz':'hakkimizda','mekan-fikirleri':'ilham-modelleri'};for(const [old,to]of Object.entries(aliases)){fs.mkdirSync(out+'/'+old,{recursive:true});fs.writeFileSync(out+'/'+old+'/index.html','<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta http-equiv="refresh" content="0;url='+base+'/'+to+'/"><title>Elif Tasarım</title><a href="'+base+'/'+to+'/">Güncel sayfaya devam et</a></html>')}
fs.writeFileSync(out+'/robots.txt','User-agent: *\nAllow: /\n'+(indexable?'Sitemap: '+site+'/sitemap.xml\n':''));
if(indexable)fs.writeFileSync(out+'/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routeList.filter(x=>!['/arama','/modelini-getir','/teklif-al','/calisma-dosyam'].includes(x)).map(r=>'<url><loc>'+esc(abs(r))+'</loc></url>').join('')+'</urlset>');
fs.writeFileSync(out+'/.nojekyll','');fs.writeFileSync(out+'/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  Permissions-Policy: geolocation=(), camera=(), microphone=(), web-share=(self)\n  Content-Security-Policy-Report-Only: default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: blob:; connect-src \'self\'; frame-src https://assets.pinterest.com https://www.pinterest.com; object-src \'none\'; base-uri \'self\'; form-action \'none\'; frame-ancestors \'none\'\n');
const inlineAssets=Object.fromEntries(assetNames.map(n=>[n,'data:'+(n.endsWith('.webp')?'image/webp':'image/png')+';base64,'+fs.readFileSync('public/assets/'+n).toString('base64')]));
inlineAssets['office.webp']=inlineAssets['office-v8.webp'];inlineAssets['joinery.webp']=inlineAssets['joinery-v8.webp'];
// An offline-only module graph. Publication keeps separate same-origin ESM files.
const offlineGraph={};
function moduleTree(dir){for(const n of fs.readdirSync(dir).sort()){const p=path.join(dir,n);if(fs.statSync(p).isDirectory()){moduleTree(p);continue}if(!/\.(mjs|js)$/.test(n))continue;const id=path.relative('public/three',p).replaceAll('\\','/'),code=fs.readFileSync(p,'utf8'),deps={};for(const m of code.matchAll(/(?:from\s*|import\s*)['"]([^'"]+)['"]/g)){if(m[1].startsWith('.'))deps[m[1]]=path.posix.normalize(path.posix.join(path.posix.dirname(id),m[1]));}offlineGraph[id]={code,deps};}}
moduleTree('public/three');
const offlineLoader=function(files){
 let promise=null;const urls={};
 function build(key,visiting=new Set()){
  if(urls[key])return urls[key];if(visiting.has(key))throw Error('Cyclic local module '+key);visiting.add(key);
  const f=files[key];if(!f)throw Error('Missing local module '+key);let code=f.code;
  for(const [spec,dest] of Object.entries(f.deps)){const url=build(dest,visiting);code=code.split('"'+spec+'"').join('"'+url+'"').split("'"+spec+"'").join("'"+url+"'");}
  visiting.delete(key);return urls[key]=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));
 }
 window.__ELIF_LOAD_3D__=()=>promise||(promise=import(build('desk-scene.mjs')).then(()=>window.ElifDesk3D).catch(e=>{promise=null;throw e}));
 window.addEventListener('pagehide',()=>{Object.values(urls).forEach(u=>URL.revokeObjectURL(u))},{once:true});
};
const offlineThree='('+offlineLoader.toString()+')('+JSON.stringify(offlineGraph)+');';
const offlineConfig='window.__ELIF_PREVIEW__=true;window.__ELIF_INITIAL__="/";window.__ELIF_ASSETS__='+JSON.stringify(inlineAssets)+';';
const offline='<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="elif-release" content="v11-coherent-project"><meta name="description" content="Elif Tasarım V11 tasarım önizlemesi"><title>Elif Tasarım</title><style>'+css+'</style></head><body><div id="app"></div><noscript>Yunus Usta. +90 530 879 71 69.</noscript><script>'+offlineConfig+'</script><script>'+offlineThree.replace(/<\/script/gi,'<\\/script')+'</script><script>'+js.replace(/<\/script/gi,'<\\/script')+'</script></body></html>';
fs.mkdirSync('preview',{recursive:true});fs.writeFileSync('preview/Elif_Tasarim.html',offline);
const files={};function walk(dir){for(const n of fs.readdirSync(dir).sort()){const p=path.join(dir,n);if(fs.statSync(p).isDirectory())walk(p);else files[path.relative(out,p).replaceAll('\\','/')]={bytes:fs.statSync(p).size,sha256:sum(fs.readFileSync(p))}}}walk(out);const manifest={release:'v11-coherent-project',version:'0.11.0',baseline:'cb8cf2af5f7044327dc4744014bc26baa53853a4',basePath:base,siteUrl:site,indexable,routes:routeList,modules:[...used].sort(),runtime:'Pinned local MIT Preact runtime from V6',files};fs.writeFileSync(out+'/release-v11.json',JSON.stringify(manifest,null,2));fs.writeFileSync('tests/v7/routes.json',JSON.stringify(routeList,null,2));console.log(JSON.stringify({routes:routeList.length,modules:used.size,jsBytes:Buffer.byteLength(js),cssBytes:Buffer.byteLength(css),files:Object.keys(files).length,jname,cname,offlineBytes:Buffer.byteLength(offline)},null,2));
